/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "synth_demux1x2_8bits.v:10" *)
module synth_demux1x2_8bits(data_rx00_synt, data_rx11_synt, valid_rx00_synt, valid_rx11_synt, data_rx000_synt, valid_rx000_synt, clk_2f, clk_4f, reset);
  (* src = "synth_demux1x2_8bits.v:43" *)
  wire [7:0] _000_;
  (* src = "synth_demux1x2_8bits.v:43" *)
  wire [7:0] _001_;
  (* src = "synth_demux1x2_8bits.v:27" *)
  wire [8:0] _002_;
  (* src = "synth_demux1x2_8bits.v:27" *)
  wire [8:0] _003_;
  (* src = "synth_demux1x2_8bits.v:43" *)
  wire _004_;
  (* src = "synth_demux1x2_8bits.v:43" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  (* src = "synth_demux1x2_8bits.v:14" *)
  input clk_2f;
  (* src = "synth_demux1x2_8bits.v:17" *)
  wire clk_2f_s;
  (* src = "synth_demux1x2_8bits.v:14" *)
  input clk_4f;
  (* src = "synth_demux1x2_8bits.v:10" *)
  output [7:0] data_rx00_synt;
  (* src = "synth_demux1x2_8bits.v:12" *)
  input [7:0] data_rx000_synt;
  (* src = "synth_demux1x2_8bits.v:10" *)
  output [7:0] data_rx11_synt;
  (* src = "synth_demux1x2_8bits.v:16" *)
  wire [8:0] paq_00;
  (* src = "synth_demux1x2_8bits.v:16" *)
  wire [8:0] paq_11;
  (* src = "synth_demux1x2_8bits.v:14" *)
  input reset;
  (* src = "synth_demux1x2_8bits.v:17" *)
  wire reset_s;
  (* src = "synth_demux1x2_8bits.v:11" *)
  output valid_rx00_synt;
  (* src = "synth_demux1x2_8bits.v:13" *)
  input valid_rx000_synt;
  (* src = "synth_demux1x2_8bits.v:11" *)
  output valid_rx11_synt;
  NOT _168_ (
    .A(paq_11[1]),
    .Y(_024_)
  );
  NOT _169_ (
    .A(data_rx11_synt[0]),
    .Y(_025_)
  );
  NOT _170_ (
    .A(paq_11[2]),
    .Y(_026_)
  );
  NOT _171_ (
    .A(data_rx11_synt[1]),
    .Y(_027_)
  );
  NOT _172_ (
    .A(paq_11[3]),
    .Y(_028_)
  );
  NOT _173_ (
    .A(data_rx11_synt[2]),
    .Y(_029_)
  );
  NOT _174_ (
    .A(paq_11[4]),
    .Y(_030_)
  );
  NOT _175_ (
    .A(data_rx11_synt[3]),
    .Y(_031_)
  );
  NOT _176_ (
    .A(paq_11[5]),
    .Y(_032_)
  );
  NOT _177_ (
    .A(data_rx11_synt[4]),
    .Y(_033_)
  );
  NOT _178_ (
    .A(paq_11[6]),
    .Y(_034_)
  );
  NOT _179_ (
    .A(data_rx11_synt[5]),
    .Y(_035_)
  );
  NOT _180_ (
    .A(paq_11[7]),
    .Y(_036_)
  );
  NOT _181_ (
    .A(data_rx11_synt[6]),
    .Y(_037_)
  );
  NOT _182_ (
    .A(paq_11[8]),
    .Y(_038_)
  );
  NOT _183_ (
    .A(data_rx11_synt[7]),
    .Y(_039_)
  );
  NOT _184_ (
    .A(paq_11[0]),
    .Y(_040_)
  );
  NOT _185_ (
    .A(valid_rx11_synt),
    .Y(_041_)
  );
  NOT _186_ (
    .A(valid_rx00_synt),
    .Y(_042_)
  );
  NOT _187_ (
    .A(valid_rx000_synt),
    .Y(_043_)
  );
  NOT _188_ (
    .A(data_rx000_synt[0]),
    .Y(_044_)
  );
  NOT _189_ (
    .A(data_rx000_synt[1]),
    .Y(_045_)
  );
  NOT _190_ (
    .A(data_rx000_synt[2]),
    .Y(_046_)
  );
  NOT _191_ (
    .A(data_rx000_synt[3]),
    .Y(_047_)
  );
  NOT _192_ (
    .A(data_rx000_synt[4]),
    .Y(_048_)
  );
  NOT _193_ (
    .A(data_rx000_synt[5]),
    .Y(_049_)
  );
  NOT _194_ (
    .A(data_rx000_synt[6]),
    .Y(_050_)
  );
  NOT _195_ (
    .A(data_rx000_synt[7]),
    .Y(_051_)
  );
  NOT _196_ (
    .A(data_rx00_synt[0]),
    .Y(_052_)
  );
  NOT _197_ (
    .A(data_rx00_synt[1]),
    .Y(_053_)
  );
  NOT _198_ (
    .A(data_rx00_synt[2]),
    .Y(_054_)
  );
  NOT _199_ (
    .A(data_rx00_synt[3]),
    .Y(_055_)
  );
  NOT _200_ (
    .A(data_rx00_synt[4]),
    .Y(_056_)
  );
  NOT _201_ (
    .A(data_rx00_synt[5]),
    .Y(_057_)
  );
  NOT _202_ (
    .A(data_rx00_synt[6]),
    .Y(_058_)
  );
  NOT _203_ (
    .A(data_rx00_synt[7]),
    .Y(_059_)
  );
  NOT _204_ (
    .A(clk_4f),
    .Y(_006_)
  );
  NOR _205_ (
    .A(clk_2f_s),
    .B(paq_11[2]),
    .Y(_060_)
  );
  NAND _206_ (
    .A(clk_2f_s),
    .B(_027_),
    .Y(_061_)
  );
  NAND _207_ (
    .A(reset_s),
    .B(_061_),
    .Y(_062_)
  );
  NOR _208_ (
    .A(_060_),
    .B(_062_),
    .Y(_001_[1])
  );
  NOR _209_ (
    .A(clk_2f_s),
    .B(paq_11[3]),
    .Y(_063_)
  );
  NAND _210_ (
    .A(clk_2f_s),
    .B(_029_),
    .Y(_064_)
  );
  NAND _211_ (
    .A(reset_s),
    .B(_064_),
    .Y(_065_)
  );
  NOR _212_ (
    .A(_063_),
    .B(_065_),
    .Y(_001_[2])
  );
  NOR _213_ (
    .A(clk_2f_s),
    .B(paq_11[4]),
    .Y(_066_)
  );
  NAND _214_ (
    .A(clk_2f_s),
    .B(_031_),
    .Y(_067_)
  );
  NAND _215_ (
    .A(reset_s),
    .B(_067_),
    .Y(_068_)
  );
  NOR _216_ (
    .A(_066_),
    .B(_068_),
    .Y(_001_[3])
  );
  NOR _217_ (
    .A(clk_2f_s),
    .B(paq_11[5]),
    .Y(_069_)
  );
  NAND _218_ (
    .A(clk_2f_s),
    .B(_033_),
    .Y(_070_)
  );
  NAND _219_ (
    .A(reset_s),
    .B(_070_),
    .Y(_071_)
  );
  NOR _220_ (
    .A(_069_),
    .B(_071_),
    .Y(_001_[4])
  );
  NOR _221_ (
    .A(clk_2f_s),
    .B(paq_11[6]),
    .Y(_072_)
  );
  NAND _222_ (
    .A(clk_2f_s),
    .B(_035_),
    .Y(_073_)
  );
  NAND _223_ (
    .A(reset_s),
    .B(_073_),
    .Y(_074_)
  );
  NOR _224_ (
    .A(_072_),
    .B(_074_),
    .Y(_001_[5])
  );
  NOR _225_ (
    .A(clk_2f_s),
    .B(paq_11[7]),
    .Y(_075_)
  );
  NAND _226_ (
    .A(clk_2f_s),
    .B(_037_),
    .Y(_076_)
  );
  NAND _227_ (
    .A(reset_s),
    .B(_076_),
    .Y(_077_)
  );
  NOR _228_ (
    .A(_075_),
    .B(_077_),
    .Y(_001_[6])
  );
  NOR _229_ (
    .A(clk_2f_s),
    .B(paq_11[8]),
    .Y(_078_)
  );
  NAND _230_ (
    .A(clk_2f_s),
    .B(_039_),
    .Y(_079_)
  );
  NAND _231_ (
    .A(reset_s),
    .B(_079_),
    .Y(_080_)
  );
  NOR _232_ (
    .A(_078_),
    .B(_080_),
    .Y(_001_[7])
  );
  NOR _233_ (
    .A(clk_2f_s),
    .B(paq_00[0]),
    .Y(_081_)
  );
  NAND _234_ (
    .A(clk_2f_s),
    .B(_042_),
    .Y(_082_)
  );
  NAND _235_ (
    .A(reset_s),
    .B(_082_),
    .Y(_083_)
  );
  NOR _236_ (
    .A(_081_),
    .B(_083_),
    .Y(_004_)
  );
  NOR _237_ (
    .A(clk_2f_s),
    .B(paq_11[0]),
    .Y(_084_)
  );
  NAND _238_ (
    .A(clk_2f_s),
    .B(_041_),
    .Y(_085_)
  );
  NAND _239_ (
    .A(reset_s),
    .B(_085_),
    .Y(_086_)
  );
  NOR _240_ (
    .A(_084_),
    .B(_086_),
    .Y(_005_)
  );
  NOR _241_ (
    .A(clk_2f_s),
    .B(paq_00[1]),
    .Y(_087_)
  );
  NAND _242_ (
    .A(clk_2f_s),
    .B(_052_),
    .Y(_088_)
  );
  NAND _243_ (
    .A(reset_s),
    .B(_088_),
    .Y(_089_)
  );
  NOR _244_ (
    .A(_087_),
    .B(_089_),
    .Y(_000_[0])
  );
  NOR _245_ (
    .A(clk_2f_s),
    .B(paq_00[2]),
    .Y(_090_)
  );
  NAND _246_ (
    .A(clk_2f_s),
    .B(_053_),
    .Y(_091_)
  );
  NAND _247_ (
    .A(reset_s),
    .B(_091_),
    .Y(_092_)
  );
  NOR _248_ (
    .A(_090_),
    .B(_092_),
    .Y(_000_[1])
  );
  NOR _249_ (
    .A(clk_2f_s),
    .B(paq_00[3]),
    .Y(_093_)
  );
  NAND _250_ (
    .A(clk_2f_s),
    .B(_054_),
    .Y(_094_)
  );
  NAND _251_ (
    .A(reset_s),
    .B(_094_),
    .Y(_095_)
  );
  NOR _252_ (
    .A(_093_),
    .B(_095_),
    .Y(_000_[2])
  );
  NOR _253_ (
    .A(clk_2f_s),
    .B(paq_00[4]),
    .Y(_096_)
  );
  NAND _254_ (
    .A(clk_2f_s),
    .B(_055_),
    .Y(_097_)
  );
  NAND _255_ (
    .A(reset_s),
    .B(_097_),
    .Y(_098_)
  );
  NOR _256_ (
    .A(_096_),
    .B(_098_),
    .Y(_000_[3])
  );
  NOR _257_ (
    .A(clk_2f_s),
    .B(paq_00[5]),
    .Y(_099_)
  );
  NAND _258_ (
    .A(clk_2f_s),
    .B(_056_),
    .Y(_100_)
  );
  NAND _259_ (
    .A(reset_s),
    .B(_100_),
    .Y(_101_)
  );
  NOR _260_ (
    .A(_099_),
    .B(_101_),
    .Y(_000_[4])
  );
  NOR _261_ (
    .A(clk_2f_s),
    .B(paq_00[6]),
    .Y(_102_)
  );
  NAND _262_ (
    .A(clk_2f_s),
    .B(_057_),
    .Y(_103_)
  );
  NAND _263_ (
    .A(reset_s),
    .B(_103_),
    .Y(_104_)
  );
  NOR _264_ (
    .A(_102_),
    .B(_104_),
    .Y(_000_[5])
  );
  NOR _265_ (
    .A(clk_2f_s),
    .B(paq_00[7]),
    .Y(_105_)
  );
  NAND _266_ (
    .A(clk_2f_s),
    .B(_058_),
    .Y(_106_)
  );
  NAND _267_ (
    .A(reset_s),
    .B(_106_),
    .Y(_107_)
  );
  NOR _268_ (
    .A(_105_),
    .B(_107_),
    .Y(_000_[6])
  );
  NOR _269_ (
    .A(clk_2f_s),
    .B(paq_00[8]),
    .Y(_108_)
  );
  NAND _270_ (
    .A(clk_2f_s),
    .B(_059_),
    .Y(_109_)
  );
  NAND _271_ (
    .A(reset_s),
    .B(_109_),
    .Y(_110_)
  );
  NOR _272_ (
    .A(_108_),
    .B(_110_),
    .Y(_000_[7])
  );
  NOR _273_ (
    .A(valid_rx000_synt),
    .B(clk_2f),
    .Y(_111_)
  );
  NAND _274_ (
    .A(_040_),
    .B(clk_2f),
    .Y(_112_)
  );
  NAND _275_ (
    .A(reset_s),
    .B(_112_),
    .Y(_113_)
  );
  NOR _276_ (
    .A(_111_),
    .B(_113_),
    .Y(_003_[0])
  );
  NOR _277_ (
    .A(clk_2f),
    .B(data_rx000_synt[0]),
    .Y(_114_)
  );
  NAND _278_ (
    .A(_024_),
    .B(clk_2f),
    .Y(_115_)
  );
  NAND _279_ (
    .A(reset_s),
    .B(_115_),
    .Y(_116_)
  );
  NOR _280_ (
    .A(_114_),
    .B(_116_),
    .Y(_003_[1])
  );
  NOR _281_ (
    .A(clk_2f),
    .B(data_rx000_synt[1]),
    .Y(_117_)
  );
  NAND _282_ (
    .A(_026_),
    .B(clk_2f),
    .Y(_118_)
  );
  NAND _283_ (
    .A(reset_s),
    .B(_118_),
    .Y(_119_)
  );
  NOR _284_ (
    .A(_117_),
    .B(_119_),
    .Y(_003_[2])
  );
  NOR _285_ (
    .A(clk_2f),
    .B(data_rx000_synt[2]),
    .Y(_120_)
  );
  NAND _286_ (
    .A(_028_),
    .B(clk_2f),
    .Y(_121_)
  );
  NAND _287_ (
    .A(reset_s),
    .B(_121_),
    .Y(_122_)
  );
  NOR _288_ (
    .A(_120_),
    .B(_122_),
    .Y(_003_[3])
  );
  NOR _289_ (
    .A(clk_2f),
    .B(data_rx000_synt[3]),
    .Y(_123_)
  );
  NAND _290_ (
    .A(_030_),
    .B(clk_2f),
    .Y(_124_)
  );
  NAND _291_ (
    .A(reset_s),
    .B(_124_),
    .Y(_125_)
  );
  NOR _292_ (
    .A(_123_),
    .B(_125_),
    .Y(_003_[4])
  );
  NOR _293_ (
    .A(clk_2f),
    .B(data_rx000_synt[4]),
    .Y(_126_)
  );
  NAND _294_ (
    .A(_032_),
    .B(clk_2f),
    .Y(_127_)
  );
  NAND _295_ (
    .A(reset_s),
    .B(_127_),
    .Y(_128_)
  );
  NOR _296_ (
    .A(_126_),
    .B(_128_),
    .Y(_003_[5])
  );
  NOR _297_ (
    .A(clk_2f),
    .B(data_rx000_synt[5]),
    .Y(_129_)
  );
  NAND _298_ (
    .A(_034_),
    .B(clk_2f),
    .Y(_130_)
  );
  NAND _299_ (
    .A(reset_s),
    .B(_130_),
    .Y(_131_)
  );
  NOR _300_ (
    .A(_129_),
    .B(_131_),
    .Y(_003_[6])
  );
  NOR _301_ (
    .A(clk_2f),
    .B(data_rx000_synt[6]),
    .Y(_132_)
  );
  NAND _302_ (
    .A(_036_),
    .B(clk_2f),
    .Y(_133_)
  );
  NAND _303_ (
    .A(reset_s),
    .B(_133_),
    .Y(_134_)
  );
  NOR _304_ (
    .A(_132_),
    .B(_134_),
    .Y(_003_[7])
  );
  NOR _305_ (
    .A(clk_2f),
    .B(data_rx000_synt[7]),
    .Y(_135_)
  );
  NAND _306_ (
    .A(_038_),
    .B(clk_2f),
    .Y(_136_)
  );
  NAND _307_ (
    .A(reset_s),
    .B(_136_),
    .Y(_137_)
  );
  NOR _308_ (
    .A(_135_),
    .B(_137_),
    .Y(_003_[8])
  );
  NOR _309_ (
    .A(paq_00[0]),
    .B(clk_2f),
    .Y(_138_)
  );
  NAND _310_ (
    .A(_043_),
    .B(clk_2f),
    .Y(_139_)
  );
  NAND _311_ (
    .A(reset_s),
    .B(_139_),
    .Y(_140_)
  );
  NOR _312_ (
    .A(_138_),
    .B(_140_),
    .Y(_002_[0])
  );
  NOR _313_ (
    .A(clk_2f),
    .B(paq_00[1]),
    .Y(_141_)
  );
  NAND _314_ (
    .A(clk_2f),
    .B(_044_),
    .Y(_142_)
  );
  NAND _315_ (
    .A(reset_s),
    .B(_142_),
    .Y(_143_)
  );
  NOR _316_ (
    .A(_141_),
    .B(_143_),
    .Y(_002_[1])
  );
  NOR _317_ (
    .A(clk_2f),
    .B(paq_00[2]),
    .Y(_144_)
  );
  NAND _318_ (
    .A(clk_2f),
    .B(_045_),
    .Y(_145_)
  );
  NAND _319_ (
    .A(reset_s),
    .B(_145_),
    .Y(_146_)
  );
  NOR _320_ (
    .A(_144_),
    .B(_146_),
    .Y(_002_[2])
  );
  NOR _321_ (
    .A(clk_2f),
    .B(paq_00[3]),
    .Y(_147_)
  );
  NAND _322_ (
    .A(clk_2f),
    .B(_046_),
    .Y(_148_)
  );
  NAND _323_ (
    .A(reset_s),
    .B(_148_),
    .Y(_149_)
  );
  NOR _324_ (
    .A(_147_),
    .B(_149_),
    .Y(_002_[3])
  );
  NOR _325_ (
    .A(clk_2f),
    .B(paq_00[4]),
    .Y(_150_)
  );
  NAND _326_ (
    .A(clk_2f),
    .B(_047_),
    .Y(_151_)
  );
  NAND _327_ (
    .A(reset_s),
    .B(_151_),
    .Y(_152_)
  );
  NOR _328_ (
    .A(_150_),
    .B(_152_),
    .Y(_002_[4])
  );
  NOR _329_ (
    .A(clk_2f),
    .B(paq_00[5]),
    .Y(_153_)
  );
  NAND _330_ (
    .A(clk_2f),
    .B(_048_),
    .Y(_154_)
  );
  NAND _331_ (
    .A(reset_s),
    .B(_154_),
    .Y(_155_)
  );
  NOR _332_ (
    .A(_153_),
    .B(_155_),
    .Y(_002_[5])
  );
  NOR _333_ (
    .A(clk_2f),
    .B(paq_00[6]),
    .Y(_156_)
  );
  NAND _334_ (
    .A(clk_2f),
    .B(_049_),
    .Y(_157_)
  );
  NAND _335_ (
    .A(reset_s),
    .B(_157_),
    .Y(_158_)
  );
  NOR _336_ (
    .A(_156_),
    .B(_158_),
    .Y(_002_[6])
  );
  NOR _337_ (
    .A(clk_2f),
    .B(paq_00[7]),
    .Y(_159_)
  );
  NAND _338_ (
    .A(clk_2f),
    .B(_050_),
    .Y(_160_)
  );
  NAND _339_ (
    .A(reset_s),
    .B(_160_),
    .Y(_161_)
  );
  NOR _340_ (
    .A(_159_),
    .B(_161_),
    .Y(_002_[7])
  );
  NOR _341_ (
    .A(clk_2f),
    .B(paq_00[8]),
    .Y(_162_)
  );
  NAND _342_ (
    .A(clk_2f),
    .B(_051_),
    .Y(_163_)
  );
  NAND _343_ (
    .A(reset_s),
    .B(_163_),
    .Y(_164_)
  );
  NOR _344_ (
    .A(_162_),
    .B(_164_),
    .Y(_002_[8])
  );
  NOR _345_ (
    .A(paq_11[1]),
    .B(clk_2f_s),
    .Y(_165_)
  );
  NAND _346_ (
    .A(_025_),
    .B(clk_2f_s),
    .Y(_166_)
  );
  NAND _347_ (
    .A(reset_s),
    .B(_166_),
    .Y(_167_)
  );
  NOR _348_ (
    .A(_165_),
    .B(_167_),
    .Y(_001_[0])
  );
  NOT _349_ (
    .A(clk_4f),
    .Y(_007_)
  );
  NOT _350_ (
    .A(clk_4f),
    .Y(_008_)
  );
  NOT _351_ (
    .A(clk_4f),
    .Y(_009_)
  );
  NOT _352_ (
    .A(clk_4f),
    .Y(_010_)
  );
  NOT _353_ (
    .A(clk_4f),
    .Y(_011_)
  );
  NOT _354_ (
    .A(clk_4f),
    .Y(_012_)
  );
  NOT _355_ (
    .A(clk_4f),
    .Y(_013_)
  );
  NOT _356_ (
    .A(clk_4f),
    .Y(_014_)
  );
  NOT _357_ (
    .A(clk_4f),
    .Y(_015_)
  );
  NOT _358_ (
    .A(clk_4f),
    .Y(_016_)
  );
  NOT _359_ (
    .A(clk_4f),
    .Y(_017_)
  );
  NOT _360_ (
    .A(clk_4f),
    .Y(_018_)
  );
  NOT _361_ (
    .A(clk_4f),
    .Y(_019_)
  );
  NOT _362_ (
    .A(clk_4f),
    .Y(_020_)
  );
  NOT _363_ (
    .A(clk_4f),
    .Y(_021_)
  );
  NOT _364_ (
    .A(clk_4f),
    .Y(_022_)
  );
  NOT _365_ (
    .A(clk_4f),
    .Y(_023_)
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _366_ (
    .C(clk_4f),
    .D(_001_[0]),
    .Q(data_rx11_synt[0])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _367_ (
    .C(clk_4f),
    .D(_001_[1]),
    .Q(data_rx11_synt[1])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _368_ (
    .C(clk_4f),
    .D(_001_[2]),
    .Q(data_rx11_synt[2])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _369_ (
    .C(clk_4f),
    .D(_001_[3]),
    .Q(data_rx11_synt[3])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _370_ (
    .C(clk_4f),
    .D(_001_[4]),
    .Q(data_rx11_synt[4])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _371_ (
    .C(clk_4f),
    .D(_001_[5]),
    .Q(data_rx11_synt[5])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _372_ (
    .C(clk_4f),
    .D(_001_[6]),
    .Q(data_rx11_synt[6])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _373_ (
    .C(clk_4f),
    .D(_001_[7]),
    .Q(data_rx11_synt[7])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _374_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(data_rx00_synt[0])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _375_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(data_rx00_synt[1])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _376_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(data_rx00_synt[2])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _377_ (
    .C(clk_4f),
    .D(_000_[3]),
    .Q(data_rx00_synt[3])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _378_ (
    .C(clk_4f),
    .D(_000_[4]),
    .Q(data_rx00_synt[4])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _379_ (
    .C(clk_4f),
    .D(_000_[5]),
    .Q(data_rx00_synt[5])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _380_ (
    .C(clk_4f),
    .D(_000_[6]),
    .Q(data_rx00_synt[6])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _381_ (
    .C(clk_4f),
    .D(_000_[7]),
    .Q(data_rx00_synt[7])
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _382_ (
    .C(clk_4f),
    .D(_004_),
    .Q(valid_rx00_synt)
  );
  (* src = "synth_demux1x2_8bits.v:43" *)
  DFF _383_ (
    .C(clk_4f),
    .D(_005_),
    .Q(valid_rx11_synt)
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _384_ (
    .C(_006_),
    .D(_002_[0]),
    .Q(paq_00[0])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _385_ (
    .C(_007_),
    .D(_002_[1]),
    .Q(paq_00[1])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _386_ (
    .C(_008_),
    .D(_002_[2]),
    .Q(paq_00[2])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _387_ (
    .C(_009_),
    .D(_002_[3]),
    .Q(paq_00[3])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _388_ (
    .C(_010_),
    .D(_002_[4]),
    .Q(paq_00[4])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _389_ (
    .C(_011_),
    .D(_002_[5]),
    .Q(paq_00[5])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _390_ (
    .C(_012_),
    .D(_002_[6]),
    .Q(paq_00[6])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _391_ (
    .C(_013_),
    .D(_002_[7]),
    .Q(paq_00[7])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _392_ (
    .C(_014_),
    .D(_002_[8]),
    .Q(paq_00[8])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _393_ (
    .C(_015_),
    .D(_003_[0]),
    .Q(paq_11[0])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _394_ (
    .C(_016_),
    .D(_003_[1]),
    .Q(paq_11[1])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _395_ (
    .C(_017_),
    .D(_003_[2]),
    .Q(paq_11[2])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _396_ (
    .C(_018_),
    .D(_003_[3]),
    .Q(paq_11[3])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _397_ (
    .C(_019_),
    .D(_003_[4]),
    .Q(paq_11[4])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _398_ (
    .C(_020_),
    .D(_003_[5]),
    .Q(paq_11[5])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _399_ (
    .C(_021_),
    .D(_003_[6]),
    .Q(paq_11[6])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _400_ (
    .C(_022_),
    .D(_003_[7]),
    .Q(paq_11[7])
  );
  (* src = "synth_demux1x2_8bits.v:27" *)
  DFF _401_ (
    .C(_023_),
    .D(_003_[8]),
    .Q(paq_11[8])
  );
  (* src = "synth_demux1x2_8bits.v:22" *)
  DFF _402_ (
    .C(clk_4f),
    .D(reset),
    .Q(reset_s)
  );
  (* src = "synth_demux1x2_8bits.v:22" *)
  DFF _403_ (
    .C(clk_4f),
    .D(clk_2f),
    .Q(clk_2f_s)
  );
endmodule

(* src = "synth_demux2x4_8bits.v:10" *)
module synth_demux2x4_8bits(data_rx0_synt, data_rx1_synt, data_rx2_synt, data_rx3_synt, valid_rx0_synt, valid_rx1_synt, valid_rx2_synt, valid_rx3_synt, data_rx00s_synt, data_rx11s_synt, valid_rx00s_synt, valid_rx11s_synt, clk_f, clk_2f, reset);
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire [7:0] _000_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire [7:0] _001_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire [7:0] _002_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire [7:0] _003_;
  (* src = "synth_demux2x4_8bits.v:30" *)
  wire [8:0] _004_;
  (* src = "synth_demux2x4_8bits.v:30" *)
  wire [8:0] _005_;
  (* src = "synth_demux2x4_8bits.v:30" *)
  wire [8:0] _006_;
  (* src = "synth_demux2x4_8bits.v:30" *)
  wire [8:0] _007_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire _008_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire _009_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire _010_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  (* src = "synth_demux2x4_8bits.v:16" *)
  input clk_2f;
  (* src = "synth_demux2x4_8bits.v:16" *)
  input clk_f;
  (* src = "synth_demux2x4_8bits.v:21" *)
  wire clk_f_s;
  (* src = "synth_demux2x4_8bits.v:10" *)
  output [7:0] data_rx0_synt;
  (* src = "synth_demux2x4_8bits.v:14" *)
  input [7:0] data_rx00s_synt;
  (* src = "synth_demux2x4_8bits.v:10" *)
  output [7:0] data_rx1_synt;
  (* src = "synth_demux2x4_8bits.v:14" *)
  input [7:0] data_rx11s_synt;
  (* src = "synth_demux2x4_8bits.v:11" *)
  output [7:0] data_rx2_synt;
  (* src = "synth_demux2x4_8bits.v:11" *)
  output [7:0] data_rx3_synt;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_0;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_1;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_2;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_3;
  (* src = "synth_demux2x4_8bits.v:16" *)
  input reset;
  (* src = "synth_demux2x4_8bits.v:19" *)
  wire reset_s;
  (* src = "synth_demux2x4_8bits.v:12" *)
  output valid_rx0_synt;
  (* src = "synth_demux2x4_8bits.v:15" *)
  input valid_rx00s_synt;
  (* src = "synth_demux2x4_8bits.v:12" *)
  output valid_rx1_synt;
  (* src = "synth_demux2x4_8bits.v:15" *)
  input valid_rx11s_synt;
  (* src = "synth_demux2x4_8bits.v:13" *)
  output valid_rx2_synt;
  (* src = "synth_demux2x4_8bits.v:13" *)
  output valid_rx3_synt;
  NOT _284_ (
    .A(clk_2f),
    .Y(_047_)
  );
  NOT _285_ (
    .A(reset_s),
    .Y(_048_)
  );
  NOT _286_ (
    .A(data_rx3_synt[0]),
    .Y(_049_)
  );
  NOT _287_ (
    .A(clk_f_s),
    .Y(_050_)
  );
  NOT _288_ (
    .A(data_rx3_synt[1]),
    .Y(_051_)
  );
  NOT _289_ (
    .A(data_rx3_synt[2]),
    .Y(_052_)
  );
  NOT _290_ (
    .A(data_rx3_synt[3]),
    .Y(_053_)
  );
  NOT _291_ (
    .A(data_rx3_synt[4]),
    .Y(_054_)
  );
  NOT _292_ (
    .A(data_rx3_synt[5]),
    .Y(_055_)
  );
  NOT _293_ (
    .A(data_rx3_synt[6]),
    .Y(_056_)
  );
  NOT _294_ (
    .A(data_rx3_synt[7]),
    .Y(_057_)
  );
  NOT _295_ (
    .A(paq_0[1]),
    .Y(_058_)
  );
  NOT _296_ (
    .A(paq_0[2]),
    .Y(_059_)
  );
  NOT _297_ (
    .A(paq_0[3]),
    .Y(_060_)
  );
  NOT _298_ (
    .A(paq_0[4]),
    .Y(_061_)
  );
  NOT _299_ (
    .A(paq_0[5]),
    .Y(_062_)
  );
  NOT _300_ (
    .A(paq_0[6]),
    .Y(_063_)
  );
  NOT _301_ (
    .A(paq_0[7]),
    .Y(_064_)
  );
  NOT _302_ (
    .A(paq_0[8]),
    .Y(_065_)
  );
  NOT _303_ (
    .A(paq_2[0]),
    .Y(_066_)
  );
  NOT _304_ (
    .A(valid_rx3_synt),
    .Y(_067_)
  );
  NOT _305_ (
    .A(paq_2[1]),
    .Y(_068_)
  );
  NOT _306_ (
    .A(paq_2[2]),
    .Y(_069_)
  );
  NOT _307_ (
    .A(paq_2[3]),
    .Y(_070_)
  );
  NOT _308_ (
    .A(paq_2[4]),
    .Y(_071_)
  );
  NOT _309_ (
    .A(paq_2[5]),
    .Y(_072_)
  );
  NOT _310_ (
    .A(paq_2[6]),
    .Y(_073_)
  );
  NOT _311_ (
    .A(paq_2[7]),
    .Y(_074_)
  );
  NOT _312_ (
    .A(paq_2[8]),
    .Y(_075_)
  );
  NOT _313_ (
    .A(data_rx1_synt[0]),
    .Y(_076_)
  );
  NOT _314_ (
    .A(data_rx1_synt[1]),
    .Y(_077_)
  );
  NOT _315_ (
    .A(data_rx1_synt[2]),
    .Y(_078_)
  );
  NOT _316_ (
    .A(data_rx1_synt[3]),
    .Y(_079_)
  );
  NOT _317_ (
    .A(data_rx1_synt[4]),
    .Y(_080_)
  );
  NOT _318_ (
    .A(data_rx1_synt[5]),
    .Y(_081_)
  );
  NOT _319_ (
    .A(data_rx1_synt[6]),
    .Y(_082_)
  );
  NOT _320_ (
    .A(data_rx1_synt[7]),
    .Y(_083_)
  );
  NOT _321_ (
    .A(valid_rx1_synt),
    .Y(_084_)
  );
  NOT _322_ (
    .A(paq_0[0]),
    .Y(_085_)
  );
  NOR _323_ (
    .A(clk_f_s),
    .B(paq_3[2]),
    .Y(_086_)
  );
  NAND _324_ (
    .A(clk_f_s),
    .B(_051_),
    .Y(_087_)
  );
  NAND _325_ (
    .A(reset_s),
    .B(_087_),
    .Y(_088_)
  );
  NOR _326_ (
    .A(_086_),
    .B(_088_),
    .Y(_003_[1])
  );
  NOR _327_ (
    .A(clk_f_s),
    .B(paq_3[3]),
    .Y(_089_)
  );
  NAND _328_ (
    .A(clk_f_s),
    .B(_052_),
    .Y(_090_)
  );
  NAND _329_ (
    .A(reset_s),
    .B(_090_),
    .Y(_091_)
  );
  NOR _330_ (
    .A(_089_),
    .B(_091_),
    .Y(_003_[2])
  );
  NOR _331_ (
    .A(clk_f_s),
    .B(paq_3[4]),
    .Y(_092_)
  );
  NAND _332_ (
    .A(clk_f_s),
    .B(_053_),
    .Y(_093_)
  );
  NAND _333_ (
    .A(reset_s),
    .B(_093_),
    .Y(_094_)
  );
  NOR _334_ (
    .A(_092_),
    .B(_094_),
    .Y(_003_[3])
  );
  NOR _335_ (
    .A(clk_f_s),
    .B(paq_3[5]),
    .Y(_095_)
  );
  NAND _336_ (
    .A(clk_f_s),
    .B(_054_),
    .Y(_096_)
  );
  NAND _337_ (
    .A(reset_s),
    .B(_096_),
    .Y(_097_)
  );
  NOR _338_ (
    .A(_095_),
    .B(_097_),
    .Y(_003_[4])
  );
  NOR _339_ (
    .A(clk_f_s),
    .B(paq_3[6]),
    .Y(_098_)
  );
  NAND _340_ (
    .A(clk_f_s),
    .B(_055_),
    .Y(_099_)
  );
  NAND _341_ (
    .A(reset_s),
    .B(_099_),
    .Y(_100_)
  );
  NOR _342_ (
    .A(_098_),
    .B(_100_),
    .Y(_003_[5])
  );
  NOR _343_ (
    .A(clk_f_s),
    .B(paq_3[7]),
    .Y(_101_)
  );
  NAND _344_ (
    .A(clk_f_s),
    .B(_056_),
    .Y(_102_)
  );
  NAND _345_ (
    .A(reset_s),
    .B(_102_),
    .Y(_103_)
  );
  NOR _346_ (
    .A(_101_),
    .B(_103_),
    .Y(_003_[6])
  );
  NOR _347_ (
    .A(clk_f_s),
    .B(paq_3[8]),
    .Y(_104_)
  );
  NAND _348_ (
    .A(clk_f_s),
    .B(_057_),
    .Y(_105_)
  );
  NAND _349_ (
    .A(reset_s),
    .B(_105_),
    .Y(_106_)
  );
  NOR _350_ (
    .A(_104_),
    .B(_106_),
    .Y(_003_[7])
  );
  NOR _351_ (
    .A(clk_f_s),
    .B(_058_),
    .Y(_107_)
  );
  NAND _352_ (
    .A(_050_),
    .B(paq_0[1]),
    .Y(_108_)
  );
  NAND _353_ (
    .A(clk_f_s),
    .B(data_rx0_synt[0]),
    .Y(_109_)
  );
  NOT _354_ (
    .A(_109_),
    .Y(_110_)
  );
  NOR _355_ (
    .A(_107_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _356_ (
    .A(_048_),
    .B(_111_),
    .Y(_000_[0])
  );
  NOR _357_ (
    .A(clk_f_s),
    .B(_059_),
    .Y(_112_)
  );
  NAND _358_ (
    .A(_050_),
    .B(paq_0[2]),
    .Y(_113_)
  );
  NAND _359_ (
    .A(clk_f_s),
    .B(data_rx0_synt[1]),
    .Y(_114_)
  );
  NOT _360_ (
    .A(_114_),
    .Y(_115_)
  );
  NOR _361_ (
    .A(_112_),
    .B(_115_),
    .Y(_116_)
  );
  NOR _362_ (
    .A(_048_),
    .B(_116_),
    .Y(_000_[1])
  );
  NOR _363_ (
    .A(clk_f_s),
    .B(_060_),
    .Y(_117_)
  );
  NAND _364_ (
    .A(_050_),
    .B(paq_0[3]),
    .Y(_118_)
  );
  NAND _365_ (
    .A(clk_f_s),
    .B(data_rx0_synt[2]),
    .Y(_119_)
  );
  NOT _366_ (
    .A(_119_),
    .Y(_120_)
  );
  NOR _367_ (
    .A(_117_),
    .B(_120_),
    .Y(_121_)
  );
  NOR _368_ (
    .A(_048_),
    .B(_121_),
    .Y(_000_[2])
  );
  NOR _369_ (
    .A(clk_f_s),
    .B(_061_),
    .Y(_122_)
  );
  NAND _370_ (
    .A(_050_),
    .B(paq_0[4]),
    .Y(_123_)
  );
  NAND _371_ (
    .A(clk_f_s),
    .B(data_rx0_synt[3]),
    .Y(_124_)
  );
  NOT _372_ (
    .A(_124_),
    .Y(_125_)
  );
  NOR _373_ (
    .A(_122_),
    .B(_125_),
    .Y(_126_)
  );
  NOR _374_ (
    .A(_048_),
    .B(_126_),
    .Y(_000_[3])
  );
  NOR _375_ (
    .A(clk_f_s),
    .B(_062_),
    .Y(_127_)
  );
  NAND _376_ (
    .A(_050_),
    .B(paq_0[5]),
    .Y(_128_)
  );
  NAND _377_ (
    .A(clk_f_s),
    .B(data_rx0_synt[4]),
    .Y(_129_)
  );
  NOT _378_ (
    .A(_129_),
    .Y(_130_)
  );
  NOR _379_ (
    .A(_127_),
    .B(_130_),
    .Y(_131_)
  );
  NOR _380_ (
    .A(_048_),
    .B(_131_),
    .Y(_000_[4])
  );
  NOR _381_ (
    .A(clk_f_s),
    .B(_063_),
    .Y(_132_)
  );
  NAND _382_ (
    .A(_050_),
    .B(paq_0[6]),
    .Y(_133_)
  );
  NAND _383_ (
    .A(clk_f_s),
    .B(data_rx0_synt[5]),
    .Y(_134_)
  );
  NOT _384_ (
    .A(_134_),
    .Y(_135_)
  );
  NOR _385_ (
    .A(_132_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _386_ (
    .A(_048_),
    .B(_136_),
    .Y(_000_[5])
  );
  NOR _387_ (
    .A(clk_f_s),
    .B(_064_),
    .Y(_137_)
  );
  NAND _388_ (
    .A(_050_),
    .B(paq_0[7]),
    .Y(_138_)
  );
  NAND _389_ (
    .A(clk_f_s),
    .B(data_rx0_synt[6]),
    .Y(_139_)
  );
  NOT _390_ (
    .A(_139_),
    .Y(_140_)
  );
  NOR _391_ (
    .A(_137_),
    .B(_140_),
    .Y(_141_)
  );
  NOR _392_ (
    .A(_048_),
    .B(_141_),
    .Y(_000_[6])
  );
  NOR _393_ (
    .A(clk_f_s),
    .B(_065_),
    .Y(_142_)
  );
  NAND _394_ (
    .A(_050_),
    .B(paq_0[8]),
    .Y(_143_)
  );
  NAND _395_ (
    .A(clk_f_s),
    .B(data_rx0_synt[7]),
    .Y(_144_)
  );
  NOT _396_ (
    .A(_144_),
    .Y(_145_)
  );
  NOR _397_ (
    .A(_142_),
    .B(_145_),
    .Y(_146_)
  );
  NOR _398_ (
    .A(_048_),
    .B(_146_),
    .Y(_000_[7])
  );
  NOR _399_ (
    .A(clk_f_s),
    .B(paq_3[0]),
    .Y(_147_)
  );
  NAND _400_ (
    .A(clk_f_s),
    .B(_067_),
    .Y(_148_)
  );
  NAND _401_ (
    .A(reset_s),
    .B(_148_),
    .Y(_149_)
  );
  NOR _402_ (
    .A(_147_),
    .B(_149_),
    .Y(_011_)
  );
  NOR _403_ (
    .A(clk_f_s),
    .B(_066_),
    .Y(_150_)
  );
  NAND _404_ (
    .A(_050_),
    .B(paq_2[0]),
    .Y(_151_)
  );
  NAND _405_ (
    .A(clk_f_s),
    .B(valid_rx2_synt),
    .Y(_152_)
  );
  NOT _406_ (
    .A(_152_),
    .Y(_153_)
  );
  NOR _407_ (
    .A(_150_),
    .B(_153_),
    .Y(_154_)
  );
  NOR _408_ (
    .A(_048_),
    .B(_154_),
    .Y(_010_)
  );
  NOR _409_ (
    .A(clk_f_s),
    .B(paq_1[1]),
    .Y(_155_)
  );
  NAND _410_ (
    .A(clk_f_s),
    .B(_076_),
    .Y(_156_)
  );
  NAND _411_ (
    .A(reset_s),
    .B(_156_),
    .Y(_157_)
  );
  NOR _412_ (
    .A(_155_),
    .B(_157_),
    .Y(_001_[0])
  );
  NOR _413_ (
    .A(clk_f_s),
    .B(paq_1[2]),
    .Y(_158_)
  );
  NAND _414_ (
    .A(clk_f_s),
    .B(_077_),
    .Y(_159_)
  );
  NAND _415_ (
    .A(reset_s),
    .B(_159_),
    .Y(_160_)
  );
  NOR _416_ (
    .A(_158_),
    .B(_160_),
    .Y(_001_[1])
  );
  NOR _417_ (
    .A(clk_f_s),
    .B(paq_1[3]),
    .Y(_161_)
  );
  NAND _418_ (
    .A(clk_f_s),
    .B(_078_),
    .Y(_162_)
  );
  NAND _419_ (
    .A(reset_s),
    .B(_162_),
    .Y(_163_)
  );
  NOR _420_ (
    .A(_161_),
    .B(_163_),
    .Y(_001_[2])
  );
  NOR _421_ (
    .A(clk_f_s),
    .B(paq_1[4]),
    .Y(_164_)
  );
  NAND _422_ (
    .A(clk_f_s),
    .B(_079_),
    .Y(_165_)
  );
  NAND _423_ (
    .A(reset_s),
    .B(_165_),
    .Y(_166_)
  );
  NOR _424_ (
    .A(_164_),
    .B(_166_),
    .Y(_001_[3])
  );
  NOR _425_ (
    .A(clk_f_s),
    .B(paq_1[5]),
    .Y(_167_)
  );
  NAND _426_ (
    .A(clk_f_s),
    .B(_080_),
    .Y(_168_)
  );
  NAND _427_ (
    .A(reset_s),
    .B(_168_),
    .Y(_169_)
  );
  NOR _428_ (
    .A(_167_),
    .B(_169_),
    .Y(_001_[4])
  );
  NOR _429_ (
    .A(clk_f_s),
    .B(paq_1[6]),
    .Y(_170_)
  );
  NAND _430_ (
    .A(clk_f_s),
    .B(_081_),
    .Y(_171_)
  );
  NAND _431_ (
    .A(reset_s),
    .B(_171_),
    .Y(_172_)
  );
  NOR _432_ (
    .A(_170_),
    .B(_172_),
    .Y(_001_[5])
  );
  NOR _433_ (
    .A(clk_f_s),
    .B(paq_1[7]),
    .Y(_173_)
  );
  NAND _434_ (
    .A(clk_f_s),
    .B(_082_),
    .Y(_174_)
  );
  NAND _435_ (
    .A(reset_s),
    .B(_174_),
    .Y(_175_)
  );
  NOR _436_ (
    .A(_173_),
    .B(_175_),
    .Y(_001_[6])
  );
  NOR _437_ (
    .A(clk_f_s),
    .B(paq_1[8]),
    .Y(_176_)
  );
  NAND _438_ (
    .A(clk_f_s),
    .B(_083_),
    .Y(_177_)
  );
  NAND _439_ (
    .A(reset_s),
    .B(_177_),
    .Y(_178_)
  );
  NOR _440_ (
    .A(_176_),
    .B(_178_),
    .Y(_001_[7])
  );
  NOR _441_ (
    .A(clk_f_s),
    .B(_068_),
    .Y(_179_)
  );
  NAND _442_ (
    .A(_050_),
    .B(paq_2[1]),
    .Y(_180_)
  );
  NAND _443_ (
    .A(clk_f_s),
    .B(data_rx2_synt[0]),
    .Y(_181_)
  );
  NOT _444_ (
    .A(_181_),
    .Y(_182_)
  );
  NOR _445_ (
    .A(_179_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _446_ (
    .A(_048_),
    .B(_183_),
    .Y(_002_[0])
  );
  NOR _447_ (
    .A(clk_f_s),
    .B(_069_),
    .Y(_184_)
  );
  NAND _448_ (
    .A(_050_),
    .B(paq_2[2]),
    .Y(_185_)
  );
  NAND _449_ (
    .A(clk_f_s),
    .B(data_rx2_synt[1]),
    .Y(_186_)
  );
  NOT _450_ (
    .A(_186_),
    .Y(_187_)
  );
  NOR _451_ (
    .A(_184_),
    .B(_187_),
    .Y(_188_)
  );
  NOR _452_ (
    .A(_048_),
    .B(_188_),
    .Y(_002_[1])
  );
  NOR _453_ (
    .A(clk_f_s),
    .B(_070_),
    .Y(_189_)
  );
  NAND _454_ (
    .A(_050_),
    .B(paq_2[3]),
    .Y(_190_)
  );
  NAND _455_ (
    .A(clk_f_s),
    .B(data_rx2_synt[2]),
    .Y(_191_)
  );
  NOT _456_ (
    .A(_191_),
    .Y(_192_)
  );
  NOR _457_ (
    .A(_189_),
    .B(_192_),
    .Y(_193_)
  );
  NOR _458_ (
    .A(_048_),
    .B(_193_),
    .Y(_002_[2])
  );
  NOR _459_ (
    .A(clk_f_s),
    .B(_071_),
    .Y(_194_)
  );
  NAND _460_ (
    .A(_050_),
    .B(paq_2[4]),
    .Y(_195_)
  );
  NAND _461_ (
    .A(clk_f_s),
    .B(data_rx2_synt[3]),
    .Y(_196_)
  );
  NOT _462_ (
    .A(_196_),
    .Y(_197_)
  );
  NOR _463_ (
    .A(_194_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _464_ (
    .A(_048_),
    .B(_198_),
    .Y(_002_[3])
  );
  NOR _465_ (
    .A(clk_f_s),
    .B(_072_),
    .Y(_199_)
  );
  NAND _466_ (
    .A(_050_),
    .B(paq_2[5]),
    .Y(_200_)
  );
  NAND _467_ (
    .A(clk_f_s),
    .B(data_rx2_synt[4]),
    .Y(_201_)
  );
  NOT _468_ (
    .A(_201_),
    .Y(_202_)
  );
  NOR _469_ (
    .A(_199_),
    .B(_202_),
    .Y(_203_)
  );
  NOR _470_ (
    .A(_048_),
    .B(_203_),
    .Y(_002_[4])
  );
  NOR _471_ (
    .A(clk_f_s),
    .B(_073_),
    .Y(_204_)
  );
  NAND _472_ (
    .A(_050_),
    .B(paq_2[6]),
    .Y(_205_)
  );
  NAND _473_ (
    .A(clk_f_s),
    .B(data_rx2_synt[5]),
    .Y(_206_)
  );
  NOT _474_ (
    .A(_206_),
    .Y(_207_)
  );
  NOR _475_ (
    .A(_204_),
    .B(_207_),
    .Y(_208_)
  );
  NOR _476_ (
    .A(_048_),
    .B(_208_),
    .Y(_002_[5])
  );
  NOR _477_ (
    .A(clk_f_s),
    .B(_074_),
    .Y(_209_)
  );
  NAND _478_ (
    .A(_050_),
    .B(paq_2[7]),
    .Y(_210_)
  );
  NAND _479_ (
    .A(clk_f_s),
    .B(data_rx2_synt[6]),
    .Y(_211_)
  );
  NOT _480_ (
    .A(_211_),
    .Y(_212_)
  );
  NOR _481_ (
    .A(_209_),
    .B(_212_),
    .Y(_213_)
  );
  NOR _482_ (
    .A(_048_),
    .B(_213_),
    .Y(_002_[6])
  );
  NOR _483_ (
    .A(clk_f_s),
    .B(_075_),
    .Y(_214_)
  );
  NAND _484_ (
    .A(_050_),
    .B(paq_2[8]),
    .Y(_215_)
  );
  NAND _485_ (
    .A(clk_f_s),
    .B(data_rx2_synt[7]),
    .Y(_216_)
  );
  NOT _486_ (
    .A(_216_),
    .Y(_217_)
  );
  NOR _487_ (
    .A(_214_),
    .B(_217_),
    .Y(_218_)
  );
  NOR _488_ (
    .A(_048_),
    .B(_218_),
    .Y(_002_[7])
  );
  NOR _489_ (
    .A(clk_f_s),
    .B(_085_),
    .Y(_219_)
  );
  NAND _490_ (
    .A(_050_),
    .B(paq_0[0]),
    .Y(_220_)
  );
  NAND _491_ (
    .A(clk_f_s),
    .B(valid_rx0_synt),
    .Y(_221_)
  );
  NOT _492_ (
    .A(_221_),
    .Y(_222_)
  );
  NOR _493_ (
    .A(_219_),
    .B(_222_),
    .Y(_223_)
  );
  NOR _494_ (
    .A(_048_),
    .B(_223_),
    .Y(_008_)
  );
  NOR _495_ (
    .A(clk_f_s),
    .B(paq_1[0]),
    .Y(_224_)
  );
  NAND _496_ (
    .A(clk_f_s),
    .B(_084_),
    .Y(_225_)
  );
  NAND _497_ (
    .A(reset_s),
    .B(_225_),
    .Y(_226_)
  );
  NOR _498_ (
    .A(_224_),
    .B(_226_),
    .Y(_009_)
  );
  NAND _499_ (
    .A(clk_f_s),
    .B(paq_1[0]),
    .Y(_227_)
  );
  NAND _500_ (
    .A(_050_),
    .B(valid_rx00s_synt),
    .Y(_228_)
  );
  NAND _501_ (
    .A(_227_),
    .B(_228_),
    .Y(_005_[0])
  );
  NAND _502_ (
    .A(clk_f_s),
    .B(paq_1[1]),
    .Y(_229_)
  );
  NAND _503_ (
    .A(_050_),
    .B(data_rx00s_synt[0]),
    .Y(_230_)
  );
  NAND _504_ (
    .A(_229_),
    .B(_230_),
    .Y(_005_[1])
  );
  NAND _505_ (
    .A(clk_f_s),
    .B(paq_1[2]),
    .Y(_231_)
  );
  NAND _506_ (
    .A(_050_),
    .B(data_rx00s_synt[1]),
    .Y(_232_)
  );
  NAND _507_ (
    .A(_231_),
    .B(_232_),
    .Y(_005_[2])
  );
  NAND _508_ (
    .A(clk_f_s),
    .B(paq_1[3]),
    .Y(_233_)
  );
  NAND _509_ (
    .A(_050_),
    .B(data_rx00s_synt[2]),
    .Y(_234_)
  );
  NAND _510_ (
    .A(_233_),
    .B(_234_),
    .Y(_005_[3])
  );
  NAND _511_ (
    .A(clk_f_s),
    .B(paq_1[4]),
    .Y(_235_)
  );
  NAND _512_ (
    .A(_050_),
    .B(data_rx00s_synt[3]),
    .Y(_236_)
  );
  NAND _513_ (
    .A(_235_),
    .B(_236_),
    .Y(_005_[4])
  );
  NAND _514_ (
    .A(clk_f_s),
    .B(paq_1[5]),
    .Y(_237_)
  );
  NAND _515_ (
    .A(_050_),
    .B(data_rx00s_synt[4]),
    .Y(_238_)
  );
  NAND _516_ (
    .A(_237_),
    .B(_238_),
    .Y(_005_[5])
  );
  NAND _517_ (
    .A(clk_f_s),
    .B(paq_1[6]),
    .Y(_239_)
  );
  NAND _518_ (
    .A(_050_),
    .B(data_rx00s_synt[5]),
    .Y(_240_)
  );
  NAND _519_ (
    .A(_239_),
    .B(_240_),
    .Y(_005_[6])
  );
  NAND _520_ (
    .A(clk_f_s),
    .B(paq_1[7]),
    .Y(_241_)
  );
  NAND _521_ (
    .A(_050_),
    .B(data_rx00s_synt[6]),
    .Y(_242_)
  );
  NAND _522_ (
    .A(_241_),
    .B(_242_),
    .Y(_005_[7])
  );
  NAND _523_ (
    .A(clk_f_s),
    .B(paq_1[8]),
    .Y(_243_)
  );
  NAND _524_ (
    .A(_050_),
    .B(data_rx00s_synt[7]),
    .Y(_244_)
  );
  NAND _525_ (
    .A(_243_),
    .B(_244_),
    .Y(_005_[8])
  );
  NAND _526_ (
    .A(clk_f_s),
    .B(paq_3[0]),
    .Y(_245_)
  );
  NAND _527_ (
    .A(_050_),
    .B(valid_rx11s_synt),
    .Y(_246_)
  );
  NAND _528_ (
    .A(_245_),
    .B(_246_),
    .Y(_007_[0])
  );
  NAND _529_ (
    .A(paq_3[1]),
    .B(clk_f_s),
    .Y(_247_)
  );
  NAND _530_ (
    .A(_050_),
    .B(data_rx11s_synt[0]),
    .Y(_248_)
  );
  NAND _531_ (
    .A(_247_),
    .B(_248_),
    .Y(_007_[1])
  );
  NAND _532_ (
    .A(clk_f_s),
    .B(paq_3[2]),
    .Y(_249_)
  );
  NAND _533_ (
    .A(_050_),
    .B(data_rx11s_synt[1]),
    .Y(_250_)
  );
  NAND _534_ (
    .A(_249_),
    .B(_250_),
    .Y(_007_[2])
  );
  NAND _535_ (
    .A(clk_f_s),
    .B(paq_3[3]),
    .Y(_251_)
  );
  NAND _536_ (
    .A(_050_),
    .B(data_rx11s_synt[2]),
    .Y(_252_)
  );
  NAND _537_ (
    .A(_251_),
    .B(_252_),
    .Y(_007_[3])
  );
  NAND _538_ (
    .A(clk_f_s),
    .B(paq_3[4]),
    .Y(_253_)
  );
  NAND _539_ (
    .A(_050_),
    .B(data_rx11s_synt[3]),
    .Y(_254_)
  );
  NAND _540_ (
    .A(_253_),
    .B(_254_),
    .Y(_007_[4])
  );
  NAND _541_ (
    .A(clk_f_s),
    .B(paq_3[5]),
    .Y(_255_)
  );
  NAND _542_ (
    .A(_050_),
    .B(data_rx11s_synt[4]),
    .Y(_256_)
  );
  NAND _543_ (
    .A(_255_),
    .B(_256_),
    .Y(_007_[5])
  );
  NAND _544_ (
    .A(clk_f_s),
    .B(paq_3[6]),
    .Y(_257_)
  );
  NAND _545_ (
    .A(_050_),
    .B(data_rx11s_synt[5]),
    .Y(_258_)
  );
  NAND _546_ (
    .A(_257_),
    .B(_258_),
    .Y(_007_[6])
  );
  NAND _547_ (
    .A(clk_f_s),
    .B(paq_3[7]),
    .Y(_259_)
  );
  NAND _548_ (
    .A(_050_),
    .B(data_rx11s_synt[6]),
    .Y(_260_)
  );
  NAND _549_ (
    .A(_259_),
    .B(_260_),
    .Y(_007_[7])
  );
  NAND _550_ (
    .A(clk_f_s),
    .B(paq_3[8]),
    .Y(_261_)
  );
  NAND _551_ (
    .A(_050_),
    .B(data_rx11s_synt[7]),
    .Y(_262_)
  );
  NAND _552_ (
    .A(_261_),
    .B(_262_),
    .Y(_007_[8])
  );
  NAND _553_ (
    .A(clk_f_s),
    .B(valid_rx11s_synt),
    .Y(_263_)
  );
  NAND _554_ (
    .A(_151_),
    .B(_263_),
    .Y(_006_[0])
  );
  NAND _555_ (
    .A(clk_f_s),
    .B(data_rx11s_synt[0]),
    .Y(_264_)
  );
  NAND _556_ (
    .A(_180_),
    .B(_264_),
    .Y(_006_[1])
  );
  NAND _557_ (
    .A(clk_f_s),
    .B(data_rx11s_synt[1]),
    .Y(_265_)
  );
  NAND _558_ (
    .A(_185_),
    .B(_265_),
    .Y(_006_[2])
  );
  NAND _559_ (
    .A(clk_f_s),
    .B(data_rx11s_synt[2]),
    .Y(_266_)
  );
  NAND _560_ (
    .A(_190_),
    .B(_266_),
    .Y(_006_[3])
  );
  NAND _561_ (
    .A(clk_f_s),
    .B(data_rx11s_synt[3]),
    .Y(_267_)
  );
  NAND _562_ (
    .A(_195_),
    .B(_267_),
    .Y(_006_[4])
  );
  NAND _563_ (
    .A(clk_f_s),
    .B(data_rx11s_synt[4]),
    .Y(_268_)
  );
  NAND _564_ (
    .A(_200_),
    .B(_268_),
    .Y(_006_[5])
  );
  NAND _565_ (
    .A(clk_f_s),
    .B(data_rx11s_synt[5]),
    .Y(_269_)
  );
  NAND _566_ (
    .A(_205_),
    .B(_269_),
    .Y(_006_[6])
  );
  NAND _567_ (
    .A(clk_f_s),
    .B(data_rx11s_synt[6]),
    .Y(_270_)
  );
  NAND _568_ (
    .A(_210_),
    .B(_270_),
    .Y(_006_[7])
  );
  NAND _569_ (
    .A(clk_f_s),
    .B(data_rx11s_synt[7]),
    .Y(_271_)
  );
  NAND _570_ (
    .A(_215_),
    .B(_271_),
    .Y(_006_[8])
  );
  NAND _571_ (
    .A(clk_f_s),
    .B(valid_rx00s_synt),
    .Y(_272_)
  );
  NAND _572_ (
    .A(_220_),
    .B(_272_),
    .Y(_004_[0])
  );
  NAND _573_ (
    .A(clk_f_s),
    .B(data_rx00s_synt[0]),
    .Y(_273_)
  );
  NAND _574_ (
    .A(_108_),
    .B(_273_),
    .Y(_004_[1])
  );
  NAND _575_ (
    .A(clk_f_s),
    .B(data_rx00s_synt[1]),
    .Y(_274_)
  );
  NAND _576_ (
    .A(_113_),
    .B(_274_),
    .Y(_004_[2])
  );
  NAND _577_ (
    .A(clk_f_s),
    .B(data_rx00s_synt[2]),
    .Y(_275_)
  );
  NAND _578_ (
    .A(_118_),
    .B(_275_),
    .Y(_004_[3])
  );
  NAND _579_ (
    .A(clk_f_s),
    .B(data_rx00s_synt[3]),
    .Y(_276_)
  );
  NAND _580_ (
    .A(_123_),
    .B(_276_),
    .Y(_004_[4])
  );
  NAND _581_ (
    .A(clk_f_s),
    .B(data_rx00s_synt[4]),
    .Y(_277_)
  );
  NAND _582_ (
    .A(_128_),
    .B(_277_),
    .Y(_004_[5])
  );
  NAND _583_ (
    .A(clk_f_s),
    .B(data_rx00s_synt[5]),
    .Y(_278_)
  );
  NAND _584_ (
    .A(_133_),
    .B(_278_),
    .Y(_004_[6])
  );
  NAND _585_ (
    .A(clk_f_s),
    .B(data_rx00s_synt[6]),
    .Y(_279_)
  );
  NAND _586_ (
    .A(_138_),
    .B(_279_),
    .Y(_004_[7])
  );
  NAND _587_ (
    .A(clk_f_s),
    .B(data_rx00s_synt[7]),
    .Y(_280_)
  );
  NAND _588_ (
    .A(_143_),
    .B(_280_),
    .Y(_004_[8])
  );
  NOR _589_ (
    .A(paq_3[1]),
    .B(clk_f_s),
    .Y(_281_)
  );
  NAND _590_ (
    .A(_049_),
    .B(clk_f_s),
    .Y(_282_)
  );
  NAND _591_ (
    .A(reset_s),
    .B(_282_),
    .Y(_283_)
  );
  NOR _592_ (
    .A(_281_),
    .B(_283_),
    .Y(_003_[0])
  );
  NOT _593_ (
    .A(clk_2f),
    .Y(_012_)
  );
  NOT _594_ (
    .A(clk_2f),
    .Y(_013_)
  );
  NOT _595_ (
    .A(clk_2f),
    .Y(_014_)
  );
  NOT _596_ (
    .A(clk_2f),
    .Y(_015_)
  );
  NOT _597_ (
    .A(clk_2f),
    .Y(_016_)
  );
  NOT _598_ (
    .A(clk_2f),
    .Y(_017_)
  );
  NOT _599_ (
    .A(clk_2f),
    .Y(_018_)
  );
  NOT _600_ (
    .A(clk_2f),
    .Y(_019_)
  );
  NOT _601_ (
    .A(clk_2f),
    .Y(_020_)
  );
  NOT _602_ (
    .A(clk_2f),
    .Y(_021_)
  );
  NOT _603_ (
    .A(clk_2f),
    .Y(_022_)
  );
  NOT _604_ (
    .A(clk_2f),
    .Y(_023_)
  );
  NOT _605_ (
    .A(clk_2f),
    .Y(_024_)
  );
  NOT _606_ (
    .A(clk_2f),
    .Y(_025_)
  );
  NOT _607_ (
    .A(clk_2f),
    .Y(_026_)
  );
  NOT _608_ (
    .A(clk_2f),
    .Y(_027_)
  );
  NOT _609_ (
    .A(clk_2f),
    .Y(_028_)
  );
  NOT _610_ (
    .A(clk_2f),
    .Y(_029_)
  );
  NOT _611_ (
    .A(clk_2f),
    .Y(_030_)
  );
  NOT _612_ (
    .A(clk_2f),
    .Y(_031_)
  );
  NOT _613_ (
    .A(clk_2f),
    .Y(_032_)
  );
  NOT _614_ (
    .A(clk_2f),
    .Y(_033_)
  );
  NOT _615_ (
    .A(clk_2f),
    .Y(_034_)
  );
  NOT _616_ (
    .A(clk_2f),
    .Y(_035_)
  );
  NOT _617_ (
    .A(clk_2f),
    .Y(_036_)
  );
  NOT _618_ (
    .A(clk_2f),
    .Y(_037_)
  );
  NOT _619_ (
    .A(clk_2f),
    .Y(_038_)
  );
  NOT _620_ (
    .A(clk_2f),
    .Y(_039_)
  );
  NOT _621_ (
    .A(clk_2f),
    .Y(_040_)
  );
  NOT _622_ (
    .A(clk_2f),
    .Y(_041_)
  );
  NOT _623_ (
    .A(clk_2f),
    .Y(_042_)
  );
  NOT _624_ (
    .A(clk_2f),
    .Y(_043_)
  );
  NOT _625_ (
    .A(clk_2f),
    .Y(_044_)
  );
  NOT _626_ (
    .A(clk_2f),
    .Y(_045_)
  );
  NOT _627_ (
    .A(clk_2f),
    .Y(_046_)
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _628_ (
    .C(_012_),
    .D(_007_[8]),
    .Q(paq_3[8])
  );
  (* src = "synth_demux2x4_8bits.v:24" *)
  DFF _629_ (
    .C(clk_2f),
    .D(reset),
    .Q(reset_s)
  );
  (* src = "synth_demux2x4_8bits.v:24" *)
  DFF _630_ (
    .C(clk_2f),
    .D(clk_f),
    .Q(clk_f_s)
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _631_ (
    .C(clk_2f),
    .D(_010_),
    .Q(valid_rx2_synt)
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _632_ (
    .C(clk_2f),
    .D(_009_),
    .Q(valid_rx1_synt)
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _633_ (
    .C(clk_2f),
    .D(_008_),
    .Q(valid_rx0_synt)
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _634_ (
    .C(clk_2f),
    .D(_002_[0]),
    .Q(data_rx2_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _635_ (
    .C(clk_2f),
    .D(_002_[1]),
    .Q(data_rx2_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _636_ (
    .C(clk_2f),
    .D(_002_[2]),
    .Q(data_rx2_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _637_ (
    .C(clk_2f),
    .D(_002_[3]),
    .Q(data_rx2_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _638_ (
    .C(clk_2f),
    .D(_002_[4]),
    .Q(data_rx2_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _639_ (
    .C(clk_2f),
    .D(_002_[5]),
    .Q(data_rx2_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _640_ (
    .C(clk_2f),
    .D(_002_[6]),
    .Q(data_rx2_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _641_ (
    .C(clk_2f),
    .D(_002_[7]),
    .Q(data_rx2_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _642_ (
    .C(clk_2f),
    .D(_011_),
    .Q(valid_rx3_synt)
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _643_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_rx0_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _644_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_rx0_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _645_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_rx0_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _646_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_rx0_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _647_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_rx0_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _648_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_rx0_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _649_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_rx0_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _650_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_rx0_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _651_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(data_rx1_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _652_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(data_rx1_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _653_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(data_rx1_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _654_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(data_rx1_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _655_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(data_rx1_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _656_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(data_rx1_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _657_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(data_rx1_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _658_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(data_rx1_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _659_ (
    .C(clk_2f),
    .D(_003_[0]),
    .Q(data_rx3_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _660_ (
    .C(clk_2f),
    .D(_003_[1]),
    .Q(data_rx3_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _661_ (
    .C(clk_2f),
    .D(_003_[2]),
    .Q(data_rx3_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _662_ (
    .C(clk_2f),
    .D(_003_[3]),
    .Q(data_rx3_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _663_ (
    .C(clk_2f),
    .D(_003_[4]),
    .Q(data_rx3_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _664_ (
    .C(clk_2f),
    .D(_003_[5]),
    .Q(data_rx3_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _665_ (
    .C(clk_2f),
    .D(_003_[6]),
    .Q(data_rx3_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _666_ (
    .C(clk_2f),
    .D(_003_[7]),
    .Q(data_rx3_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _667_ (
    .C(_013_),
    .D(_004_[0]),
    .Q(paq_0[0])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _668_ (
    .C(_014_),
    .D(_004_[1]),
    .Q(paq_0[1])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _669_ (
    .C(_015_),
    .D(_004_[2]),
    .Q(paq_0[2])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _670_ (
    .C(_016_),
    .D(_004_[3]),
    .Q(paq_0[3])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _671_ (
    .C(_017_),
    .D(_004_[4]),
    .Q(paq_0[4])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _672_ (
    .C(_018_),
    .D(_004_[5]),
    .Q(paq_0[5])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _673_ (
    .C(_019_),
    .D(_004_[6]),
    .Q(paq_0[6])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _674_ (
    .C(_020_),
    .D(_004_[7]),
    .Q(paq_0[7])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _675_ (
    .C(_021_),
    .D(_004_[8]),
    .Q(paq_0[8])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _676_ (
    .C(_022_),
    .D(_005_[0]),
    .Q(paq_1[0])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _677_ (
    .C(_023_),
    .D(_005_[1]),
    .Q(paq_1[1])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _678_ (
    .C(_024_),
    .D(_005_[2]),
    .Q(paq_1[2])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _679_ (
    .C(_025_),
    .D(_005_[3]),
    .Q(paq_1[3])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _680_ (
    .C(_026_),
    .D(_005_[4]),
    .Q(paq_1[4])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _681_ (
    .C(_027_),
    .D(_005_[5]),
    .Q(paq_1[5])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _682_ (
    .C(_028_),
    .D(_005_[6]),
    .Q(paq_1[6])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _683_ (
    .C(_029_),
    .D(_005_[7]),
    .Q(paq_1[7])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _684_ (
    .C(_030_),
    .D(_005_[8]),
    .Q(paq_1[8])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _685_ (
    .C(_031_),
    .D(_006_[0]),
    .Q(paq_2[0])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _686_ (
    .C(_032_),
    .D(_006_[1]),
    .Q(paq_2[1])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _687_ (
    .C(_033_),
    .D(_006_[2]),
    .Q(paq_2[2])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _688_ (
    .C(_034_),
    .D(_006_[3]),
    .Q(paq_2[3])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _689_ (
    .C(_035_),
    .D(_006_[4]),
    .Q(paq_2[4])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _690_ (
    .C(_036_),
    .D(_006_[5]),
    .Q(paq_2[5])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _691_ (
    .C(_037_),
    .D(_006_[6]),
    .Q(paq_2[6])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _692_ (
    .C(_038_),
    .D(_006_[7]),
    .Q(paq_2[7])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _693_ (
    .C(_039_),
    .D(_006_[8]),
    .Q(paq_2[8])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _694_ (
    .C(_040_),
    .D(_007_[0]),
    .Q(paq_3[0])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _695_ (
    .C(_041_),
    .D(_007_[1]),
    .Q(paq_3[1])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _696_ (
    .C(_042_),
    .D(_007_[2]),
    .Q(paq_3[2])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _697_ (
    .C(_043_),
    .D(_007_[3]),
    .Q(paq_3[3])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _698_ (
    .C(_044_),
    .D(_007_[4]),
    .Q(paq_3[4])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _699_ (
    .C(_045_),
    .D(_007_[5]),
    .Q(paq_3[5])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _700_ (
    .C(_046_),
    .D(_007_[6]),
    .Q(paq_3[6])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _701_ (
    .C(_047_),
    .D(_007_[7]),
    .Q(paq_3[7])
  );
endmodule

(* src = "synth_etapaflops3.v:1" *)
module synth_etapaflops3(data_rx00s_synt, data_rx11s_synt, valid_rx00s_synt, valid_rx11s_synt, data_rx00_synt, data_rx11_synt, valid_rx00_synt, valid_rx11_synt, clk_2f);
  (* src = "synth_etapaflops3.v:5" *)
  input clk_2f;
  (* src = "synth_etapaflops3.v:3" *)
  input [7:0] data_rx00_synt;
  (* src = "synth_etapaflops3.v:1" *)
  output [7:0] data_rx00s_synt;
  (* src = "synth_etapaflops3.v:3" *)
  input [7:0] data_rx11_synt;
  (* src = "synth_etapaflops3.v:1" *)
  output [7:0] data_rx11s_synt;
  (* src = "synth_etapaflops3.v:4" *)
  input valid_rx00_synt;
  (* src = "synth_etapaflops3.v:2" *)
  output valid_rx00s_synt;
  (* src = "synth_etapaflops3.v:4" *)
  input valid_rx11_synt;
  (* src = "synth_etapaflops3.v:2" *)
  output valid_rx11s_synt;
  (* src = "synth_etapaflops3.v:7" *)
  DFF _00_ (
    .C(clk_2f),
    .D(data_rx00_synt[0]),
    .Q(data_rx00s_synt[0])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _01_ (
    .C(clk_2f),
    .D(data_rx00_synt[1]),
    .Q(data_rx00s_synt[1])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _02_ (
    .C(clk_2f),
    .D(data_rx00_synt[2]),
    .Q(data_rx00s_synt[2])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _03_ (
    .C(clk_2f),
    .D(data_rx00_synt[3]),
    .Q(data_rx00s_synt[3])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _04_ (
    .C(clk_2f),
    .D(data_rx00_synt[4]),
    .Q(data_rx00s_synt[4])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _05_ (
    .C(clk_2f),
    .D(data_rx00_synt[5]),
    .Q(data_rx00s_synt[5])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _06_ (
    .C(clk_2f),
    .D(data_rx00_synt[6]),
    .Q(data_rx00s_synt[6])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _07_ (
    .C(clk_2f),
    .D(data_rx00_synt[7]),
    .Q(data_rx00s_synt[7])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _08_ (
    .C(clk_2f),
    .D(data_rx11_synt[0]),
    .Q(data_rx11s_synt[0])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _09_ (
    .C(clk_2f),
    .D(data_rx11_synt[1]),
    .Q(data_rx11s_synt[1])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _10_ (
    .C(clk_2f),
    .D(data_rx11_synt[2]),
    .Q(data_rx11s_synt[2])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _11_ (
    .C(clk_2f),
    .D(data_rx11_synt[3]),
    .Q(data_rx11s_synt[3])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _12_ (
    .C(clk_2f),
    .D(data_rx11_synt[4]),
    .Q(data_rx11s_synt[4])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _13_ (
    .C(clk_2f),
    .D(data_rx11_synt[5]),
    .Q(data_rx11s_synt[5])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _14_ (
    .C(clk_2f),
    .D(data_rx11_synt[6]),
    .Q(data_rx11s_synt[6])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _15_ (
    .C(clk_2f),
    .D(data_rx11_synt[7]),
    .Q(data_rx11s_synt[7])
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _16_ (
    .C(clk_2f),
    .D(valid_rx00_synt),
    .Q(valid_rx00s_synt)
  );
  (* src = "synth_etapaflops3.v:7" *)
  DFF _17_ (
    .C(clk_2f),
    .D(valid_rx11_synt),
    .Q(valid_rx11s_synt)
  );
endmodule

(* src = "synth_paralelo_serial2.v:1" *)
module synth_paralelo_serial2(inserter_synt, clk_4f, clk_32f, reset, active_synt);
  (* src = "synth_paralelo_serial2.v:30" *)
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  (* src = "synth_paralelo_serial2.v:5" *)
  (* unused_bits = "6 7" *)
  wire [7:0] IDLE_COM;
  (* src = "synth_paralelo_serial2.v:3" *)
  input active_synt;
  (* src = "synth_paralelo_serial2.v:2" *)
  input clk_32f;
  (* src = "synth_paralelo_serial2.v:2" *)
  input clk_4f;
  (* src = "synth_paralelo_serial2.v:6" *)
  wire [2:0] counter;
  (* src = "synth_paralelo_serial2.v:1" *)
  output inserter_synt;
  (* src = "synth_paralelo_serial2.v:3" *)
  input reset;
  (* src = "synth_paralelo_serial2.v:7" *)
  wire reset_s;
  NOT _20_ (
    .A(reset_s),
    .Y(_01_)
  );
  NOT _21_ (
    .A(counter[2]),
    .Y(_02_)
  );
  NAND _22_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_03_)
  );
  NOT _23_ (
    .A(_03_),
    .Y(_04_)
  );
  NOR _24_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_05_)
  );
  NOT _25_ (
    .A(_05_),
    .Y(_06_)
  );
  NAND _26_ (
    .A(reset_s),
    .B(_06_),
    .Y(_07_)
  );
  NOR _27_ (
    .A(_04_),
    .B(_07_),
    .Y(_00_[1])
  );
  NAND _28_ (
    .A(_02_),
    .B(_03_),
    .Y(_08_)
  );
  NAND _29_ (
    .A(reset_s),
    .B(_08_),
    .Y(_09_)
  );
  NAND _30_ (
    .A(counter[2]),
    .B(counter[1]),
    .Y(_10_)
  );
  NOR _31_ (
    .A(_02_),
    .B(_03_),
    .Y(_11_)
  );
  NOR _32_ (
    .A(_09_),
    .B(_11_),
    .Y(_00_[2])
  );
  NAND _33_ (
    .A(active_synt),
    .B(counter[0]),
    .Y(_12_)
  );
  NOT _34_ (
    .A(_12_),
    .Y(_13_)
  );
  NOR _35_ (
    .A(active_synt),
    .B(counter[0]),
    .Y(_14_)
  );
  NOR _36_ (
    .A(_13_),
    .B(_14_),
    .Y(_15_)
  );
  NOR _37_ (
    .A(_10_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _38_ (
    .A(counter[2]),
    .B(counter[1]),
    .Y(_17_)
  );
  NOT _39_ (
    .A(_17_),
    .Y(_18_)
  );
  NAND _40_ (
    .A(reset_s),
    .B(_18_),
    .Y(_19_)
  );
  NOR _41_ (
    .A(_16_),
    .B(_19_),
    .Y(inserter_synt)
  );
  NOR _42_ (
    .A(_01_),
    .B(counter[0]),
    .Y(_00_[0])
  );
  (* src = "synth_paralelo_serial2.v:30" *)
  DFF _43_ (
    .C(clk_32f),
    .D(_00_[0]),
    .Q(counter[0])
  );
  (* src = "synth_paralelo_serial2.v:30" *)
  DFF _44_ (
    .C(clk_32f),
    .D(_00_[1]),
    .Q(counter[1])
  );
  (* src = "synth_paralelo_serial2.v:30" *)
  DFF _45_ (
    .C(clk_32f),
    .D(_00_[2]),
    .Q(counter[2])
  );
  (* src = "synth_paralelo_serial2.v:26" *)
  DFF _46_ (
    .C(clk_4f),
    .D(reset),
    .Q(reset_s)
  );
  assign IDLE_COM[5:0] = { reset_s, reset_s, reset_s, reset_s, 2'h0 };
endmodule

(* top =  1  *)
(* src = "synth_phy_rx.v:7" *)
module synth_phy_rx(data_rx0_synt, data_rx1_synt, data_rx2_synt, data_rx3_synt, valid_rx0_synt, valid_rx1_synt, valid_rx2_synt, valid_rx3_synt, inserter_synt, data_out, reset, clk_f, clk_2f, clk_4f, clk_32f);
  (* src = "synth_phy_rx.v:17" *)
  wire active_synt;
  (* src = "synth_phy_rx.v:13" *)
  input clk_2f;
  (* src = "synth_phy_rx.v:13" *)
  input clk_32f;
  (* src = "synth_phy_rx.v:13" *)
  input clk_4f;
  (* src = "synth_phy_rx.v:13" *)
  input clk_f;
  (* src = "synth_phy_rx.v:12" *)
  input data_out;
  (* src = "synth_phy_rx.v:7" *)
  output [7:0] data_rx0_synt;
  (* src = "synth_phy_rx.v:18" *)
  wire [7:0] data_rx00_synt;
  (* src = "synth_phy_rx.v:19" *)
  wire [7:0] data_rx000_synt;
  (* src = "synth_phy_rx.v:20" *)
  wire [7:0] data_rx00s_synt;
  (* src = "synth_phy_rx.v:7" *)
  output [7:0] data_rx1_synt;
  (* src = "synth_phy_rx.v:21" *)
  wire [7:0] data_rx11_synt;
  (* src = "synth_phy_rx.v:22" *)
  wire [7:0] data_rx11s_synt;
  (* src = "synth_phy_rx.v:8" *)
  output [7:0] data_rx2_synt;
  (* src = "synth_phy_rx.v:8" *)
  output [7:0] data_rx3_synt;
  (* src = "synth_phy_rx.v:11" *)
  output inserter_synt;
  (* src = "synth_phy_rx.v:12" *)
  input reset;
  (* src = "synth_phy_rx.v:9" *)
  output valid_rx0_synt;
  (* src = "synth_phy_rx.v:23" *)
  wire valid_rx00_synt;
  (* src = "synth_phy_rx.v:24" *)
  wire valid_rx000_synt;
  (* src = "synth_phy_rx.v:25" *)
  wire valid_rx00s_synt;
  (* src = "synth_phy_rx.v:9" *)
  output valid_rx1_synt;
  (* src = "synth_phy_rx.v:26" *)
  wire valid_rx11_synt;
  (* src = "synth_phy_rx.v:27" *)
  wire valid_rx11s_synt;
  (* src = "synth_phy_rx.v:10" *)
  output valid_rx2_synt;
  (* src = "synth_phy_rx.v:10" *)
  output valid_rx3_synt;
  (* module_not_derived = 32'd1 *)
  (* src = "synth_phy_rx.v:60" *)
  synth_demux2x4_8bits DEMUXL1 (
    .clk_2f(clk_2f),
    .clk_f(clk_f),
    .data_rx0_synt(data_rx0_synt),
    .data_rx00s_synt(data_rx00s_synt),
    .data_rx1_synt(data_rx1_synt),
    .data_rx11s_synt(data_rx11s_synt),
    .data_rx2_synt(data_rx2_synt),
    .data_rx3_synt(data_rx3_synt),
    .reset(reset),
    .valid_rx0_synt(valid_rx0_synt),
    .valid_rx00s_synt(valid_rx00s_synt),
    .valid_rx1_synt(valid_rx1_synt),
    .valid_rx11s_synt(valid_rx11s_synt),
    .valid_rx2_synt(valid_rx2_synt),
    .valid_rx3_synt(valid_rx3_synt)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synth_phy_rx.v:48" *)
  synth_demux1x2_8bits DEMUXL2 (
    .clk_2f(clk_2f),
    .clk_4f(clk_4f),
    .data_rx00_synt(data_rx00_synt),
    .data_rx000_synt(data_rx000_synt),
    .data_rx11_synt(data_rx11_synt),
    .reset(reset),
    .valid_rx00_synt(valid_rx00_synt),
    .valid_rx000_synt(valid_rx000_synt),
    .valid_rx11_synt(valid_rx11_synt)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synth_phy_rx.v:78" *)
  synth_etapaflops3 FLOPS3 (
    .clk_2f(clk_2f),
    .data_rx00_synt(data_rx00_synt),
    .data_rx00s_synt(data_rx00s_synt),
    .data_rx11_synt(data_rx11_synt),
    .data_rx11s_synt(data_rx11s_synt),
    .valid_rx00_synt(valid_rx00_synt),
    .valid_rx00s_synt(valid_rx00s_synt),
    .valid_rx11_synt(valid_rx11_synt),
    .valid_rx11s_synt(valid_rx11s_synt)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synth_phy_rx.v:40" *)
  synth_paralelo_serial2 PARSER2 (
    .active_synt(active_synt),
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .inserter_synt(inserter_synt),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synth_phy_rx.v:30" *)
  synth_serial_paralelo1 SERPAR1 (
    .active_synt(active_synt),
    .clk_32f(clk_32f),
    .clk_4f(clk_4f),
    .data_out(data_out),
    .data_rx000_synt(data_rx000_synt),
    .reset(reset),
    .valid_rx000_synt(valid_rx000_synt)
  );
endmodule

(* src = "synth_serial_paralelo1.v:1" *)
module synth_serial_paralelo1(data_rx000_synt, valid_rx000_synt, active_synt, data_out, reset, clk_4f, clk_32f);
  (* src = "synth_serial_paralelo1.v:40" *)
  wire [2:0] _000_;
  (* src = "synth_serial_paralelo1.v:30" *)
  wire [7:0] _001_;
  (* src = "synth_serial_paralelo1.v:19" *)
  wire [2:0] _002_;
  (* src = "synth_serial_paralelo1.v:65" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  (* src = "synth_serial_paralelo1.v:9" *)
  wire [2:0] BC_counter;
  (* src = "synth_serial_paralelo1.v:2" *)
  output active_synt;
  (* src = "synth_serial_paralelo1.v:4" *)
  input clk_32f;
  (* src = "synth_serial_paralelo1.v:4" *)
  input clk_4f;
  (* src = "synth_serial_paralelo1.v:8" *)
  wire [7:0] container;
  (* src = "synth_serial_paralelo1.v:7" *)
  wire [2:0] counter;
  (* src = "synth_serial_paralelo1.v:3" *)
  input data_out;
  (* src = "synth_serial_paralelo1.v:1" *)
  output [7:0] data_rx000_synt;
  (* src = "synth_serial_paralelo1.v:3" *)
  input reset;
  (* src = "synth_serial_paralelo1.v:6" *)
  wire reset_s;
  (* src = "synth_serial_paralelo1.v:2" *)
  output valid_rx000_synt;
  NOT _081_ (
    .A(container[0]),
    .Y(_033_)
  );
  NOT _082_ (
    .A(container[1]),
    .Y(_034_)
  );
  NOT _083_ (
    .A(container[6]),
    .Y(_035_)
  );
  NOT _084_ (
    .A(counter[2]),
    .Y(_036_)
  );
  NOT _085_ (
    .A(counter[0]),
    .Y(_037_)
  );
  NOT _086_ (
    .A(reset_s),
    .Y(_038_)
  );
  NOT _087_ (
    .A(BC_counter[1]),
    .Y(_039_)
  );
  NOT _088_ (
    .A(BC_counter[2]),
    .Y(_040_)
  );
  NOT _089_ (
    .A(data_out),
    .Y(_041_)
  );
  NOT _090_ (
    .A(container[7]),
    .Y(_042_)
  );
  NOT _091_ (
    .A(container[2]),
    .Y(_043_)
  );
  NOT _092_ (
    .A(clk_32f),
    .Y(_004_)
  );
  NAND _093_ (
    .A(_039_),
    .B(BC_counter[2]),
    .Y(_044_)
  );
  NOR _094_ (
    .A(BC_counter[0]),
    .B(_044_),
    .Y(active_synt)
  );
  NAND _095_ (
    .A(container[5]),
    .B(container[4]),
    .Y(_045_)
  );
  NAND _096_ (
    .A(container[3]),
    .B(container[2]),
    .Y(_046_)
  );
  NOR _097_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  NAND _098_ (
    .A(_033_),
    .B(_034_),
    .Y(_048_)
  );
  NAND _099_ (
    .A(_035_),
    .B(container[7]),
    .Y(_049_)
  );
  NOR _100_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _101_ (
    .A(_047_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _102_ (
    .A(reset),
    .B(_051_),
    .Y(_052_)
  );
  NOR _103_ (
    .A(_040_),
    .B(_052_),
    .Y(_003_)
  );
  NOR _104_ (
    .A(BC_counter[2]),
    .B(_051_),
    .Y(_053_)
  );
  NAND _105_ (
    .A(BC_counter[0]),
    .B(_053_),
    .Y(_054_)
  );
  NOR _106_ (
    .A(BC_counter[0]),
    .B(_053_),
    .Y(_055_)
  );
  NAND _107_ (
    .A(reset_s),
    .B(_054_),
    .Y(_056_)
  );
  NOR _108_ (
    .A(_055_),
    .B(_056_),
    .Y(_000_[0])
  );
  NOR _109_ (
    .A(_039_),
    .B(_054_),
    .Y(_057_)
  );
  NAND _110_ (
    .A(_039_),
    .B(_054_),
    .Y(_058_)
  );
  NAND _111_ (
    .A(reset_s),
    .B(_058_),
    .Y(_059_)
  );
  NOR _112_ (
    .A(_057_),
    .B(_059_),
    .Y(_000_[1])
  );
  NOR _113_ (
    .A(BC_counter[2]),
    .B(_057_),
    .Y(_060_)
  );
  NOR _114_ (
    .A(_038_),
    .B(_060_),
    .Y(_000_[2])
  );
  NAND _115_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_061_)
  );
  NOT _116_ (
    .A(_061_),
    .Y(_062_)
  );
  NAND _117_ (
    .A(counter[2]),
    .B(_062_),
    .Y(_063_)
  );
  NOR _118_ (
    .A(data_out),
    .B(_063_),
    .Y(_064_)
  );
  NOT _119_ (
    .A(_064_),
    .Y(_065_)
  );
  NAND _120_ (
    .A(_042_),
    .B(_063_),
    .Y(_066_)
  );
  NAND _121_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _122_ (
    .A(reset_s),
    .B(_067_),
    .Y(_001_[7])
  );
  NOR _123_ (
    .A(counter[1]),
    .B(_037_),
    .Y(_068_)
  );
  NAND _124_ (
    .A(counter[2]),
    .B(_068_),
    .Y(_069_)
  );
  NOR _125_ (
    .A(_041_),
    .B(_069_),
    .Y(_070_)
  );
  NAND _126_ (
    .A(container[5]),
    .B(_069_),
    .Y(_071_)
  );
  NOR _127_ (
    .A(_038_),
    .B(_070_),
    .Y(_072_)
  );
  NAND _128_ (
    .A(_071_),
    .B(_072_),
    .Y(_001_[5])
  );
  NOR _129_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_073_)
  );
  NAND _130_ (
    .A(counter[2]),
    .B(_073_),
    .Y(_074_)
  );
  NOR _131_ (
    .A(_041_),
    .B(_074_),
    .Y(_075_)
  );
  NAND _132_ (
    .A(container[4]),
    .B(_074_),
    .Y(_076_)
  );
  NOR _133_ (
    .A(_038_),
    .B(_075_),
    .Y(_077_)
  );
  NAND _134_ (
    .A(_076_),
    .B(_077_),
    .Y(_001_[4])
  );
  NAND _135_ (
    .A(_036_),
    .B(_062_),
    .Y(_078_)
  );
  NOR _136_ (
    .A(_041_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _137_ (
    .A(container[3]),
    .B(_078_),
    .Y(_080_)
  );
  NOR _138_ (
    .A(_038_),
    .B(_079_),
    .Y(_012_)
  );
  NAND _139_ (
    .A(_080_),
    .B(_012_),
    .Y(_001_[3])
  );
  NAND _140_ (
    .A(counter[1]),
    .B(_037_),
    .Y(_013_)
  );
  NOR _141_ (
    .A(counter[2]),
    .B(_013_),
    .Y(_014_)
  );
  NAND _142_ (
    .A(data_out),
    .B(_014_),
    .Y(_015_)
  );
  NOR _143_ (
    .A(_043_),
    .B(_014_),
    .Y(_016_)
  );
  NOR _144_ (
    .A(_038_),
    .B(_016_),
    .Y(_017_)
  );
  NAND _145_ (
    .A(_015_),
    .B(_017_),
    .Y(_001_[2])
  );
  NAND _146_ (
    .A(_036_),
    .B(_068_),
    .Y(_018_)
  );
  NAND _147_ (
    .A(_034_),
    .B(_018_),
    .Y(_019_)
  );
  NOR _148_ (
    .A(data_out),
    .B(_018_),
    .Y(_020_)
  );
  NAND _149_ (
    .A(reset_s),
    .B(_019_),
    .Y(_021_)
  );
  NOR _150_ (
    .A(_020_),
    .B(_021_),
    .Y(_001_[1])
  );
  NAND _151_ (
    .A(_036_),
    .B(_073_),
    .Y(_022_)
  );
  NAND _152_ (
    .A(_033_),
    .B(_022_),
    .Y(_023_)
  );
  NOR _153_ (
    .A(data_out),
    .B(_022_),
    .Y(_024_)
  );
  NAND _154_ (
    .A(reset_s),
    .B(_023_),
    .Y(_025_)
  );
  NOR _155_ (
    .A(_024_),
    .B(_025_),
    .Y(_001_[0])
  );
  NOR _156_ (
    .A(_036_),
    .B(_013_),
    .Y(_026_)
  );
  NOR _157_ (
    .A(container[6]),
    .B(_026_),
    .Y(_027_)
  );
  NAND _158_ (
    .A(_041_),
    .B(_026_),
    .Y(_028_)
  );
  NAND _159_ (
    .A(reset_s),
    .B(_028_),
    .Y(_029_)
  );
  NOR _160_ (
    .A(_027_),
    .B(_029_),
    .Y(_001_[6])
  );
  NOR _161_ (
    .A(counter[0]),
    .B(_038_),
    .Y(_002_[0])
  );
  NAND _162_ (
    .A(reset_s),
    .B(_061_),
    .Y(_030_)
  );
  NOR _163_ (
    .A(_073_),
    .B(_030_),
    .Y(_002_[1])
  );
  NOR _164_ (
    .A(counter[2]),
    .B(_062_),
    .Y(_031_)
  );
  NAND _165_ (
    .A(reset_s),
    .B(_063_),
    .Y(_032_)
  );
  NOR _166_ (
    .A(_031_),
    .B(_032_),
    .Y(_002_[2])
  );
  NOT _167_ (
    .A(clk_32f),
    .Y(_005_)
  );
  NOT _168_ (
    .A(clk_32f),
    .Y(_006_)
  );
  NOT _169_ (
    .A(clk_32f),
    .Y(_007_)
  );
  NOT _170_ (
    .A(clk_32f),
    .Y(_008_)
  );
  NOT _171_ (
    .A(clk_32f),
    .Y(_009_)
  );
  NOT _172_ (
    .A(clk_32f),
    .Y(_010_)
  );
  NOT _173_ (
    .A(clk_32f),
    .Y(_011_)
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _174_ (
    .C(clk_4f),
    .D(container[0]),
    .Q(data_rx000_synt[0])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _175_ (
    .C(clk_4f),
    .D(container[1]),
    .Q(data_rx000_synt[1])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _176_ (
    .C(clk_4f),
    .D(container[2]),
    .Q(data_rx000_synt[2])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _177_ (
    .C(clk_4f),
    .D(container[3]),
    .Q(data_rx000_synt[3])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _178_ (
    .C(clk_4f),
    .D(container[4]),
    .Q(data_rx000_synt[4])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _179_ (
    .C(clk_4f),
    .D(container[5]),
    .Q(data_rx000_synt[5])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _180_ (
    .C(clk_4f),
    .D(container[6]),
    .Q(data_rx000_synt[6])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _181_ (
    .C(clk_4f),
    .D(container[7]),
    .Q(data_rx000_synt[7])
  );
  (* src = "synth_serial_paralelo1.v:65" *)
  DFF _182_ (
    .C(clk_4f),
    .D(_003_),
    .Q(valid_rx000_synt)
  );
  (* src = "synth_serial_paralelo1.v:40" *)
  DFF _183_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "synth_serial_paralelo1.v:40" *)
  DFF _184_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "synth_serial_paralelo1.v:40" *)
  DFF _185_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _186_ (
    .C(_004_),
    .D(_001_[0]),
    .Q(container[0])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _187_ (
    .C(_005_),
    .D(_001_[1]),
    .Q(container[1])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _188_ (
    .C(_006_),
    .D(_001_[2]),
    .Q(container[2])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _189_ (
    .C(_007_),
    .D(_001_[3]),
    .Q(container[3])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _190_ (
    .C(_008_),
    .D(_001_[4]),
    .Q(container[4])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _191_ (
    .C(_009_),
    .D(_001_[5]),
    .Q(container[5])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _192_ (
    .C(_010_),
    .D(_001_[6]),
    .Q(container[6])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _193_ (
    .C(_011_),
    .D(_001_[7]),
    .Q(container[7])
  );
  (* src = "synth_serial_paralelo1.v:19" *)
  DFF _194_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(counter[0])
  );
  (* src = "synth_serial_paralelo1.v:19" *)
  DFF _195_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(counter[1])
  );
  (* src = "synth_serial_paralelo1.v:19" *)
  DFF _196_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(counter[2])
  );
  (* src = "synth_serial_paralelo1.v:13" *)
  DFF _197_ (
    .C(clk_4f),
    .D(reset),
    .Q(reset_s)
  );
endmodule
