/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "synth_mux2x1_8bits.v:10" *)
module synth_mux2x1_8bits(data_000_synt, valid_000_synt, data_00, data_11, valid_00, valid_11, clk_4f, clk_2f);
  (* src = "synth_mux2x1_8bits.v:26" *)
  wire [8:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  (* src = "synth_mux2x1_8bits.v:14" *)
  input clk_2f;
  (* src = "synth_mux2x1_8bits.v:14" *)
  input clk_4f;
  (* src = "synth_mux2x1_8bits.v:12" *)
  input [7:0] data_00;
  (* src = "synth_mux2x1_8bits.v:10" *)
  output [7:0] data_000_synt;
  (* src = "synth_mux2x1_8bits.v:12" *)
  input [7:0] data_11;
  (* src = "synth_mux2x1_8bits.v:18" *)
  wire [8:0] paq_000;
  (* src = "synth_mux2x1_8bits.v:16" *)
  wire [8:0] paq_0_x;
  (* src = "synth_mux2x1_8bits.v:17" *)
  wire [8:0] paq_1_x;
  (* src = "synth_mux2x1_8bits.v:13" *)
  input valid_00;
  (* src = "synth_mux2x1_8bits.v:11" *)
  output valid_000_synt;
  (* src = "synth_mux2x1_8bits.v:13" *)
  input valid_11;
  NOT _29_ (
    .A(clk_4f),
    .Y(_09_)
  );
  NOT _30_ (
    .A(clk_2f),
    .Y(_10_)
  );
  NAND _31_ (
    .A(data_00[0]),
    .B(clk_2f),
    .Y(_11_)
  );
  NAND _32_ (
    .A(data_11[0]),
    .B(_10_),
    .Y(_12_)
  );
  NAND _33_ (
    .A(_11_),
    .B(_12_),
    .Y(_00_[1])
  );
  NAND _34_ (
    .A(clk_2f),
    .B(data_00[1]),
    .Y(_13_)
  );
  NAND _35_ (
    .A(_10_),
    .B(data_11[1]),
    .Y(_14_)
  );
  NAND _36_ (
    .A(_13_),
    .B(_14_),
    .Y(_00_[2])
  );
  NAND _37_ (
    .A(clk_2f),
    .B(data_00[2]),
    .Y(_15_)
  );
  NAND _38_ (
    .A(_10_),
    .B(data_11[2]),
    .Y(_16_)
  );
  NAND _39_ (
    .A(_15_),
    .B(_16_),
    .Y(_00_[3])
  );
  NAND _40_ (
    .A(clk_2f),
    .B(data_00[3]),
    .Y(_17_)
  );
  NAND _41_ (
    .A(_10_),
    .B(data_11[3]),
    .Y(_18_)
  );
  NAND _42_ (
    .A(_17_),
    .B(_18_),
    .Y(_00_[4])
  );
  NAND _43_ (
    .A(clk_2f),
    .B(data_00[4]),
    .Y(_19_)
  );
  NAND _44_ (
    .A(_10_),
    .B(data_11[4]),
    .Y(_20_)
  );
  NAND _45_ (
    .A(_19_),
    .B(_20_),
    .Y(_00_[5])
  );
  NAND _46_ (
    .A(clk_2f),
    .B(data_00[5]),
    .Y(_21_)
  );
  NAND _47_ (
    .A(_10_),
    .B(data_11[5]),
    .Y(_22_)
  );
  NAND _48_ (
    .A(_21_),
    .B(_22_),
    .Y(_00_[6])
  );
  NAND _49_ (
    .A(clk_2f),
    .B(data_00[6]),
    .Y(_23_)
  );
  NAND _50_ (
    .A(_10_),
    .B(data_11[6]),
    .Y(_24_)
  );
  NAND _51_ (
    .A(_23_),
    .B(_24_),
    .Y(_00_[7])
  );
  NAND _52_ (
    .A(clk_2f),
    .B(data_00[7]),
    .Y(_25_)
  );
  NAND _53_ (
    .A(_10_),
    .B(data_11[7]),
    .Y(_26_)
  );
  NAND _54_ (
    .A(_25_),
    .B(_26_),
    .Y(_00_[8])
  );
  NAND _55_ (
    .A(clk_2f),
    .B(valid_00),
    .Y(_27_)
  );
  NAND _56_ (
    .A(_10_),
    .B(valid_11),
    .Y(_28_)
  );
  NAND _57_ (
    .A(_27_),
    .B(_28_),
    .Y(_00_[0])
  );
  NOT _58_ (
    .A(clk_4f),
    .Y(_01_)
  );
  NOT _59_ (
    .A(clk_4f),
    .Y(_02_)
  );
  NOT _60_ (
    .A(clk_4f),
    .Y(_03_)
  );
  NOT _61_ (
    .A(clk_4f),
    .Y(_04_)
  );
  NOT _62_ (
    .A(clk_4f),
    .Y(_05_)
  );
  NOT _63_ (
    .A(clk_4f),
    .Y(_06_)
  );
  NOT _64_ (
    .A(clk_4f),
    .Y(_07_)
  );
  NOT _65_ (
    .A(clk_4f),
    .Y(_08_)
  );
  (* src = "synth_mux2x1_8bits.v:35" *)
  DFF _66_ (
    .C(clk_4f),
    .D(paq_000[1]),
    .Q(data_000_synt[0])
  );
  (* src = "synth_mux2x1_8bits.v:35" *)
  DFF _67_ (
    .C(clk_4f),
    .D(paq_000[2]),
    .Q(data_000_synt[1])
  );
  (* src = "synth_mux2x1_8bits.v:35" *)
  DFF _68_ (
    .C(clk_4f),
    .D(paq_000[3]),
    .Q(data_000_synt[2])
  );
  (* src = "synth_mux2x1_8bits.v:35" *)
  DFF _69_ (
    .C(clk_4f),
    .D(paq_000[4]),
    .Q(data_000_synt[3])
  );
  (* src = "synth_mux2x1_8bits.v:35" *)
  DFF _70_ (
    .C(clk_4f),
    .D(paq_000[5]),
    .Q(data_000_synt[4])
  );
  (* src = "synth_mux2x1_8bits.v:35" *)
  DFF _71_ (
    .C(clk_4f),
    .D(paq_000[6]),
    .Q(data_000_synt[5])
  );
  (* src = "synth_mux2x1_8bits.v:35" *)
  DFF _72_ (
    .C(clk_4f),
    .D(paq_000[7]),
    .Q(data_000_synt[6])
  );
  (* src = "synth_mux2x1_8bits.v:35" *)
  DFF _73_ (
    .C(clk_4f),
    .D(paq_000[8]),
    .Q(data_000_synt[7])
  );
  (* src = "synth_mux2x1_8bits.v:35" *)
  DFF _74_ (
    .C(clk_4f),
    .D(paq_000[0]),
    .Q(valid_000_synt)
  );
  (* src = "synth_mux2x1_8bits.v:26" *)
  DFF _75_ (
    .C(_01_),
    .D(_00_[0]),
    .Q(paq_000[0])
  );
  (* src = "synth_mux2x1_8bits.v:26" *)
  DFF _76_ (
    .C(_02_),
    .D(_00_[1]),
    .Q(paq_000[1])
  );
  (* src = "synth_mux2x1_8bits.v:26" *)
  DFF _77_ (
    .C(_03_),
    .D(_00_[2]),
    .Q(paq_000[2])
  );
  (* src = "synth_mux2x1_8bits.v:26" *)
  DFF _78_ (
    .C(_04_),
    .D(_00_[3]),
    .Q(paq_000[3])
  );
  (* src = "synth_mux2x1_8bits.v:26" *)
  DFF _79_ (
    .C(_05_),
    .D(_00_[4]),
    .Q(paq_000[4])
  );
  (* src = "synth_mux2x1_8bits.v:26" *)
  DFF _80_ (
    .C(_06_),
    .D(_00_[5]),
    .Q(paq_000[5])
  );
  (* src = "synth_mux2x1_8bits.v:26" *)
  DFF _81_ (
    .C(_07_),
    .D(_00_[6]),
    .Q(paq_000[6])
  );
  (* src = "synth_mux2x1_8bits.v:26" *)
  DFF _82_ (
    .C(_08_),
    .D(_00_[7]),
    .Q(paq_000[7])
  );
  (* src = "synth_mux2x1_8bits.v:26" *)
  DFF _83_ (
    .C(_09_),
    .D(_00_[8]),
    .Q(paq_000[8])
  );
  assign paq_0_x = { data_00, valid_00 };
  assign paq_1_x = { data_11, valid_11 };
endmodule
