/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "synth_idletemporal.v:1" *)
module synth_idletemporal(IDLE_OUT_synt, reset, clk_f);
  (* src = "synth_idletemporal.v:1" *)
  output IDLE_OUT_synt;
  (* src = "synth_idletemporal.v:2" *)
  input clk_f;
  (* src = "synth_idletemporal.v:2" *)
  input reset;
  (* src = "synth_idletemporal.v:4" *)
  DFF _0_ (
    .C(clk_f),
    .D(reset),
    .Q(IDLE_OUT_synt)
  );
endmodule
