/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "synth_serial_paralelo1.v:1" *)
module synth_serial_paralelo1(data_rx000_synt, valid_rx000_synt, active_synt, data_out, reset, clk_4f, clk_32f);
  (* src = "synth_serial_paralelo1.v:40" *)
  wire [2:0] _000_;
  (* src = "synth_serial_paralelo1.v:30" *)
  wire [7:0] _001_;
  (* src = "synth_serial_paralelo1.v:19" *)
  wire [2:0] _002_;
  (* src = "synth_serial_paralelo1.v:65" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  (* src = "synth_serial_paralelo1.v:9" *)
  wire [2:0] BC_counter;
  (* src = "synth_serial_paralelo1.v:2" *)
  output active_synt;
  (* src = "synth_serial_paralelo1.v:4" *)
  input clk_32f;
  (* src = "synth_serial_paralelo1.v:4" *)
  input clk_4f;
  (* src = "synth_serial_paralelo1.v:8" *)
  wire [7:0] container;
  (* src = "synth_serial_paralelo1.v:7" *)
  wire [2:0] counter;
  (* src = "synth_serial_paralelo1.v:3" *)
  input data_out;
  (* src = "synth_serial_paralelo1.v:1" *)
  output [7:0] data_rx000_synt;
  (* src = "synth_serial_paralelo1.v:3" *)
  input reset;
  (* src = "synth_serial_paralelo1.v:6" *)
  wire reset_s;
  (* src = "synth_serial_paralelo1.v:2" *)
  output valid_rx000_synt;
  NOT _081_ (
    .A(container[0]),
    .Y(_032_)
  );
  NOT _082_ (
    .A(container[1]),
    .Y(_033_)
  );
  NOT _083_ (
    .A(container[6]),
    .Y(_034_)
  );
  NOT _084_ (
    .A(counter[2]),
    .Y(_035_)
  );
  NOT _085_ (
    .A(counter[0]),
    .Y(_036_)
  );
  NOT _086_ (
    .A(reset_s),
    .Y(_037_)
  );
  NOT _087_ (
    .A(BC_counter[1]),
    .Y(_038_)
  );
  NOT _088_ (
    .A(BC_counter[2]),
    .Y(_039_)
  );
  NOT _089_ (
    .A(data_out),
    .Y(_040_)
  );
  NOT _090_ (
    .A(container[7]),
    .Y(_041_)
  );
  NOT _091_ (
    .A(container[2]),
    .Y(_042_)
  );
  NOT _092_ (
    .A(clk_32f),
    .Y(_004_)
  );
  NAND _093_ (
    .A(_038_),
    .B(BC_counter[2]),
    .Y(_043_)
  );
  NOR _094_ (
    .A(BC_counter[0]),
    .B(_043_),
    .Y(active_synt)
  );
  NAND _095_ (
    .A(container[5]),
    .B(container[4]),
    .Y(_044_)
  );
  NAND _096_ (
    .A(container[3]),
    .B(container[2]),
    .Y(_045_)
  );
  NOR _097_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  NAND _098_ (
    .A(_032_),
    .B(_033_),
    .Y(_047_)
  );
  NAND _099_ (
    .A(_034_),
    .B(container[7]),
    .Y(_048_)
  );
  NOR _100_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _101_ (
    .A(_046_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _102_ (
    .A(reset_s),
    .B(_050_),
    .Y(_051_)
  );
  NOR _103_ (
    .A(_039_),
    .B(_051_),
    .Y(_003_)
  );
  NOR _104_ (
    .A(BC_counter[2]),
    .B(_050_),
    .Y(_052_)
  );
  NAND _105_ (
    .A(BC_counter[0]),
    .B(_052_),
    .Y(_053_)
  );
  NOR _106_ (
    .A(BC_counter[0]),
    .B(_052_),
    .Y(_054_)
  );
  NAND _107_ (
    .A(reset_s),
    .B(_053_),
    .Y(_055_)
  );
  NOR _108_ (
    .A(_054_),
    .B(_055_),
    .Y(_000_[0])
  );
  NOR _109_ (
    .A(_038_),
    .B(_053_),
    .Y(_056_)
  );
  NAND _110_ (
    .A(_038_),
    .B(_053_),
    .Y(_057_)
  );
  NAND _111_ (
    .A(reset_s),
    .B(_057_),
    .Y(_058_)
  );
  NOR _112_ (
    .A(_056_),
    .B(_058_),
    .Y(_000_[1])
  );
  NOR _113_ (
    .A(BC_counter[2]),
    .B(_056_),
    .Y(_059_)
  );
  NOR _114_ (
    .A(_037_),
    .B(_059_),
    .Y(_000_[2])
  );
  NAND _115_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_060_)
  );
  NOT _116_ (
    .A(_060_),
    .Y(_061_)
  );
  NAND _117_ (
    .A(counter[2]),
    .B(_061_),
    .Y(_062_)
  );
  NOR _118_ (
    .A(data_out),
    .B(_062_),
    .Y(_063_)
  );
  NOT _119_ (
    .A(_063_),
    .Y(_064_)
  );
  NAND _120_ (
    .A(_041_),
    .B(_062_),
    .Y(_065_)
  );
  NAND _121_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _122_ (
    .A(reset_s),
    .B(_066_),
    .Y(_001_[7])
  );
  NOR _123_ (
    .A(counter[1]),
    .B(_036_),
    .Y(_067_)
  );
  NAND _124_ (
    .A(counter[2]),
    .B(_067_),
    .Y(_068_)
  );
  NOR _125_ (
    .A(_040_),
    .B(_068_),
    .Y(_069_)
  );
  NAND _126_ (
    .A(container[5]),
    .B(_068_),
    .Y(_070_)
  );
  NOR _127_ (
    .A(_037_),
    .B(_069_),
    .Y(_071_)
  );
  NAND _128_ (
    .A(_070_),
    .B(_071_),
    .Y(_001_[5])
  );
  NOR _129_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_072_)
  );
  NAND _130_ (
    .A(counter[2]),
    .B(_072_),
    .Y(_073_)
  );
  NOR _131_ (
    .A(_040_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _132_ (
    .A(container[4]),
    .B(_073_),
    .Y(_075_)
  );
  NOR _133_ (
    .A(_037_),
    .B(_074_),
    .Y(_076_)
  );
  NAND _134_ (
    .A(_075_),
    .B(_076_),
    .Y(_001_[4])
  );
  NAND _135_ (
    .A(_035_),
    .B(_061_),
    .Y(_077_)
  );
  NOR _136_ (
    .A(_040_),
    .B(_077_),
    .Y(_078_)
  );
  NAND _137_ (
    .A(container[3]),
    .B(_077_),
    .Y(_079_)
  );
  NOR _138_ (
    .A(_037_),
    .B(_078_),
    .Y(_080_)
  );
  NAND _139_ (
    .A(_079_),
    .B(_080_),
    .Y(_001_[3])
  );
  NAND _140_ (
    .A(counter[1]),
    .B(_036_),
    .Y(_012_)
  );
  NOR _141_ (
    .A(counter[2]),
    .B(_012_),
    .Y(_013_)
  );
  NAND _142_ (
    .A(data_out),
    .B(_013_),
    .Y(_014_)
  );
  NOR _143_ (
    .A(_042_),
    .B(_013_),
    .Y(_015_)
  );
  NOR _144_ (
    .A(_037_),
    .B(_015_),
    .Y(_016_)
  );
  NAND _145_ (
    .A(_014_),
    .B(_016_),
    .Y(_001_[2])
  );
  NAND _146_ (
    .A(_035_),
    .B(_067_),
    .Y(_017_)
  );
  NAND _147_ (
    .A(_033_),
    .B(_017_),
    .Y(_018_)
  );
  NOR _148_ (
    .A(data_out),
    .B(_017_),
    .Y(_019_)
  );
  NAND _149_ (
    .A(reset_s),
    .B(_018_),
    .Y(_020_)
  );
  NOR _150_ (
    .A(_019_),
    .B(_020_),
    .Y(_001_[1])
  );
  NAND _151_ (
    .A(_035_),
    .B(_072_),
    .Y(_021_)
  );
  NAND _152_ (
    .A(_032_),
    .B(_021_),
    .Y(_022_)
  );
  NOR _153_ (
    .A(data_out),
    .B(_021_),
    .Y(_023_)
  );
  NAND _154_ (
    .A(reset_s),
    .B(_022_),
    .Y(_024_)
  );
  NOR _155_ (
    .A(_023_),
    .B(_024_),
    .Y(_001_[0])
  );
  NOR _156_ (
    .A(_035_),
    .B(_012_),
    .Y(_025_)
  );
  NOR _157_ (
    .A(container[6]),
    .B(_025_),
    .Y(_026_)
  );
  NAND _158_ (
    .A(_040_),
    .B(_025_),
    .Y(_027_)
  );
  NAND _159_ (
    .A(reset_s),
    .B(_027_),
    .Y(_028_)
  );
  NOR _160_ (
    .A(_026_),
    .B(_028_),
    .Y(_001_[6])
  );
  NOR _161_ (
    .A(counter[0]),
    .B(_037_),
    .Y(_002_[0])
  );
  NAND _162_ (
    .A(reset_s),
    .B(_060_),
    .Y(_029_)
  );
  NOR _163_ (
    .A(_072_),
    .B(_029_),
    .Y(_002_[1])
  );
  NOR _164_ (
    .A(counter[2]),
    .B(_061_),
    .Y(_030_)
  );
  NAND _165_ (
    .A(reset_s),
    .B(_062_),
    .Y(_031_)
  );
  NOR _166_ (
    .A(_030_),
    .B(_031_),
    .Y(_002_[2])
  );
  NOT _167_ (
    .A(clk_32f),
    .Y(_005_)
  );
  NOT _168_ (
    .A(clk_32f),
    .Y(_006_)
  );
  NOT _169_ (
    .A(clk_32f),
    .Y(_007_)
  );
  NOT _170_ (
    .A(clk_32f),
    .Y(_008_)
  );
  NOT _171_ (
    .A(clk_32f),
    .Y(_009_)
  );
  NOT _172_ (
    .A(clk_32f),
    .Y(_010_)
  );
  NOT _173_ (
    .A(clk_32f),
    .Y(_011_)
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _174_ (
    .C(clk_4f),
    .D(container[0]),
    .Q(data_rx000_synt[0])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _175_ (
    .C(clk_4f),
    .D(container[1]),
    .Q(data_rx000_synt[1])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _176_ (
    .C(clk_4f),
    .D(container[2]),
    .Q(data_rx000_synt[2])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _177_ (
    .C(clk_4f),
    .D(container[3]),
    .Q(data_rx000_synt[3])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _178_ (
    .C(clk_4f),
    .D(container[4]),
    .Q(data_rx000_synt[4])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _179_ (
    .C(clk_4f),
    .D(container[5]),
    .Q(data_rx000_synt[5])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _180_ (
    .C(clk_4f),
    .D(container[6]),
    .Q(data_rx000_synt[6])
  );
  (* src = "synth_serial_paralelo1.v:84" *)
  DFF _181_ (
    .C(clk_4f),
    .D(container[7]),
    .Q(data_rx000_synt[7])
  );
  (* src = "synth_serial_paralelo1.v:65" *)
  DFF _182_ (
    .C(clk_4f),
    .D(_003_),
    .Q(valid_rx000_synt)
  );
  (* src = "synth_serial_paralelo1.v:40" *)
  DFF _183_ (
    .C(clk_4f),
    .D(_000_[0]),
    .Q(BC_counter[0])
  );
  (* src = "synth_serial_paralelo1.v:40" *)
  DFF _184_ (
    .C(clk_4f),
    .D(_000_[1]),
    .Q(BC_counter[1])
  );
  (* src = "synth_serial_paralelo1.v:40" *)
  DFF _185_ (
    .C(clk_4f),
    .D(_000_[2]),
    .Q(BC_counter[2])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _186_ (
    .C(_004_),
    .D(_001_[0]),
    .Q(container[0])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _187_ (
    .C(_005_),
    .D(_001_[1]),
    .Q(container[1])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _188_ (
    .C(_006_),
    .D(_001_[2]),
    .Q(container[2])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _189_ (
    .C(_007_),
    .D(_001_[3]),
    .Q(container[3])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _190_ (
    .C(_008_),
    .D(_001_[4]),
    .Q(container[4])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _191_ (
    .C(_009_),
    .D(_001_[5]),
    .Q(container[5])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _192_ (
    .C(_010_),
    .D(_001_[6]),
    .Q(container[6])
  );
  (* src = "synth_serial_paralelo1.v:30" *)
  DFF _193_ (
    .C(_011_),
    .D(_001_[7]),
    .Q(container[7])
  );
  (* src = "synth_serial_paralelo1.v:19" *)
  DFF _194_ (
    .C(clk_32f),
    .D(_002_[0]),
    .Q(counter[0])
  );
  (* src = "synth_serial_paralelo1.v:19" *)
  DFF _195_ (
    .C(clk_32f),
    .D(_002_[1]),
    .Q(counter[1])
  );
  (* src = "synth_serial_paralelo1.v:19" *)
  DFF _196_ (
    .C(clk_32f),
    .D(_002_[2]),
    .Q(counter[2])
  );
  (* src = "synth_serial_paralelo1.v:13" *)
  DFF _197_ (
    .C(clk_4f),
    .D(reset),
    .Q(reset_s)
  );
endmodule
