/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "synth_demux2x4_8bits.v:10" *)
module synth_demux2x4_8bits(data_0_synt, data_1_synt, data_2_synt, data_3_synt, valid_0_synt, valid_1_synt, valid_2_synt, valid_3_synt, data_00, data_11, valid_00, valid_11, clk_f, clk_2f);
  (* src = "synth_demux2x4_8bits.v:38" *)
  wire [7:0] _000_;
  (* src = "synth_demux2x4_8bits.v:38" *)
  wire [7:0] _001_;
  (* src = "synth_demux2x4_8bits.v:38" *)
  wire [7:0] _002_;
  (* src = "synth_demux2x4_8bits.v:38" *)
  wire [7:0] _003_;
  (* src = "synth_demux2x4_8bits.v:27" *)
  wire [8:0] _004_;
  (* src = "synth_demux2x4_8bits.v:27" *)
  wire [8:0] _005_;
  (* src = "synth_demux2x4_8bits.v:27" *)
  wire [8:0] _006_;
  (* src = "synth_demux2x4_8bits.v:27" *)
  wire [8:0] _007_;
  (* src = "synth_demux2x4_8bits.v:38" *)
  wire _008_;
  (* src = "synth_demux2x4_8bits.v:38" *)
  wire _009_;
  (* src = "synth_demux2x4_8bits.v:38" *)
  wire _010_;
  (* src = "synth_demux2x4_8bits.v:38" *)
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  (* src = "synth_demux2x4_8bits.v:16" *)
  input clk_2f;
  (* src = "synth_demux2x4_8bits.v:16" *)
  input clk_f;
  (* src = "synth_demux2x4_8bits.v:19" *)
  wire clk_f_s;
  (* src = "synth_demux2x4_8bits.v:14" *)
  input [7:0] data_00;
  (* src = "synth_demux2x4_8bits.v:10" *)
  output [7:0] data_0_synt;
  (* src = "synth_demux2x4_8bits.v:14" *)
  input [7:0] data_11;
  (* src = "synth_demux2x4_8bits.v:10" *)
  output [7:0] data_1_synt;
  (* src = "synth_demux2x4_8bits.v:11" *)
  output [7:0] data_2_synt;
  (* src = "synth_demux2x4_8bits.v:11" *)
  output [7:0] data_3_synt;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_0;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_1;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_2;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_3;
  (* src = "synth_demux2x4_8bits.v:15" *)
  input valid_00;
  (* src = "synth_demux2x4_8bits.v:12" *)
  output valid_0_synt;
  (* src = "synth_demux2x4_8bits.v:15" *)
  input valid_11;
  (* src = "synth_demux2x4_8bits.v:12" *)
  output valid_1_synt;
  (* src = "synth_demux2x4_8bits.v:13" *)
  output valid_2_synt;
  (* src = "synth_demux2x4_8bits.v:13" *)
  output valid_3_synt;
  NOT _175_ (
    .A(clk_f_s),
    .Y(_048_)
  );
  NOT _176_ (
    .A(clk_2f),
    .Y(_012_)
  );
  NAND _177_ (
    .A(paq_2[0]),
    .B(_048_),
    .Y(_049_)
  );
  NAND _178_ (
    .A(valid_0_synt),
    .B(clk_f_s),
    .Y(_050_)
  );
  NAND _179_ (
    .A(_049_),
    .B(_050_),
    .Y(_008_)
  );
  NAND _180_ (
    .A(_048_),
    .B(paq_2[1]),
    .Y(_051_)
  );
  NAND _181_ (
    .A(clk_f_s),
    .B(data_0_synt[0]),
    .Y(_052_)
  );
  NAND _182_ (
    .A(_051_),
    .B(_052_),
    .Y(_000_[0])
  );
  NAND _183_ (
    .A(_048_),
    .B(paq_2[2]),
    .Y(_053_)
  );
  NAND _184_ (
    .A(clk_f_s),
    .B(data_0_synt[1]),
    .Y(_054_)
  );
  NAND _185_ (
    .A(_053_),
    .B(_054_),
    .Y(_000_[1])
  );
  NAND _186_ (
    .A(_048_),
    .B(paq_2[3]),
    .Y(_055_)
  );
  NAND _187_ (
    .A(clk_f_s),
    .B(data_0_synt[2]),
    .Y(_056_)
  );
  NAND _188_ (
    .A(_055_),
    .B(_056_),
    .Y(_000_[2])
  );
  NAND _189_ (
    .A(_048_),
    .B(paq_2[4]),
    .Y(_057_)
  );
  NAND _190_ (
    .A(clk_f_s),
    .B(data_0_synt[3]),
    .Y(_058_)
  );
  NAND _191_ (
    .A(_057_),
    .B(_058_),
    .Y(_000_[3])
  );
  NAND _192_ (
    .A(_048_),
    .B(paq_2[5]),
    .Y(_059_)
  );
  NAND _193_ (
    .A(clk_f_s),
    .B(data_0_synt[4]),
    .Y(_060_)
  );
  NAND _194_ (
    .A(_059_),
    .B(_060_),
    .Y(_000_[4])
  );
  NAND _195_ (
    .A(_048_),
    .B(paq_2[6]),
    .Y(_061_)
  );
  NAND _196_ (
    .A(clk_f_s),
    .B(data_0_synt[5]),
    .Y(_062_)
  );
  NAND _197_ (
    .A(_061_),
    .B(_062_),
    .Y(_000_[5])
  );
  NAND _198_ (
    .A(_048_),
    .B(paq_2[7]),
    .Y(_063_)
  );
  NAND _199_ (
    .A(clk_f_s),
    .B(data_0_synt[6]),
    .Y(_064_)
  );
  NAND _200_ (
    .A(_063_),
    .B(_064_),
    .Y(_000_[6])
  );
  NAND _201_ (
    .A(_048_),
    .B(paq_2[8]),
    .Y(_065_)
  );
  NAND _202_ (
    .A(clk_f_s),
    .B(data_0_synt[7]),
    .Y(_066_)
  );
  NAND _203_ (
    .A(_065_),
    .B(_066_),
    .Y(_000_[7])
  );
  NAND _204_ (
    .A(clk_f_s),
    .B(valid_3_synt),
    .Y(_067_)
  );
  NAND _205_ (
    .A(_048_),
    .B(paq_1[0]),
    .Y(_068_)
  );
  NAND _206_ (
    .A(_067_),
    .B(_068_),
    .Y(_011_)
  );
  NAND _207_ (
    .A(_048_),
    .B(paq_3[0]),
    .Y(_069_)
  );
  NAND _208_ (
    .A(clk_f_s),
    .B(valid_11),
    .Y(_070_)
  );
  NAND _209_ (
    .A(_069_),
    .B(_070_),
    .Y(_007_[0])
  );
  NAND _210_ (
    .A(_048_),
    .B(paq_3[1]),
    .Y(_071_)
  );
  NAND _211_ (
    .A(clk_f_s),
    .B(data_11[0]),
    .Y(_072_)
  );
  NAND _212_ (
    .A(_071_),
    .B(_072_),
    .Y(_007_[1])
  );
  NAND _213_ (
    .A(_048_),
    .B(paq_3[2]),
    .Y(_073_)
  );
  NAND _214_ (
    .A(clk_f_s),
    .B(data_11[1]),
    .Y(_074_)
  );
  NAND _215_ (
    .A(_073_),
    .B(_074_),
    .Y(_007_[2])
  );
  NAND _216_ (
    .A(_048_),
    .B(paq_3[3]),
    .Y(_075_)
  );
  NAND _217_ (
    .A(clk_f_s),
    .B(data_11[2]),
    .Y(_076_)
  );
  NAND _218_ (
    .A(_075_),
    .B(_076_),
    .Y(_007_[3])
  );
  NAND _219_ (
    .A(_048_),
    .B(paq_3[4]),
    .Y(_077_)
  );
  NAND _220_ (
    .A(clk_f_s),
    .B(data_11[3]),
    .Y(_078_)
  );
  NAND _221_ (
    .A(_077_),
    .B(_078_),
    .Y(_007_[4])
  );
  NAND _222_ (
    .A(_048_),
    .B(paq_3[5]),
    .Y(_079_)
  );
  NAND _223_ (
    .A(clk_f_s),
    .B(data_11[4]),
    .Y(_080_)
  );
  NAND _224_ (
    .A(_079_),
    .B(_080_),
    .Y(_007_[5])
  );
  NAND _225_ (
    .A(_048_),
    .B(paq_3[6]),
    .Y(_081_)
  );
  NAND _226_ (
    .A(clk_f_s),
    .B(data_11[5]),
    .Y(_082_)
  );
  NAND _227_ (
    .A(_081_),
    .B(_082_),
    .Y(_007_[6])
  );
  NAND _228_ (
    .A(_048_),
    .B(paq_3[7]),
    .Y(_083_)
  );
  NAND _229_ (
    .A(clk_f_s),
    .B(data_11[6]),
    .Y(_084_)
  );
  NAND _230_ (
    .A(_083_),
    .B(_084_),
    .Y(_007_[7])
  );
  NAND _231_ (
    .A(_048_),
    .B(paq_3[8]),
    .Y(_085_)
  );
  NAND _232_ (
    .A(clk_f_s),
    .B(data_11[7]),
    .Y(_086_)
  );
  NAND _233_ (
    .A(_085_),
    .B(_086_),
    .Y(_007_[8])
  );
  NAND _234_ (
    .A(clk_f_s),
    .B(data_2_synt[0]),
    .Y(_087_)
  );
  NAND _235_ (
    .A(_071_),
    .B(_087_),
    .Y(_002_[0])
  );
  NAND _236_ (
    .A(clk_f_s),
    .B(data_2_synt[1]),
    .Y(_088_)
  );
  NAND _237_ (
    .A(_073_),
    .B(_088_),
    .Y(_002_[1])
  );
  NAND _238_ (
    .A(clk_f_s),
    .B(data_2_synt[2]),
    .Y(_089_)
  );
  NAND _239_ (
    .A(_075_),
    .B(_089_),
    .Y(_002_[2])
  );
  NAND _240_ (
    .A(clk_f_s),
    .B(data_2_synt[3]),
    .Y(_090_)
  );
  NAND _241_ (
    .A(_077_),
    .B(_090_),
    .Y(_002_[3])
  );
  NAND _242_ (
    .A(clk_f_s),
    .B(data_2_synt[4]),
    .Y(_091_)
  );
  NAND _243_ (
    .A(_079_),
    .B(_091_),
    .Y(_002_[4])
  );
  NAND _244_ (
    .A(clk_f_s),
    .B(data_2_synt[5]),
    .Y(_092_)
  );
  NAND _245_ (
    .A(_081_),
    .B(_092_),
    .Y(_002_[5])
  );
  NAND _246_ (
    .A(clk_f_s),
    .B(data_2_synt[6]),
    .Y(_093_)
  );
  NAND _247_ (
    .A(_083_),
    .B(_093_),
    .Y(_002_[6])
  );
  NAND _248_ (
    .A(clk_f_s),
    .B(data_2_synt[7]),
    .Y(_094_)
  );
  NAND _249_ (
    .A(_085_),
    .B(_094_),
    .Y(_002_[7])
  );
  NAND _250_ (
    .A(clk_f_s),
    .B(data_1_synt[0]),
    .Y(_095_)
  );
  NAND _251_ (
    .A(_048_),
    .B(paq_0[1]),
    .Y(_096_)
  );
  NAND _252_ (
    .A(_095_),
    .B(_096_),
    .Y(_001_[0])
  );
  NAND _253_ (
    .A(clk_f_s),
    .B(data_1_synt[1]),
    .Y(_097_)
  );
  NAND _254_ (
    .A(_048_),
    .B(paq_0[2]),
    .Y(_098_)
  );
  NAND _255_ (
    .A(_097_),
    .B(_098_),
    .Y(_001_[1])
  );
  NAND _256_ (
    .A(clk_f_s),
    .B(data_1_synt[2]),
    .Y(_099_)
  );
  NAND _257_ (
    .A(_048_),
    .B(paq_0[3]),
    .Y(_100_)
  );
  NAND _258_ (
    .A(_099_),
    .B(_100_),
    .Y(_001_[2])
  );
  NAND _259_ (
    .A(clk_f_s),
    .B(data_1_synt[3]),
    .Y(_101_)
  );
  NAND _260_ (
    .A(_048_),
    .B(paq_0[4]),
    .Y(_102_)
  );
  NAND _261_ (
    .A(_101_),
    .B(_102_),
    .Y(_001_[3])
  );
  NAND _262_ (
    .A(clk_f_s),
    .B(data_1_synt[4]),
    .Y(_103_)
  );
  NAND _263_ (
    .A(_048_),
    .B(paq_0[5]),
    .Y(_104_)
  );
  NAND _264_ (
    .A(_103_),
    .B(_104_),
    .Y(_001_[4])
  );
  NAND _265_ (
    .A(clk_f_s),
    .B(data_1_synt[5]),
    .Y(_105_)
  );
  NAND _266_ (
    .A(_048_),
    .B(paq_0[6]),
    .Y(_106_)
  );
  NAND _267_ (
    .A(_105_),
    .B(_106_),
    .Y(_001_[5])
  );
  NAND _268_ (
    .A(clk_f_s),
    .B(data_1_synt[6]),
    .Y(_107_)
  );
  NAND _269_ (
    .A(_048_),
    .B(paq_0[7]),
    .Y(_108_)
  );
  NAND _270_ (
    .A(_107_),
    .B(_108_),
    .Y(_001_[6])
  );
  NAND _271_ (
    .A(clk_f_s),
    .B(data_1_synt[7]),
    .Y(_109_)
  );
  NAND _272_ (
    .A(_048_),
    .B(paq_0[8]),
    .Y(_110_)
  );
  NAND _273_ (
    .A(_109_),
    .B(_110_),
    .Y(_001_[7])
  );
  NAND _274_ (
    .A(clk_f_s),
    .B(paq_0[0]),
    .Y(_111_)
  );
  NAND _275_ (
    .A(_048_),
    .B(valid_00),
    .Y(_112_)
  );
  NAND _276_ (
    .A(_111_),
    .B(_112_),
    .Y(_004_[0])
  );
  NAND _277_ (
    .A(clk_f_s),
    .B(paq_0[1]),
    .Y(_113_)
  );
  NAND _278_ (
    .A(_048_),
    .B(data_00[0]),
    .Y(_114_)
  );
  NAND _279_ (
    .A(_113_),
    .B(_114_),
    .Y(_004_[1])
  );
  NAND _280_ (
    .A(clk_f_s),
    .B(paq_0[2]),
    .Y(_115_)
  );
  NAND _281_ (
    .A(_048_),
    .B(data_00[1]),
    .Y(_116_)
  );
  NAND _282_ (
    .A(_115_),
    .B(_116_),
    .Y(_004_[2])
  );
  NAND _283_ (
    .A(clk_f_s),
    .B(paq_0[3]),
    .Y(_117_)
  );
  NAND _284_ (
    .A(_048_),
    .B(data_00[2]),
    .Y(_118_)
  );
  NAND _285_ (
    .A(_117_),
    .B(_118_),
    .Y(_004_[3])
  );
  NAND _286_ (
    .A(clk_f_s),
    .B(paq_0[4]),
    .Y(_119_)
  );
  NAND _287_ (
    .A(_048_),
    .B(data_00[3]),
    .Y(_120_)
  );
  NAND _288_ (
    .A(_119_),
    .B(_120_),
    .Y(_004_[4])
  );
  NAND _289_ (
    .A(clk_f_s),
    .B(paq_0[5]),
    .Y(_121_)
  );
  NAND _290_ (
    .A(_048_),
    .B(data_00[4]),
    .Y(_122_)
  );
  NAND _291_ (
    .A(_121_),
    .B(_122_),
    .Y(_004_[5])
  );
  NAND _292_ (
    .A(clk_f_s),
    .B(paq_0[6]),
    .Y(_123_)
  );
  NAND _293_ (
    .A(_048_),
    .B(data_00[5]),
    .Y(_124_)
  );
  NAND _294_ (
    .A(_123_),
    .B(_124_),
    .Y(_004_[6])
  );
  NAND _295_ (
    .A(clk_f_s),
    .B(paq_0[7]),
    .Y(_125_)
  );
  NAND _296_ (
    .A(_048_),
    .B(data_00[6]),
    .Y(_126_)
  );
  NAND _297_ (
    .A(_125_),
    .B(_126_),
    .Y(_004_[7])
  );
  NAND _298_ (
    .A(clk_f_s),
    .B(paq_0[8]),
    .Y(_127_)
  );
  NAND _299_ (
    .A(_048_),
    .B(data_00[7]),
    .Y(_128_)
  );
  NAND _300_ (
    .A(_127_),
    .B(_128_),
    .Y(_004_[8])
  );
  NAND _301_ (
    .A(clk_f_s),
    .B(valid_00),
    .Y(_129_)
  );
  NAND _302_ (
    .A(_049_),
    .B(_129_),
    .Y(_006_[0])
  );
  NAND _303_ (
    .A(clk_f_s),
    .B(data_00[0]),
    .Y(_130_)
  );
  NAND _304_ (
    .A(_051_),
    .B(_130_),
    .Y(_006_[1])
  );
  NAND _305_ (
    .A(clk_f_s),
    .B(data_00[1]),
    .Y(_131_)
  );
  NAND _306_ (
    .A(_053_),
    .B(_131_),
    .Y(_006_[2])
  );
  NAND _307_ (
    .A(clk_f_s),
    .B(data_00[2]),
    .Y(_132_)
  );
  NAND _308_ (
    .A(_055_),
    .B(_132_),
    .Y(_006_[3])
  );
  NAND _309_ (
    .A(clk_f_s),
    .B(data_00[3]),
    .Y(_133_)
  );
  NAND _310_ (
    .A(_057_),
    .B(_133_),
    .Y(_006_[4])
  );
  NAND _311_ (
    .A(clk_f_s),
    .B(data_00[4]),
    .Y(_134_)
  );
  NAND _312_ (
    .A(_059_),
    .B(_134_),
    .Y(_006_[5])
  );
  NAND _313_ (
    .A(clk_f_s),
    .B(data_00[5]),
    .Y(_135_)
  );
  NAND _314_ (
    .A(_061_),
    .B(_135_),
    .Y(_006_[6])
  );
  NAND _315_ (
    .A(clk_f_s),
    .B(data_00[6]),
    .Y(_136_)
  );
  NAND _316_ (
    .A(_063_),
    .B(_136_),
    .Y(_006_[7])
  );
  NAND _317_ (
    .A(clk_f_s),
    .B(data_00[7]),
    .Y(_137_)
  );
  NAND _318_ (
    .A(_065_),
    .B(_137_),
    .Y(_006_[8])
  );
  NAND _319_ (
    .A(clk_f_s),
    .B(paq_1[0]),
    .Y(_138_)
  );
  NAND _320_ (
    .A(_048_),
    .B(valid_11),
    .Y(_139_)
  );
  NAND _321_ (
    .A(_138_),
    .B(_139_),
    .Y(_005_[0])
  );
  NAND _322_ (
    .A(clk_f_s),
    .B(paq_1[1]),
    .Y(_140_)
  );
  NAND _323_ (
    .A(_048_),
    .B(data_11[0]),
    .Y(_141_)
  );
  NAND _324_ (
    .A(_140_),
    .B(_141_),
    .Y(_005_[1])
  );
  NAND _325_ (
    .A(clk_f_s),
    .B(paq_1[2]),
    .Y(_142_)
  );
  NAND _326_ (
    .A(_048_),
    .B(data_11[1]),
    .Y(_143_)
  );
  NAND _327_ (
    .A(_142_),
    .B(_143_),
    .Y(_005_[2])
  );
  NAND _328_ (
    .A(clk_f_s),
    .B(paq_1[3]),
    .Y(_144_)
  );
  NAND _329_ (
    .A(_048_),
    .B(data_11[2]),
    .Y(_145_)
  );
  NAND _330_ (
    .A(_144_),
    .B(_145_),
    .Y(_005_[3])
  );
  NAND _331_ (
    .A(clk_f_s),
    .B(paq_1[4]),
    .Y(_146_)
  );
  NAND _332_ (
    .A(_048_),
    .B(data_11[3]),
    .Y(_147_)
  );
  NAND _333_ (
    .A(_146_),
    .B(_147_),
    .Y(_005_[4])
  );
  NAND _334_ (
    .A(clk_f_s),
    .B(paq_1[5]),
    .Y(_148_)
  );
  NAND _335_ (
    .A(_048_),
    .B(data_11[4]),
    .Y(_149_)
  );
  NAND _336_ (
    .A(_148_),
    .B(_149_),
    .Y(_005_[5])
  );
  NAND _337_ (
    .A(clk_f_s),
    .B(paq_1[6]),
    .Y(_150_)
  );
  NAND _338_ (
    .A(_048_),
    .B(data_11[5]),
    .Y(_151_)
  );
  NAND _339_ (
    .A(_150_),
    .B(_151_),
    .Y(_005_[6])
  );
  NAND _340_ (
    .A(clk_f_s),
    .B(paq_1[7]),
    .Y(_152_)
  );
  NAND _341_ (
    .A(_048_),
    .B(data_11[6]),
    .Y(_153_)
  );
  NAND _342_ (
    .A(_152_),
    .B(_153_),
    .Y(_005_[7])
  );
  NAND _343_ (
    .A(clk_f_s),
    .B(paq_1[8]),
    .Y(_154_)
  );
  NAND _344_ (
    .A(_048_),
    .B(data_11[7]),
    .Y(_155_)
  );
  NAND _345_ (
    .A(_154_),
    .B(_155_),
    .Y(_005_[8])
  );
  NAND _346_ (
    .A(clk_f_s),
    .B(data_3_synt[0]),
    .Y(_156_)
  );
  NAND _347_ (
    .A(_048_),
    .B(paq_1[1]),
    .Y(_157_)
  );
  NAND _348_ (
    .A(_156_),
    .B(_157_),
    .Y(_003_[0])
  );
  NAND _349_ (
    .A(clk_f_s),
    .B(data_3_synt[1]),
    .Y(_158_)
  );
  NAND _350_ (
    .A(_048_),
    .B(paq_1[2]),
    .Y(_159_)
  );
  NAND _351_ (
    .A(_158_),
    .B(_159_),
    .Y(_003_[1])
  );
  NAND _352_ (
    .A(clk_f_s),
    .B(data_3_synt[2]),
    .Y(_160_)
  );
  NAND _353_ (
    .A(_048_),
    .B(paq_1[3]),
    .Y(_161_)
  );
  NAND _354_ (
    .A(_160_),
    .B(_161_),
    .Y(_003_[2])
  );
  NAND _355_ (
    .A(clk_f_s),
    .B(data_3_synt[3]),
    .Y(_162_)
  );
  NAND _356_ (
    .A(_048_),
    .B(paq_1[4]),
    .Y(_163_)
  );
  NAND _357_ (
    .A(_162_),
    .B(_163_),
    .Y(_003_[3])
  );
  NAND _358_ (
    .A(clk_f_s),
    .B(data_3_synt[4]),
    .Y(_164_)
  );
  NAND _359_ (
    .A(_048_),
    .B(paq_1[5]),
    .Y(_165_)
  );
  NAND _360_ (
    .A(_164_),
    .B(_165_),
    .Y(_003_[4])
  );
  NAND _361_ (
    .A(clk_f_s),
    .B(data_3_synt[5]),
    .Y(_166_)
  );
  NAND _362_ (
    .A(_048_),
    .B(paq_1[6]),
    .Y(_167_)
  );
  NAND _363_ (
    .A(_166_),
    .B(_167_),
    .Y(_003_[5])
  );
  NAND _364_ (
    .A(clk_f_s),
    .B(data_3_synt[6]),
    .Y(_168_)
  );
  NAND _365_ (
    .A(_048_),
    .B(paq_1[7]),
    .Y(_169_)
  );
  NAND _366_ (
    .A(_168_),
    .B(_169_),
    .Y(_003_[6])
  );
  NAND _367_ (
    .A(clk_f_s),
    .B(data_3_synt[7]),
    .Y(_170_)
  );
  NAND _368_ (
    .A(_048_),
    .B(paq_1[8]),
    .Y(_171_)
  );
  NAND _369_ (
    .A(_170_),
    .B(_171_),
    .Y(_003_[7])
  );
  NAND _370_ (
    .A(clk_f_s),
    .B(valid_2_synt),
    .Y(_172_)
  );
  NAND _371_ (
    .A(_069_),
    .B(_172_),
    .Y(_010_)
  );
  NAND _372_ (
    .A(clk_f_s),
    .B(valid_1_synt),
    .Y(_173_)
  );
  NAND _373_ (
    .A(_048_),
    .B(paq_0[0]),
    .Y(_174_)
  );
  NAND _374_ (
    .A(_173_),
    .B(_174_),
    .Y(_009_)
  );
  NOT _375_ (
    .A(clk_2f),
    .Y(_013_)
  );
  NOT _376_ (
    .A(clk_2f),
    .Y(_014_)
  );
  NOT _377_ (
    .A(clk_2f),
    .Y(_015_)
  );
  NOT _378_ (
    .A(clk_2f),
    .Y(_016_)
  );
  NOT _379_ (
    .A(clk_2f),
    .Y(_017_)
  );
  NOT _380_ (
    .A(clk_2f),
    .Y(_018_)
  );
  NOT _381_ (
    .A(clk_2f),
    .Y(_019_)
  );
  NOT _382_ (
    .A(clk_2f),
    .Y(_020_)
  );
  NOT _383_ (
    .A(clk_2f),
    .Y(_021_)
  );
  NOT _384_ (
    .A(clk_2f),
    .Y(_022_)
  );
  NOT _385_ (
    .A(clk_2f),
    .Y(_023_)
  );
  NOT _386_ (
    .A(clk_2f),
    .Y(_024_)
  );
  NOT _387_ (
    .A(clk_2f),
    .Y(_025_)
  );
  NOT _388_ (
    .A(clk_2f),
    .Y(_026_)
  );
  NOT _389_ (
    .A(clk_2f),
    .Y(_027_)
  );
  NOT _390_ (
    .A(clk_2f),
    .Y(_028_)
  );
  NOT _391_ (
    .A(clk_2f),
    .Y(_029_)
  );
  NOT _392_ (
    .A(clk_2f),
    .Y(_030_)
  );
  NOT _393_ (
    .A(clk_2f),
    .Y(_031_)
  );
  NOT _394_ (
    .A(clk_2f),
    .Y(_032_)
  );
  NOT _395_ (
    .A(clk_2f),
    .Y(_033_)
  );
  NOT _396_ (
    .A(clk_2f),
    .Y(_034_)
  );
  NOT _397_ (
    .A(clk_2f),
    .Y(_035_)
  );
  NOT _398_ (
    .A(clk_2f),
    .Y(_036_)
  );
  NOT _399_ (
    .A(clk_2f),
    .Y(_037_)
  );
  NOT _400_ (
    .A(clk_2f),
    .Y(_038_)
  );
  NOT _401_ (
    .A(clk_2f),
    .Y(_039_)
  );
  NOT _402_ (
    .A(clk_2f),
    .Y(_040_)
  );
  NOT _403_ (
    .A(clk_2f),
    .Y(_041_)
  );
  NOT _404_ (
    .A(clk_2f),
    .Y(_042_)
  );
  NOT _405_ (
    .A(clk_2f),
    .Y(_043_)
  );
  NOT _406_ (
    .A(clk_2f),
    .Y(_044_)
  );
  NOT _407_ (
    .A(clk_2f),
    .Y(_045_)
  );
  NOT _408_ (
    .A(clk_2f),
    .Y(_046_)
  );
  NOT _409_ (
    .A(clk_2f),
    .Y(_047_)
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _410_ (
    .C(clk_2f),
    .D(_010_),
    .Q(valid_2_synt)
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _411_ (
    .C(clk_2f),
    .D(_003_[0]),
    .Q(data_3_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _412_ (
    .C(clk_2f),
    .D(_003_[1]),
    .Q(data_3_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _413_ (
    .C(clk_2f),
    .D(_003_[2]),
    .Q(data_3_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _414_ (
    .C(clk_2f),
    .D(_003_[3]),
    .Q(data_3_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _415_ (
    .C(clk_2f),
    .D(_003_[4]),
    .Q(data_3_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _416_ (
    .C(clk_2f),
    .D(_003_[5]),
    .Q(data_3_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _417_ (
    .C(clk_2f),
    .D(_003_[6]),
    .Q(data_3_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _418_ (
    .C(clk_2f),
    .D(_003_[7]),
    .Q(data_3_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _419_ (
    .C(clk_2f),
    .D(_011_),
    .Q(valid_3_synt)
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _420_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_0_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _421_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_0_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _422_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_0_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _423_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_0_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _424_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_0_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _425_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_0_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _426_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_0_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _427_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_0_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _428_ (
    .C(clk_2f),
    .D(_008_),
    .Q(valid_0_synt)
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _429_ (
    .C(clk_2f),
    .D(_009_),
    .Q(valid_1_synt)
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _430_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(data_1_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _431_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(data_1_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _432_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(data_1_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _433_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(data_1_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _434_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(data_1_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _435_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(data_1_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _436_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(data_1_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _437_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(data_1_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _438_ (
    .C(clk_2f),
    .D(_002_[0]),
    .Q(data_2_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _439_ (
    .C(clk_2f),
    .D(_002_[1]),
    .Q(data_2_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _440_ (
    .C(clk_2f),
    .D(_002_[2]),
    .Q(data_2_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _441_ (
    .C(clk_2f),
    .D(_002_[3]),
    .Q(data_2_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _442_ (
    .C(clk_2f),
    .D(_002_[4]),
    .Q(data_2_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _443_ (
    .C(clk_2f),
    .D(_002_[5]),
    .Q(data_2_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _444_ (
    .C(clk_2f),
    .D(_002_[6]),
    .Q(data_2_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:38" *)
  DFF _445_ (
    .C(clk_2f),
    .D(_002_[7]),
    .Q(data_2_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _446_ (
    .C(_012_),
    .D(_004_[0]),
    .Q(paq_0[0])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _447_ (
    .C(_013_),
    .D(_004_[1]),
    .Q(paq_0[1])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _448_ (
    .C(_014_),
    .D(_004_[2]),
    .Q(paq_0[2])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _449_ (
    .C(_015_),
    .D(_004_[3]),
    .Q(paq_0[3])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _450_ (
    .C(_016_),
    .D(_004_[4]),
    .Q(paq_0[4])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _451_ (
    .C(_017_),
    .D(_004_[5]),
    .Q(paq_0[5])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _452_ (
    .C(_018_),
    .D(_004_[6]),
    .Q(paq_0[6])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _453_ (
    .C(_019_),
    .D(_004_[7]),
    .Q(paq_0[7])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _454_ (
    .C(_020_),
    .D(_004_[8]),
    .Q(paq_0[8])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _455_ (
    .C(_021_),
    .D(_005_[0]),
    .Q(paq_1[0])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _456_ (
    .C(_022_),
    .D(_005_[1]),
    .Q(paq_1[1])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _457_ (
    .C(_023_),
    .D(_005_[2]),
    .Q(paq_1[2])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _458_ (
    .C(_024_),
    .D(_005_[3]),
    .Q(paq_1[3])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _459_ (
    .C(_025_),
    .D(_005_[4]),
    .Q(paq_1[4])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _460_ (
    .C(_026_),
    .D(_005_[5]),
    .Q(paq_1[5])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _461_ (
    .C(_027_),
    .D(_005_[6]),
    .Q(paq_1[6])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _462_ (
    .C(_028_),
    .D(_005_[7]),
    .Q(paq_1[7])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _463_ (
    .C(_029_),
    .D(_005_[8]),
    .Q(paq_1[8])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _464_ (
    .C(_030_),
    .D(_006_[0]),
    .Q(paq_2[0])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _465_ (
    .C(_031_),
    .D(_006_[1]),
    .Q(paq_2[1])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _466_ (
    .C(_032_),
    .D(_006_[2]),
    .Q(paq_2[2])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _467_ (
    .C(_033_),
    .D(_006_[3]),
    .Q(paq_2[3])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _468_ (
    .C(_034_),
    .D(_006_[4]),
    .Q(paq_2[4])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _469_ (
    .C(_035_),
    .D(_006_[5]),
    .Q(paq_2[5])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _470_ (
    .C(_036_),
    .D(_006_[6]),
    .Q(paq_2[6])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _471_ (
    .C(_037_),
    .D(_006_[7]),
    .Q(paq_2[7])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _472_ (
    .C(_038_),
    .D(_006_[8]),
    .Q(paq_2[8])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _473_ (
    .C(_039_),
    .D(_007_[0]),
    .Q(paq_3[0])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _474_ (
    .C(_040_),
    .D(_007_[1]),
    .Q(paq_3[1])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _475_ (
    .C(_041_),
    .D(_007_[2]),
    .Q(paq_3[2])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _476_ (
    .C(_042_),
    .D(_007_[3]),
    .Q(paq_3[3])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _477_ (
    .C(_043_),
    .D(_007_[4]),
    .Q(paq_3[4])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _478_ (
    .C(_044_),
    .D(_007_[5]),
    .Q(paq_3[5])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _479_ (
    .C(_045_),
    .D(_007_[6]),
    .Q(paq_3[6])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _480_ (
    .C(_046_),
    .D(_007_[7]),
    .Q(paq_3[7])
  );
  (* src = "synth_demux2x4_8bits.v:27" *)
  DFF _481_ (
    .C(_047_),
    .D(_007_[8]),
    .Q(paq_3[8])
  );
  (* src = "synth_demux2x4_8bits.v:23" *)
  DFF _482_ (
    .C(clk_2f),
    .D(clk_f),
    .Q(clk_f_s)
  );
endmodule
