/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "synth_demux2x4_8bits.v:10" *)
module synth_demux2x4_8bits(data_rx0_synt, data_rx1_synt, data_rx2_synt, data_rx3_synt, valid_rx0_synt, valid_rx1_synt, valid_rx2_synt, valid_rx3_synt, data_rx00, data_rx11, valid_rx00, valid_rx11, clk_f, clk_2f, reset);
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire [7:0] _000_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire [7:0] _001_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire [7:0] _002_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire [7:0] _003_;
  (* src = "synth_demux2x4_8bits.v:30" *)
  wire [8:0] _004_;
  (* src = "synth_demux2x4_8bits.v:30" *)
  wire [8:0] _005_;
  (* src = "synth_demux2x4_8bits.v:30" *)
  wire [8:0] _006_;
  (* src = "synth_demux2x4_8bits.v:30" *)
  wire [8:0] _007_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire _008_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire _009_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire _010_;
  (* src = "synth_demux2x4_8bits.v:41" *)
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  (* src = "synth_demux2x4_8bits.v:16" *)
  input clk_2f;
  (* src = "synth_demux2x4_8bits.v:16" *)
  input clk_f;
  (* src = "synth_demux2x4_8bits.v:21" *)
  wire clk_f_s;
  (* src = "synth_demux2x4_8bits.v:10" *)
  output [7:0] data_rx0_synt;
  (* src = "synth_demux2x4_8bits.v:14" *)
  input [7:0] data_rx00;
  (* src = "synth_demux2x4_8bits.v:10" *)
  output [7:0] data_rx1_synt;
  (* src = "synth_demux2x4_8bits.v:14" *)
  input [7:0] data_rx11;
  (* src = "synth_demux2x4_8bits.v:11" *)
  output [7:0] data_rx2_synt;
  (* src = "synth_demux2x4_8bits.v:11" *)
  output [7:0] data_rx3_synt;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_0;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_1;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_2;
  (* src = "synth_demux2x4_8bits.v:20" *)
  wire [8:0] paq_3;
  (* src = "synth_demux2x4_8bits.v:16" *)
  input reset;
  (* src = "synth_demux2x4_8bits.v:19" *)
  wire reset_s;
  (* src = "synth_demux2x4_8bits.v:12" *)
  output valid_rx0_synt;
  (* src = "synth_demux2x4_8bits.v:15" *)
  input valid_rx00;
  (* src = "synth_demux2x4_8bits.v:12" *)
  output valid_rx1_synt;
  (* src = "synth_demux2x4_8bits.v:15" *)
  input valid_rx11;
  (* src = "synth_demux2x4_8bits.v:13" *)
  output valid_rx2_synt;
  (* src = "synth_demux2x4_8bits.v:13" *)
  output valid_rx3_synt;
  NOT _284_ (
    .A(data_rx3_synt[1]),
    .Y(_048_)
  );
  NOT _285_ (
    .A(clk_f_s),
    .Y(_049_)
  );
  NOT _286_ (
    .A(data_rx3_synt[2]),
    .Y(_050_)
  );
  NOT _287_ (
    .A(data_rx3_synt[3]),
    .Y(_051_)
  );
  NOT _288_ (
    .A(data_rx3_synt[4]),
    .Y(_052_)
  );
  NOT _289_ (
    .A(data_rx3_synt[5]),
    .Y(_053_)
  );
  NOT _290_ (
    .A(data_rx3_synt[6]),
    .Y(_054_)
  );
  NOT _291_ (
    .A(data_rx3_synt[7]),
    .Y(_055_)
  );
  NOT _292_ (
    .A(reset_s),
    .Y(_056_)
  );
  NOT _293_ (
    .A(data_rx1_synt[0]),
    .Y(_057_)
  );
  NOT _294_ (
    .A(data_rx1_synt[1]),
    .Y(_058_)
  );
  NOT _295_ (
    .A(data_rx1_synt[2]),
    .Y(_059_)
  );
  NOT _296_ (
    .A(data_rx1_synt[3]),
    .Y(_060_)
  );
  NOT _297_ (
    .A(data_rx1_synt[4]),
    .Y(_061_)
  );
  NOT _298_ (
    .A(data_rx1_synt[5]),
    .Y(_062_)
  );
  NOT _299_ (
    .A(data_rx1_synt[6]),
    .Y(_063_)
  );
  NOT _300_ (
    .A(data_rx1_synt[7]),
    .Y(_064_)
  );
  NOT _301_ (
    .A(paq_0[0]),
    .Y(_065_)
  );
  NOT _302_ (
    .A(paq_0[1]),
    .Y(_066_)
  );
  NOT _303_ (
    .A(paq_0[2]),
    .Y(_067_)
  );
  NOT _304_ (
    .A(paq_0[3]),
    .Y(_068_)
  );
  NOT _305_ (
    .A(paq_0[4]),
    .Y(_069_)
  );
  NOT _306_ (
    .A(paq_0[5]),
    .Y(_070_)
  );
  NOT _307_ (
    .A(paq_0[6]),
    .Y(_071_)
  );
  NOT _308_ (
    .A(paq_0[7]),
    .Y(_072_)
  );
  NOT _309_ (
    .A(paq_0[8]),
    .Y(_073_)
  );
  NOT _310_ (
    .A(valid_rx3_synt),
    .Y(_074_)
  );
  NOT _311_ (
    .A(paq_2[1]),
    .Y(_075_)
  );
  NOT _312_ (
    .A(paq_2[2]),
    .Y(_076_)
  );
  NOT _313_ (
    .A(paq_2[3]),
    .Y(_077_)
  );
  NOT _314_ (
    .A(paq_2[4]),
    .Y(_078_)
  );
  NOT _315_ (
    .A(paq_2[5]),
    .Y(_079_)
  );
  NOT _316_ (
    .A(paq_2[6]),
    .Y(_080_)
  );
  NOT _317_ (
    .A(paq_2[7]),
    .Y(_081_)
  );
  NOT _318_ (
    .A(paq_2[8]),
    .Y(_082_)
  );
  NOT _319_ (
    .A(valid_rx1_synt),
    .Y(_083_)
  );
  NOT _320_ (
    .A(paq_2[0]),
    .Y(_084_)
  );
  NOT _321_ (
    .A(data_rx3_synt[0]),
    .Y(_085_)
  );
  NOT _322_ (
    .A(clk_2f),
    .Y(_012_)
  );
  NOR _323_ (
    .A(clk_f_s),
    .B(paq_3[1]),
    .Y(_086_)
  );
  NAND _324_ (
    .A(clk_f_s),
    .B(_085_),
    .Y(_087_)
  );
  NAND _325_ (
    .A(reset_s),
    .B(_087_),
    .Y(_088_)
  );
  NOR _326_ (
    .A(_086_),
    .B(_088_),
    .Y(_003_[0])
  );
  NOR _327_ (
    .A(paq_3[2]),
    .B(clk_f_s),
    .Y(_089_)
  );
  NAND _328_ (
    .A(_048_),
    .B(clk_f_s),
    .Y(_090_)
  );
  NAND _329_ (
    .A(reset_s),
    .B(_090_),
    .Y(_091_)
  );
  NOR _330_ (
    .A(_089_),
    .B(_091_),
    .Y(_003_[1])
  );
  NOR _331_ (
    .A(clk_f_s),
    .B(paq_3[3]),
    .Y(_092_)
  );
  NAND _332_ (
    .A(clk_f_s),
    .B(_050_),
    .Y(_093_)
  );
  NAND _333_ (
    .A(reset_s),
    .B(_093_),
    .Y(_094_)
  );
  NOR _334_ (
    .A(_092_),
    .B(_094_),
    .Y(_003_[2])
  );
  NOR _335_ (
    .A(clk_f_s),
    .B(paq_3[4]),
    .Y(_095_)
  );
  NAND _336_ (
    .A(clk_f_s),
    .B(_051_),
    .Y(_096_)
  );
  NAND _337_ (
    .A(reset_s),
    .B(_096_),
    .Y(_097_)
  );
  NOR _338_ (
    .A(_095_),
    .B(_097_),
    .Y(_003_[3])
  );
  NOR _339_ (
    .A(clk_f_s),
    .B(paq_3[5]),
    .Y(_098_)
  );
  NAND _340_ (
    .A(clk_f_s),
    .B(_052_),
    .Y(_099_)
  );
  NAND _341_ (
    .A(reset_s),
    .B(_099_),
    .Y(_100_)
  );
  NOR _342_ (
    .A(_098_),
    .B(_100_),
    .Y(_003_[4])
  );
  NOR _343_ (
    .A(clk_f_s),
    .B(paq_3[6]),
    .Y(_101_)
  );
  NAND _344_ (
    .A(clk_f_s),
    .B(_053_),
    .Y(_102_)
  );
  NAND _345_ (
    .A(reset_s),
    .B(_102_),
    .Y(_103_)
  );
  NOR _346_ (
    .A(_101_),
    .B(_103_),
    .Y(_003_[5])
  );
  NOR _347_ (
    .A(clk_f_s),
    .B(paq_3[7]),
    .Y(_104_)
  );
  NAND _348_ (
    .A(clk_f_s),
    .B(_054_),
    .Y(_105_)
  );
  NAND _349_ (
    .A(reset_s),
    .B(_105_),
    .Y(_106_)
  );
  NOR _350_ (
    .A(_104_),
    .B(_106_),
    .Y(_003_[6])
  );
  NOR _351_ (
    .A(clk_f_s),
    .B(paq_3[8]),
    .Y(_107_)
  );
  NAND _352_ (
    .A(clk_f_s),
    .B(_055_),
    .Y(_108_)
  );
  NAND _353_ (
    .A(reset_s),
    .B(_108_),
    .Y(_109_)
  );
  NOR _354_ (
    .A(_107_),
    .B(_109_),
    .Y(_003_[7])
  );
  NOR _355_ (
    .A(clk_f_s),
    .B(paq_1[1]),
    .Y(_110_)
  );
  NAND _356_ (
    .A(clk_f_s),
    .B(_057_),
    .Y(_111_)
  );
  NAND _357_ (
    .A(reset_s),
    .B(_111_),
    .Y(_112_)
  );
  NOR _358_ (
    .A(_110_),
    .B(_112_),
    .Y(_001_[0])
  );
  NOR _359_ (
    .A(clk_f_s),
    .B(paq_1[2]),
    .Y(_113_)
  );
  NAND _360_ (
    .A(clk_f_s),
    .B(_058_),
    .Y(_114_)
  );
  NAND _361_ (
    .A(reset_s),
    .B(_114_),
    .Y(_115_)
  );
  NOR _362_ (
    .A(_113_),
    .B(_115_),
    .Y(_001_[1])
  );
  NOR _363_ (
    .A(clk_f_s),
    .B(paq_1[3]),
    .Y(_116_)
  );
  NAND _364_ (
    .A(clk_f_s),
    .B(_059_),
    .Y(_117_)
  );
  NAND _365_ (
    .A(reset_s),
    .B(_117_),
    .Y(_118_)
  );
  NOR _366_ (
    .A(_116_),
    .B(_118_),
    .Y(_001_[2])
  );
  NOR _367_ (
    .A(clk_f_s),
    .B(paq_1[4]),
    .Y(_119_)
  );
  NAND _368_ (
    .A(clk_f_s),
    .B(_060_),
    .Y(_120_)
  );
  NAND _369_ (
    .A(reset_s),
    .B(_120_),
    .Y(_121_)
  );
  NOR _370_ (
    .A(_119_),
    .B(_121_),
    .Y(_001_[3])
  );
  NOR _371_ (
    .A(clk_f_s),
    .B(paq_1[5]),
    .Y(_122_)
  );
  NAND _372_ (
    .A(clk_f_s),
    .B(_061_),
    .Y(_123_)
  );
  NAND _373_ (
    .A(reset_s),
    .B(_123_),
    .Y(_124_)
  );
  NOR _374_ (
    .A(_122_),
    .B(_124_),
    .Y(_001_[4])
  );
  NOR _375_ (
    .A(clk_f_s),
    .B(paq_1[6]),
    .Y(_125_)
  );
  NAND _376_ (
    .A(clk_f_s),
    .B(_062_),
    .Y(_126_)
  );
  NAND _377_ (
    .A(reset_s),
    .B(_126_),
    .Y(_127_)
  );
  NOR _378_ (
    .A(_125_),
    .B(_127_),
    .Y(_001_[5])
  );
  NOR _379_ (
    .A(clk_f_s),
    .B(paq_1[7]),
    .Y(_128_)
  );
  NAND _380_ (
    .A(clk_f_s),
    .B(_063_),
    .Y(_129_)
  );
  NAND _381_ (
    .A(reset_s),
    .B(_129_),
    .Y(_130_)
  );
  NOR _382_ (
    .A(_128_),
    .B(_130_),
    .Y(_001_[6])
  );
  NOR _383_ (
    .A(clk_f_s),
    .B(paq_1[8]),
    .Y(_131_)
  );
  NAND _384_ (
    .A(clk_f_s),
    .B(_064_),
    .Y(_132_)
  );
  NAND _385_ (
    .A(reset_s),
    .B(_132_),
    .Y(_133_)
  );
  NOR _386_ (
    .A(_131_),
    .B(_133_),
    .Y(_001_[7])
  );
  NOR _387_ (
    .A(clk_f_s),
    .B(_066_),
    .Y(_134_)
  );
  NAND _388_ (
    .A(_049_),
    .B(paq_0[1]),
    .Y(_135_)
  );
  NAND _389_ (
    .A(clk_f_s),
    .B(data_rx0_synt[0]),
    .Y(_136_)
  );
  NOT _390_ (
    .A(_136_),
    .Y(_137_)
  );
  NOR _391_ (
    .A(_134_),
    .B(_137_),
    .Y(_138_)
  );
  NOR _392_ (
    .A(_056_),
    .B(_138_),
    .Y(_000_[0])
  );
  NOR _393_ (
    .A(clk_f_s),
    .B(_067_),
    .Y(_139_)
  );
  NAND _394_ (
    .A(_049_),
    .B(paq_0[2]),
    .Y(_140_)
  );
  NAND _395_ (
    .A(clk_f_s),
    .B(data_rx0_synt[1]),
    .Y(_141_)
  );
  NOT _396_ (
    .A(_141_),
    .Y(_142_)
  );
  NOR _397_ (
    .A(_139_),
    .B(_142_),
    .Y(_143_)
  );
  NOR _398_ (
    .A(_056_),
    .B(_143_),
    .Y(_000_[1])
  );
  NOR _399_ (
    .A(clk_f_s),
    .B(_068_),
    .Y(_144_)
  );
  NAND _400_ (
    .A(_049_),
    .B(paq_0[3]),
    .Y(_145_)
  );
  NAND _401_ (
    .A(clk_f_s),
    .B(data_rx0_synt[2]),
    .Y(_146_)
  );
  NOT _402_ (
    .A(_146_),
    .Y(_147_)
  );
  NOR _403_ (
    .A(_144_),
    .B(_147_),
    .Y(_148_)
  );
  NOR _404_ (
    .A(_056_),
    .B(_148_),
    .Y(_000_[2])
  );
  NOR _405_ (
    .A(clk_f_s),
    .B(_069_),
    .Y(_149_)
  );
  NAND _406_ (
    .A(_049_),
    .B(paq_0[4]),
    .Y(_150_)
  );
  NAND _407_ (
    .A(clk_f_s),
    .B(data_rx0_synt[3]),
    .Y(_151_)
  );
  NOT _408_ (
    .A(_151_),
    .Y(_152_)
  );
  NOR _409_ (
    .A(_149_),
    .B(_152_),
    .Y(_153_)
  );
  NOR _410_ (
    .A(_056_),
    .B(_153_),
    .Y(_000_[3])
  );
  NOR _411_ (
    .A(clk_f_s),
    .B(_070_),
    .Y(_154_)
  );
  NAND _412_ (
    .A(_049_),
    .B(paq_0[5]),
    .Y(_155_)
  );
  NAND _413_ (
    .A(clk_f_s),
    .B(data_rx0_synt[4]),
    .Y(_156_)
  );
  NOT _414_ (
    .A(_156_),
    .Y(_157_)
  );
  NOR _415_ (
    .A(_154_),
    .B(_157_),
    .Y(_158_)
  );
  NOR _416_ (
    .A(_056_),
    .B(_158_),
    .Y(_000_[4])
  );
  NOR _417_ (
    .A(clk_f_s),
    .B(_071_),
    .Y(_159_)
  );
  NAND _418_ (
    .A(_049_),
    .B(paq_0[6]),
    .Y(_160_)
  );
  NAND _419_ (
    .A(clk_f_s),
    .B(data_rx0_synt[5]),
    .Y(_161_)
  );
  NOT _420_ (
    .A(_161_),
    .Y(_162_)
  );
  NOR _421_ (
    .A(_159_),
    .B(_162_),
    .Y(_163_)
  );
  NOR _422_ (
    .A(_056_),
    .B(_163_),
    .Y(_000_[5])
  );
  NOR _423_ (
    .A(clk_f_s),
    .B(_072_),
    .Y(_164_)
  );
  NAND _424_ (
    .A(_049_),
    .B(paq_0[7]),
    .Y(_165_)
  );
  NAND _425_ (
    .A(clk_f_s),
    .B(data_rx0_synt[6]),
    .Y(_166_)
  );
  NOT _426_ (
    .A(_166_),
    .Y(_167_)
  );
  NOR _427_ (
    .A(_164_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _428_ (
    .A(_056_),
    .B(_168_),
    .Y(_000_[6])
  );
  NOR _429_ (
    .A(clk_f_s),
    .B(_073_),
    .Y(_169_)
  );
  NAND _430_ (
    .A(_049_),
    .B(paq_0[8]),
    .Y(_170_)
  );
  NAND _431_ (
    .A(clk_f_s),
    .B(data_rx0_synt[7]),
    .Y(_171_)
  );
  NOT _432_ (
    .A(_171_),
    .Y(_172_)
  );
  NOR _433_ (
    .A(_169_),
    .B(_172_),
    .Y(_173_)
  );
  NOR _434_ (
    .A(_056_),
    .B(_173_),
    .Y(_000_[7])
  );
  NOR _435_ (
    .A(clk_f_s),
    .B(_065_),
    .Y(_174_)
  );
  NAND _436_ (
    .A(_049_),
    .B(paq_0[0]),
    .Y(_175_)
  );
  NAND _437_ (
    .A(clk_f_s),
    .B(valid_rx0_synt),
    .Y(_176_)
  );
  NOT _438_ (
    .A(_176_),
    .Y(_177_)
  );
  NOR _439_ (
    .A(_174_),
    .B(_177_),
    .Y(_178_)
  );
  NOR _440_ (
    .A(_056_),
    .B(_178_),
    .Y(_008_)
  );
  NOR _441_ (
    .A(clk_f_s),
    .B(_075_),
    .Y(_179_)
  );
  NAND _442_ (
    .A(_049_),
    .B(paq_2[1]),
    .Y(_180_)
  );
  NAND _443_ (
    .A(clk_f_s),
    .B(data_rx2_synt[0]),
    .Y(_181_)
  );
  NOT _444_ (
    .A(_181_),
    .Y(_182_)
  );
  NOR _445_ (
    .A(_179_),
    .B(_182_),
    .Y(_183_)
  );
  NOR _446_ (
    .A(_056_),
    .B(_183_),
    .Y(_002_[0])
  );
  NOR _447_ (
    .A(clk_f_s),
    .B(_076_),
    .Y(_184_)
  );
  NAND _448_ (
    .A(_049_),
    .B(paq_2[2]),
    .Y(_185_)
  );
  NAND _449_ (
    .A(clk_f_s),
    .B(data_rx2_synt[1]),
    .Y(_186_)
  );
  NOT _450_ (
    .A(_186_),
    .Y(_187_)
  );
  NOR _451_ (
    .A(_184_),
    .B(_187_),
    .Y(_188_)
  );
  NOR _452_ (
    .A(_056_),
    .B(_188_),
    .Y(_002_[1])
  );
  NOR _453_ (
    .A(clk_f_s),
    .B(_077_),
    .Y(_189_)
  );
  NAND _454_ (
    .A(_049_),
    .B(paq_2[3]),
    .Y(_190_)
  );
  NAND _455_ (
    .A(clk_f_s),
    .B(data_rx2_synt[2]),
    .Y(_191_)
  );
  NOT _456_ (
    .A(_191_),
    .Y(_192_)
  );
  NOR _457_ (
    .A(_189_),
    .B(_192_),
    .Y(_193_)
  );
  NOR _458_ (
    .A(_056_),
    .B(_193_),
    .Y(_002_[2])
  );
  NOR _459_ (
    .A(clk_f_s),
    .B(_078_),
    .Y(_194_)
  );
  NAND _460_ (
    .A(_049_),
    .B(paq_2[4]),
    .Y(_195_)
  );
  NAND _461_ (
    .A(clk_f_s),
    .B(data_rx2_synt[3]),
    .Y(_196_)
  );
  NOT _462_ (
    .A(_196_),
    .Y(_197_)
  );
  NOR _463_ (
    .A(_194_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _464_ (
    .A(_056_),
    .B(_198_),
    .Y(_002_[3])
  );
  NOR _465_ (
    .A(clk_f_s),
    .B(_079_),
    .Y(_199_)
  );
  NAND _466_ (
    .A(_049_),
    .B(paq_2[5]),
    .Y(_200_)
  );
  NAND _467_ (
    .A(clk_f_s),
    .B(data_rx2_synt[4]),
    .Y(_201_)
  );
  NOT _468_ (
    .A(_201_),
    .Y(_202_)
  );
  NOR _469_ (
    .A(_199_),
    .B(_202_),
    .Y(_203_)
  );
  NOR _470_ (
    .A(_056_),
    .B(_203_),
    .Y(_002_[4])
  );
  NOR _471_ (
    .A(clk_f_s),
    .B(_080_),
    .Y(_204_)
  );
  NAND _472_ (
    .A(_049_),
    .B(paq_2[6]),
    .Y(_205_)
  );
  NAND _473_ (
    .A(clk_f_s),
    .B(data_rx2_synt[5]),
    .Y(_206_)
  );
  NOT _474_ (
    .A(_206_),
    .Y(_207_)
  );
  NOR _475_ (
    .A(_204_),
    .B(_207_),
    .Y(_208_)
  );
  NOR _476_ (
    .A(_056_),
    .B(_208_),
    .Y(_002_[5])
  );
  NOR _477_ (
    .A(clk_f_s),
    .B(_081_),
    .Y(_209_)
  );
  NAND _478_ (
    .A(_049_),
    .B(paq_2[7]),
    .Y(_210_)
  );
  NAND _479_ (
    .A(clk_f_s),
    .B(data_rx2_synt[6]),
    .Y(_211_)
  );
  NOT _480_ (
    .A(_211_),
    .Y(_212_)
  );
  NOR _481_ (
    .A(_209_),
    .B(_212_),
    .Y(_213_)
  );
  NOR _482_ (
    .A(_056_),
    .B(_213_),
    .Y(_002_[6])
  );
  NOR _483_ (
    .A(clk_f_s),
    .B(_082_),
    .Y(_214_)
  );
  NAND _484_ (
    .A(_049_),
    .B(paq_2[8]),
    .Y(_215_)
  );
  NAND _485_ (
    .A(clk_f_s),
    .B(data_rx2_synt[7]),
    .Y(_216_)
  );
  NOT _486_ (
    .A(_216_),
    .Y(_217_)
  );
  NOR _487_ (
    .A(_214_),
    .B(_217_),
    .Y(_218_)
  );
  NOR _488_ (
    .A(_056_),
    .B(_218_),
    .Y(_002_[7])
  );
  NOR _489_ (
    .A(clk_f_s),
    .B(paq_3[0]),
    .Y(_219_)
  );
  NAND _490_ (
    .A(clk_f_s),
    .B(_074_),
    .Y(_220_)
  );
  NAND _491_ (
    .A(reset_s),
    .B(_220_),
    .Y(_221_)
  );
  NOR _492_ (
    .A(_219_),
    .B(_221_),
    .Y(_011_)
  );
  NOR _493_ (
    .A(clk_f_s),
    .B(_084_),
    .Y(_222_)
  );
  NAND _494_ (
    .A(_049_),
    .B(paq_2[0]),
    .Y(_223_)
  );
  NAND _495_ (
    .A(clk_f_s),
    .B(valid_rx2_synt),
    .Y(_224_)
  );
  NOT _496_ (
    .A(_224_),
    .Y(_225_)
  );
  NOR _497_ (
    .A(_222_),
    .B(_225_),
    .Y(_226_)
  );
  NOR _498_ (
    .A(_056_),
    .B(_226_),
    .Y(_010_)
  );
  NOR _499_ (
    .A(clk_f_s),
    .B(paq_1[0]),
    .Y(_227_)
  );
  NAND _500_ (
    .A(clk_f_s),
    .B(_083_),
    .Y(_228_)
  );
  NAND _501_ (
    .A(reset_s),
    .B(_228_),
    .Y(_229_)
  );
  NOR _502_ (
    .A(_227_),
    .B(_229_),
    .Y(_009_)
  );
  NAND _503_ (
    .A(clk_f_s),
    .B(paq_1[0]),
    .Y(_230_)
  );
  NAND _504_ (
    .A(_049_),
    .B(valid_rx00),
    .Y(_231_)
  );
  NAND _505_ (
    .A(_230_),
    .B(_231_),
    .Y(_005_[0])
  );
  NAND _506_ (
    .A(clk_f_s),
    .B(paq_1[1]),
    .Y(_232_)
  );
  NAND _507_ (
    .A(_049_),
    .B(data_rx00[0]),
    .Y(_233_)
  );
  NAND _508_ (
    .A(_232_),
    .B(_233_),
    .Y(_005_[1])
  );
  NAND _509_ (
    .A(clk_f_s),
    .B(paq_1[2]),
    .Y(_234_)
  );
  NAND _510_ (
    .A(_049_),
    .B(data_rx00[1]),
    .Y(_235_)
  );
  NAND _511_ (
    .A(_234_),
    .B(_235_),
    .Y(_005_[2])
  );
  NAND _512_ (
    .A(clk_f_s),
    .B(paq_1[3]),
    .Y(_236_)
  );
  NAND _513_ (
    .A(_049_),
    .B(data_rx00[2]),
    .Y(_237_)
  );
  NAND _514_ (
    .A(_236_),
    .B(_237_),
    .Y(_005_[3])
  );
  NAND _515_ (
    .A(clk_f_s),
    .B(paq_1[4]),
    .Y(_238_)
  );
  NAND _516_ (
    .A(_049_),
    .B(data_rx00[3]),
    .Y(_239_)
  );
  NAND _517_ (
    .A(_238_),
    .B(_239_),
    .Y(_005_[4])
  );
  NAND _518_ (
    .A(clk_f_s),
    .B(paq_1[5]),
    .Y(_240_)
  );
  NAND _519_ (
    .A(_049_),
    .B(data_rx00[4]),
    .Y(_241_)
  );
  NAND _520_ (
    .A(_240_),
    .B(_241_),
    .Y(_005_[5])
  );
  NAND _521_ (
    .A(clk_f_s),
    .B(paq_1[6]),
    .Y(_242_)
  );
  NAND _522_ (
    .A(_049_),
    .B(data_rx00[5]),
    .Y(_243_)
  );
  NAND _523_ (
    .A(_242_),
    .B(_243_),
    .Y(_005_[6])
  );
  NAND _524_ (
    .A(clk_f_s),
    .B(paq_1[7]),
    .Y(_244_)
  );
  NAND _525_ (
    .A(_049_),
    .B(data_rx00[6]),
    .Y(_245_)
  );
  NAND _526_ (
    .A(_244_),
    .B(_245_),
    .Y(_005_[7])
  );
  NAND _527_ (
    .A(clk_f_s),
    .B(paq_1[8]),
    .Y(_246_)
  );
  NAND _528_ (
    .A(_049_),
    .B(data_rx00[7]),
    .Y(_247_)
  );
  NAND _529_ (
    .A(_246_),
    .B(_247_),
    .Y(_005_[8])
  );
  NAND _530_ (
    .A(clk_f_s),
    .B(paq_3[0]),
    .Y(_248_)
  );
  NAND _531_ (
    .A(_049_),
    .B(valid_rx11),
    .Y(_249_)
  );
  NAND _532_ (
    .A(_248_),
    .B(_249_),
    .Y(_007_[0])
  );
  NAND _533_ (
    .A(clk_f_s),
    .B(paq_3[1]),
    .Y(_250_)
  );
  NAND _534_ (
    .A(_049_),
    .B(data_rx11[0]),
    .Y(_251_)
  );
  NAND _535_ (
    .A(_250_),
    .B(_251_),
    .Y(_007_[1])
  );
  NAND _536_ (
    .A(paq_3[2]),
    .B(clk_f_s),
    .Y(_252_)
  );
  NAND _537_ (
    .A(_049_),
    .B(data_rx11[1]),
    .Y(_253_)
  );
  NAND _538_ (
    .A(_252_),
    .B(_253_),
    .Y(_007_[2])
  );
  NAND _539_ (
    .A(clk_f_s),
    .B(paq_3[3]),
    .Y(_254_)
  );
  NAND _540_ (
    .A(_049_),
    .B(data_rx11[2]),
    .Y(_255_)
  );
  NAND _541_ (
    .A(_254_),
    .B(_255_),
    .Y(_007_[3])
  );
  NAND _542_ (
    .A(clk_f_s),
    .B(paq_3[4]),
    .Y(_256_)
  );
  NAND _543_ (
    .A(_049_),
    .B(data_rx11[3]),
    .Y(_257_)
  );
  NAND _544_ (
    .A(_256_),
    .B(_257_),
    .Y(_007_[4])
  );
  NAND _545_ (
    .A(clk_f_s),
    .B(paq_3[5]),
    .Y(_258_)
  );
  NAND _546_ (
    .A(_049_),
    .B(data_rx11[4]),
    .Y(_259_)
  );
  NAND _547_ (
    .A(_258_),
    .B(_259_),
    .Y(_007_[5])
  );
  NAND _548_ (
    .A(clk_f_s),
    .B(paq_3[6]),
    .Y(_260_)
  );
  NAND _549_ (
    .A(_049_),
    .B(data_rx11[5]),
    .Y(_261_)
  );
  NAND _550_ (
    .A(_260_),
    .B(_261_),
    .Y(_007_[6])
  );
  NAND _551_ (
    .A(clk_f_s),
    .B(paq_3[7]),
    .Y(_262_)
  );
  NAND _552_ (
    .A(_049_),
    .B(data_rx11[6]),
    .Y(_263_)
  );
  NAND _553_ (
    .A(_262_),
    .B(_263_),
    .Y(_007_[7])
  );
  NAND _554_ (
    .A(clk_f_s),
    .B(paq_3[8]),
    .Y(_264_)
  );
  NAND _555_ (
    .A(_049_),
    .B(data_rx11[7]),
    .Y(_265_)
  );
  NAND _556_ (
    .A(_264_),
    .B(_265_),
    .Y(_007_[8])
  );
  NAND _557_ (
    .A(clk_f_s),
    .B(valid_rx11),
    .Y(_266_)
  );
  NAND _558_ (
    .A(_223_),
    .B(_266_),
    .Y(_006_[0])
  );
  NAND _559_ (
    .A(clk_f_s),
    .B(data_rx11[0]),
    .Y(_267_)
  );
  NAND _560_ (
    .A(_180_),
    .B(_267_),
    .Y(_006_[1])
  );
  NAND _561_ (
    .A(clk_f_s),
    .B(data_rx11[1]),
    .Y(_268_)
  );
  NAND _562_ (
    .A(_185_),
    .B(_268_),
    .Y(_006_[2])
  );
  NAND _563_ (
    .A(clk_f_s),
    .B(data_rx11[2]),
    .Y(_269_)
  );
  NAND _564_ (
    .A(_190_),
    .B(_269_),
    .Y(_006_[3])
  );
  NAND _565_ (
    .A(clk_f_s),
    .B(data_rx11[3]),
    .Y(_270_)
  );
  NAND _566_ (
    .A(_195_),
    .B(_270_),
    .Y(_006_[4])
  );
  NAND _567_ (
    .A(clk_f_s),
    .B(data_rx11[4]),
    .Y(_271_)
  );
  NAND _568_ (
    .A(_200_),
    .B(_271_),
    .Y(_006_[5])
  );
  NAND _569_ (
    .A(clk_f_s),
    .B(data_rx11[5]),
    .Y(_272_)
  );
  NAND _570_ (
    .A(_205_),
    .B(_272_),
    .Y(_006_[6])
  );
  NAND _571_ (
    .A(clk_f_s),
    .B(data_rx11[6]),
    .Y(_273_)
  );
  NAND _572_ (
    .A(_210_),
    .B(_273_),
    .Y(_006_[7])
  );
  NAND _573_ (
    .A(clk_f_s),
    .B(data_rx11[7]),
    .Y(_274_)
  );
  NAND _574_ (
    .A(_215_),
    .B(_274_),
    .Y(_006_[8])
  );
  NAND _575_ (
    .A(clk_f_s),
    .B(valid_rx00),
    .Y(_275_)
  );
  NAND _576_ (
    .A(_175_),
    .B(_275_),
    .Y(_004_[0])
  );
  NAND _577_ (
    .A(clk_f_s),
    .B(data_rx00[0]),
    .Y(_276_)
  );
  NAND _578_ (
    .A(_135_),
    .B(_276_),
    .Y(_004_[1])
  );
  NAND _579_ (
    .A(clk_f_s),
    .B(data_rx00[1]),
    .Y(_277_)
  );
  NAND _580_ (
    .A(_140_),
    .B(_277_),
    .Y(_004_[2])
  );
  NAND _581_ (
    .A(clk_f_s),
    .B(data_rx00[2]),
    .Y(_278_)
  );
  NAND _582_ (
    .A(_145_),
    .B(_278_),
    .Y(_004_[3])
  );
  NAND _583_ (
    .A(clk_f_s),
    .B(data_rx00[3]),
    .Y(_279_)
  );
  NAND _584_ (
    .A(_150_),
    .B(_279_),
    .Y(_004_[4])
  );
  NAND _585_ (
    .A(clk_f_s),
    .B(data_rx00[4]),
    .Y(_280_)
  );
  NAND _586_ (
    .A(_155_),
    .B(_280_),
    .Y(_004_[5])
  );
  NAND _587_ (
    .A(clk_f_s),
    .B(data_rx00[5]),
    .Y(_281_)
  );
  NAND _588_ (
    .A(_160_),
    .B(_281_),
    .Y(_004_[6])
  );
  NAND _589_ (
    .A(clk_f_s),
    .B(data_rx00[6]),
    .Y(_282_)
  );
  NAND _590_ (
    .A(_165_),
    .B(_282_),
    .Y(_004_[7])
  );
  NAND _591_ (
    .A(clk_f_s),
    .B(data_rx00[7]),
    .Y(_283_)
  );
  NAND _592_ (
    .A(_170_),
    .B(_283_),
    .Y(_004_[8])
  );
  NOT _593_ (
    .A(clk_2f),
    .Y(_013_)
  );
  NOT _594_ (
    .A(clk_2f),
    .Y(_014_)
  );
  NOT _595_ (
    .A(clk_2f),
    .Y(_015_)
  );
  NOT _596_ (
    .A(clk_2f),
    .Y(_016_)
  );
  NOT _597_ (
    .A(clk_2f),
    .Y(_017_)
  );
  NOT _598_ (
    .A(clk_2f),
    .Y(_018_)
  );
  NOT _599_ (
    .A(clk_2f),
    .Y(_019_)
  );
  NOT _600_ (
    .A(clk_2f),
    .Y(_020_)
  );
  NOT _601_ (
    .A(clk_2f),
    .Y(_021_)
  );
  NOT _602_ (
    .A(clk_2f),
    .Y(_022_)
  );
  NOT _603_ (
    .A(clk_2f),
    .Y(_023_)
  );
  NOT _604_ (
    .A(clk_2f),
    .Y(_024_)
  );
  NOT _605_ (
    .A(clk_2f),
    .Y(_025_)
  );
  NOT _606_ (
    .A(clk_2f),
    .Y(_026_)
  );
  NOT _607_ (
    .A(clk_2f),
    .Y(_027_)
  );
  NOT _608_ (
    .A(clk_2f),
    .Y(_028_)
  );
  NOT _609_ (
    .A(clk_2f),
    .Y(_029_)
  );
  NOT _610_ (
    .A(clk_2f),
    .Y(_030_)
  );
  NOT _611_ (
    .A(clk_2f),
    .Y(_031_)
  );
  NOT _612_ (
    .A(clk_2f),
    .Y(_032_)
  );
  NOT _613_ (
    .A(clk_2f),
    .Y(_033_)
  );
  NOT _614_ (
    .A(clk_2f),
    .Y(_034_)
  );
  NOT _615_ (
    .A(clk_2f),
    .Y(_035_)
  );
  NOT _616_ (
    .A(clk_2f),
    .Y(_036_)
  );
  NOT _617_ (
    .A(clk_2f),
    .Y(_037_)
  );
  NOT _618_ (
    .A(clk_2f),
    .Y(_038_)
  );
  NOT _619_ (
    .A(clk_2f),
    .Y(_039_)
  );
  NOT _620_ (
    .A(clk_2f),
    .Y(_040_)
  );
  NOT _621_ (
    .A(clk_2f),
    .Y(_041_)
  );
  NOT _622_ (
    .A(clk_2f),
    .Y(_042_)
  );
  NOT _623_ (
    .A(clk_2f),
    .Y(_043_)
  );
  NOT _624_ (
    .A(clk_2f),
    .Y(_044_)
  );
  NOT _625_ (
    .A(clk_2f),
    .Y(_045_)
  );
  NOT _626_ (
    .A(clk_2f),
    .Y(_046_)
  );
  NOT _627_ (
    .A(clk_2f),
    .Y(_047_)
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _628_ (
    .C(clk_2f),
    .D(_010_),
    .Q(valid_rx2_synt)
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _629_ (
    .C(clk_2f),
    .D(_003_[0]),
    .Q(data_rx3_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _630_ (
    .C(clk_2f),
    .D(_003_[1]),
    .Q(data_rx3_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _631_ (
    .C(clk_2f),
    .D(_003_[2]),
    .Q(data_rx3_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _632_ (
    .C(clk_2f),
    .D(_003_[3]),
    .Q(data_rx3_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _633_ (
    .C(clk_2f),
    .D(_003_[4]),
    .Q(data_rx3_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _634_ (
    .C(clk_2f),
    .D(_003_[5]),
    .Q(data_rx3_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _635_ (
    .C(clk_2f),
    .D(_003_[6]),
    .Q(data_rx3_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _636_ (
    .C(clk_2f),
    .D(_003_[7]),
    .Q(data_rx3_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _637_ (
    .C(clk_2f),
    .D(_011_),
    .Q(valid_rx3_synt)
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _638_ (
    .C(clk_2f),
    .D(_000_[0]),
    .Q(data_rx0_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _639_ (
    .C(clk_2f),
    .D(_000_[1]),
    .Q(data_rx0_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _640_ (
    .C(clk_2f),
    .D(_000_[2]),
    .Q(data_rx0_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _641_ (
    .C(clk_2f),
    .D(_000_[3]),
    .Q(data_rx0_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _642_ (
    .C(clk_2f),
    .D(_000_[4]),
    .Q(data_rx0_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _643_ (
    .C(clk_2f),
    .D(_000_[5]),
    .Q(data_rx0_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _644_ (
    .C(clk_2f),
    .D(_000_[6]),
    .Q(data_rx0_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _645_ (
    .C(clk_2f),
    .D(_000_[7]),
    .Q(data_rx0_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _646_ (
    .C(clk_2f),
    .D(_008_),
    .Q(valid_rx0_synt)
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _647_ (
    .C(clk_2f),
    .D(_009_),
    .Q(valid_rx1_synt)
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _648_ (
    .C(clk_2f),
    .D(_001_[0]),
    .Q(data_rx1_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _649_ (
    .C(clk_2f),
    .D(_001_[1]),
    .Q(data_rx1_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _650_ (
    .C(clk_2f),
    .D(_001_[2]),
    .Q(data_rx1_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _651_ (
    .C(clk_2f),
    .D(_001_[3]),
    .Q(data_rx1_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _652_ (
    .C(clk_2f),
    .D(_001_[4]),
    .Q(data_rx1_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _653_ (
    .C(clk_2f),
    .D(_001_[5]),
    .Q(data_rx1_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _654_ (
    .C(clk_2f),
    .D(_001_[6]),
    .Q(data_rx1_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _655_ (
    .C(clk_2f),
    .D(_001_[7]),
    .Q(data_rx1_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _656_ (
    .C(clk_2f),
    .D(_002_[0]),
    .Q(data_rx2_synt[0])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _657_ (
    .C(clk_2f),
    .D(_002_[1]),
    .Q(data_rx2_synt[1])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _658_ (
    .C(clk_2f),
    .D(_002_[2]),
    .Q(data_rx2_synt[2])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _659_ (
    .C(clk_2f),
    .D(_002_[3]),
    .Q(data_rx2_synt[3])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _660_ (
    .C(clk_2f),
    .D(_002_[4]),
    .Q(data_rx2_synt[4])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _661_ (
    .C(clk_2f),
    .D(_002_[5]),
    .Q(data_rx2_synt[5])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _662_ (
    .C(clk_2f),
    .D(_002_[6]),
    .Q(data_rx2_synt[6])
  );
  (* src = "synth_demux2x4_8bits.v:41" *)
  DFF _663_ (
    .C(clk_2f),
    .D(_002_[7]),
    .Q(data_rx2_synt[7])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _664_ (
    .C(_012_),
    .D(_004_[0]),
    .Q(paq_0[0])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _665_ (
    .C(_013_),
    .D(_004_[1]),
    .Q(paq_0[1])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _666_ (
    .C(_014_),
    .D(_004_[2]),
    .Q(paq_0[2])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _667_ (
    .C(_015_),
    .D(_004_[3]),
    .Q(paq_0[3])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _668_ (
    .C(_016_),
    .D(_004_[4]),
    .Q(paq_0[4])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _669_ (
    .C(_017_),
    .D(_004_[5]),
    .Q(paq_0[5])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _670_ (
    .C(_018_),
    .D(_004_[6]),
    .Q(paq_0[6])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _671_ (
    .C(_019_),
    .D(_004_[7]),
    .Q(paq_0[7])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _672_ (
    .C(_020_),
    .D(_004_[8]),
    .Q(paq_0[8])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _673_ (
    .C(_021_),
    .D(_005_[0]),
    .Q(paq_1[0])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _674_ (
    .C(_022_),
    .D(_005_[1]),
    .Q(paq_1[1])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _675_ (
    .C(_023_),
    .D(_005_[2]),
    .Q(paq_1[2])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _676_ (
    .C(_024_),
    .D(_005_[3]),
    .Q(paq_1[3])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _677_ (
    .C(_025_),
    .D(_005_[4]),
    .Q(paq_1[4])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _678_ (
    .C(_026_),
    .D(_005_[5]),
    .Q(paq_1[5])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _679_ (
    .C(_027_),
    .D(_005_[6]),
    .Q(paq_1[6])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _680_ (
    .C(_028_),
    .D(_005_[7]),
    .Q(paq_1[7])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _681_ (
    .C(_029_),
    .D(_005_[8]),
    .Q(paq_1[8])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _682_ (
    .C(_030_),
    .D(_006_[0]),
    .Q(paq_2[0])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _683_ (
    .C(_031_),
    .D(_006_[1]),
    .Q(paq_2[1])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _684_ (
    .C(_032_),
    .D(_006_[2]),
    .Q(paq_2[2])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _685_ (
    .C(_033_),
    .D(_006_[3]),
    .Q(paq_2[3])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _686_ (
    .C(_034_),
    .D(_006_[4]),
    .Q(paq_2[4])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _687_ (
    .C(_035_),
    .D(_006_[5]),
    .Q(paq_2[5])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _688_ (
    .C(_036_),
    .D(_006_[6]),
    .Q(paq_2[6])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _689_ (
    .C(_037_),
    .D(_006_[7]),
    .Q(paq_2[7])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _690_ (
    .C(_038_),
    .D(_006_[8]),
    .Q(paq_2[8])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _691_ (
    .C(_039_),
    .D(_007_[0]),
    .Q(paq_3[0])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _692_ (
    .C(_040_),
    .D(_007_[1]),
    .Q(paq_3[1])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _693_ (
    .C(_041_),
    .D(_007_[2]),
    .Q(paq_3[2])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _694_ (
    .C(_042_),
    .D(_007_[3]),
    .Q(paq_3[3])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _695_ (
    .C(_043_),
    .D(_007_[4]),
    .Q(paq_3[4])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _696_ (
    .C(_044_),
    .D(_007_[5]),
    .Q(paq_3[5])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _697_ (
    .C(_045_),
    .D(_007_[6]),
    .Q(paq_3[6])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _698_ (
    .C(_046_),
    .D(_007_[7]),
    .Q(paq_3[7])
  );
  (* src = "synth_demux2x4_8bits.v:30" *)
  DFF _699_ (
    .C(_047_),
    .D(_007_[8]),
    .Q(paq_3[8])
  );
  (* src = "synth_demux2x4_8bits.v:24" *)
  DFF _700_ (
    .C(clk_2f),
    .D(reset),
    .Q(reset_s)
  );
  (* src = "synth_demux2x4_8bits.v:24" *)
  DFF _701_ (
    .C(clk_2f),
    .D(clk_f),
    .Q(clk_f_s)
  );
endmodule
