/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "synth_recirculacion.v:1" *)
module synth_recirculacion(data_0_synt, data_1_synt, data_2_synt, data_3_synt, valid_0_synt, valid_1_synt, valid_2_synt, valid_3_synt, data_0r_synt, data_1r_synt, data_2r_synt, data_3r_synt, valid_0r_synt, valid_1r_synt, valid_2r_synt, valid_3r_synt, data_0, data_1, data_2, data_3, valid_0, valid_1, valid_2, valid_3, IDLE_OUT);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  (* src = "synth_recirculacion.v:11" *)
  input IDLE_OUT;
  (* src = "synth_recirculacion.v:9" *)
  input [7:0] data_0;
  (* src = "synth_recirculacion.v:1" *)
  output [7:0] data_0_synt;
  (* src = "synth_recirculacion.v:5" *)
  output [7:0] data_0r_synt;
  (* src = "synth_recirculacion.v:9" *)
  input [7:0] data_1;
  (* src = "synth_recirculacion.v:1" *)
  output [7:0] data_1_synt;
  (* src = "synth_recirculacion.v:5" *)
  output [7:0] data_1r_synt;
  (* src = "synth_recirculacion.v:9" *)
  input [7:0] data_2;
  (* src = "synth_recirculacion.v:2" *)
  output [7:0] data_2_synt;
  (* src = "synth_recirculacion.v:6" *)
  output [7:0] data_2r_synt;
  (* src = "synth_recirculacion.v:9" *)
  input [7:0] data_3;
  (* src = "synth_recirculacion.v:2" *)
  output [7:0] data_3_synt;
  (* src = "synth_recirculacion.v:6" *)
  output [7:0] data_3r_synt;
  (* src = "synth_recirculacion.v:10" *)
  input valid_0;
  (* src = "synth_recirculacion.v:3" *)
  output valid_0_synt;
  (* src = "synth_recirculacion.v:7" *)
  output valid_0r_synt;
  (* src = "synth_recirculacion.v:10" *)
  input valid_1;
  (* src = "synth_recirculacion.v:3" *)
  output valid_1_synt;
  (* src = "synth_recirculacion.v:7" *)
  output valid_1r_synt;
  (* src = "synth_recirculacion.v:10" *)
  input valid_2;
  (* src = "synth_recirculacion.v:4" *)
  output valid_2_synt;
  (* src = "synth_recirculacion.v:8" *)
  output valid_2r_synt;
  (* src = "synth_recirculacion.v:10" *)
  input valid_3;
  (* src = "synth_recirculacion.v:4" *)
  output valid_3_synt;
  (* src = "synth_recirculacion.v:8" *)
  output valid_3r_synt;
  NOT _072_ (
    .A(data_3[5]),
    .Y(_000_)
  );
  NOT _073_ (
    .A(data_3[6]),
    .Y(_001_)
  );
  NOT _074_ (
    .A(data_3[7]),
    .Y(_002_)
  );
  NOT _075_ (
    .A(valid_2),
    .Y(_003_)
  );
  NOT _076_ (
    .A(data_1[0]),
    .Y(_004_)
  );
  NOT _077_ (
    .A(data_1[1]),
    .Y(_005_)
  );
  NOT _078_ (
    .A(data_1[2]),
    .Y(_006_)
  );
  NOT _079_ (
    .A(data_1[3]),
    .Y(_007_)
  );
  NOT _080_ (
    .A(data_1[4]),
    .Y(_008_)
  );
  NOT _081_ (
    .A(data_1[5]),
    .Y(_009_)
  );
  NOT _082_ (
    .A(data_1[6]),
    .Y(_010_)
  );
  NOT _083_ (
    .A(data_1[7]),
    .Y(_011_)
  );
  NOT _084_ (
    .A(data_2[0]),
    .Y(_012_)
  );
  NOT _085_ (
    .A(data_2[1]),
    .Y(_013_)
  );
  NOT _086_ (
    .A(data_2[2]),
    .Y(_014_)
  );
  NOT _087_ (
    .A(data_2[3]),
    .Y(_015_)
  );
  NOT _088_ (
    .A(data_2[4]),
    .Y(_016_)
  );
  NOT _089_ (
    .A(data_2[5]),
    .Y(_017_)
  );
  NOT _090_ (
    .A(data_2[6]),
    .Y(_018_)
  );
  NOT _091_ (
    .A(data_2[7]),
    .Y(_019_)
  );
  NOT _092_ (
    .A(valid_1),
    .Y(_020_)
  );
  NOT _093_ (
    .A(valid_3),
    .Y(_021_)
  );
  NOT _094_ (
    .A(valid_0),
    .Y(_022_)
  );
  NOT _095_ (
    .A(data_0[0]),
    .Y(_023_)
  );
  NOT _096_ (
    .A(data_0[1]),
    .Y(_024_)
  );
  NOT _097_ (
    .A(data_0[2]),
    .Y(_025_)
  );
  NOT _098_ (
    .A(data_0[3]),
    .Y(_026_)
  );
  NOT _099_ (
    .A(data_0[4]),
    .Y(_027_)
  );
  NOT _100_ (
    .A(data_0[5]),
    .Y(_028_)
  );
  NOT _101_ (
    .A(data_0[6]),
    .Y(_029_)
  );
  NOT _102_ (
    .A(data_0[7]),
    .Y(_030_)
  );
  NOT _103_ (
    .A(data_3[0]),
    .Y(_031_)
  );
  NOT _104_ (
    .A(data_3[1]),
    .Y(_032_)
  );
  NOT _105_ (
    .A(data_3[2]),
    .Y(_033_)
  );
  NOT _106_ (
    .A(data_3[3]),
    .Y(_034_)
  );
  NOT _107_ (
    .A(data_3[4]),
    .Y(_035_)
  );
  NOR _108_ (
    .A(_000_),
    .B(IDLE_OUT),
    .Y(data_3r_synt[5])
  );
  NOR _109_ (
    .A(IDLE_OUT),
    .B(_001_),
    .Y(data_3r_synt[6])
  );
  NOR _110_ (
    .A(IDLE_OUT),
    .B(_002_),
    .Y(data_3r_synt[7])
  );
  NOR _111_ (
    .A(IDLE_OUT),
    .B(_003_),
    .Y(valid_2r_synt)
  );
  NOR _112_ (
    .A(IDLE_OUT),
    .B(_004_),
    .Y(data_1r_synt[0])
  );
  NOR _113_ (
    .A(IDLE_OUT),
    .B(_005_),
    .Y(data_1r_synt[1])
  );
  NOR _114_ (
    .A(IDLE_OUT),
    .B(_006_),
    .Y(data_1r_synt[2])
  );
  NOR _115_ (
    .A(IDLE_OUT),
    .B(_007_),
    .Y(data_1r_synt[3])
  );
  NOR _116_ (
    .A(IDLE_OUT),
    .B(_008_),
    .Y(data_1r_synt[4])
  );
  NOR _117_ (
    .A(IDLE_OUT),
    .B(_009_),
    .Y(data_1r_synt[5])
  );
  NOR _118_ (
    .A(IDLE_OUT),
    .B(_010_),
    .Y(data_1r_synt[6])
  );
  NOR _119_ (
    .A(IDLE_OUT),
    .B(_011_),
    .Y(data_1r_synt[7])
  );
  NOR _120_ (
    .A(IDLE_OUT),
    .B(_012_),
    .Y(data_2r_synt[0])
  );
  NOR _121_ (
    .A(IDLE_OUT),
    .B(_013_),
    .Y(data_2r_synt[1])
  );
  NOR _122_ (
    .A(IDLE_OUT),
    .B(_014_),
    .Y(data_2r_synt[2])
  );
  NOR _123_ (
    .A(IDLE_OUT),
    .B(_015_),
    .Y(data_2r_synt[3])
  );
  NOR _124_ (
    .A(IDLE_OUT),
    .B(_016_),
    .Y(data_2r_synt[4])
  );
  NOR _125_ (
    .A(IDLE_OUT),
    .B(_017_),
    .Y(data_2r_synt[5])
  );
  NOR _126_ (
    .A(IDLE_OUT),
    .B(_018_),
    .Y(data_2r_synt[6])
  );
  NOR _127_ (
    .A(IDLE_OUT),
    .B(_019_),
    .Y(data_2r_synt[7])
  );
  NOR _128_ (
    .A(IDLE_OUT),
    .B(_020_),
    .Y(valid_1r_synt)
  );
  NAND _129_ (
    .A(IDLE_OUT),
    .B(valid_3),
    .Y(_036_)
  );
  NOT _130_ (
    .A(_036_),
    .Y(valid_3_synt)
  );
  NOR _131_ (
    .A(IDLE_OUT),
    .B(_022_),
    .Y(valid_0r_synt)
  );
  NOR _132_ (
    .A(IDLE_OUT),
    .B(_023_),
    .Y(data_0r_synt[0])
  );
  NOR _133_ (
    .A(IDLE_OUT),
    .B(_024_),
    .Y(data_0r_synt[1])
  );
  NOR _134_ (
    .A(IDLE_OUT),
    .B(_025_),
    .Y(data_0r_synt[2])
  );
  NOR _135_ (
    .A(IDLE_OUT),
    .B(_026_),
    .Y(data_0r_synt[3])
  );
  NOR _136_ (
    .A(IDLE_OUT),
    .B(_027_),
    .Y(data_0r_synt[4])
  );
  NOR _137_ (
    .A(IDLE_OUT),
    .B(_028_),
    .Y(data_0r_synt[5])
  );
  NOR _138_ (
    .A(IDLE_OUT),
    .B(_029_),
    .Y(data_0r_synt[6])
  );
  NOR _139_ (
    .A(IDLE_OUT),
    .B(_030_),
    .Y(data_0r_synt[7])
  );
  NAND _140_ (
    .A(IDLE_OUT),
    .B(data_2[0]),
    .Y(_037_)
  );
  NOT _141_ (
    .A(_037_),
    .Y(data_2_synt[0])
  );
  NAND _142_ (
    .A(IDLE_OUT),
    .B(data_2[1]),
    .Y(_038_)
  );
  NOT _143_ (
    .A(_038_),
    .Y(data_2_synt[1])
  );
  NAND _144_ (
    .A(IDLE_OUT),
    .B(data_2[2]),
    .Y(_039_)
  );
  NOT _145_ (
    .A(_039_),
    .Y(data_2_synt[2])
  );
  NAND _146_ (
    .A(IDLE_OUT),
    .B(data_2[3]),
    .Y(_040_)
  );
  NOT _147_ (
    .A(_040_),
    .Y(data_2_synt[3])
  );
  NAND _148_ (
    .A(IDLE_OUT),
    .B(data_2[4]),
    .Y(_041_)
  );
  NOT _149_ (
    .A(_041_),
    .Y(data_2_synt[4])
  );
  NAND _150_ (
    .A(IDLE_OUT),
    .B(data_2[5]),
    .Y(_042_)
  );
  NOT _151_ (
    .A(_042_),
    .Y(data_2_synt[5])
  );
  NAND _152_ (
    .A(IDLE_OUT),
    .B(data_2[6]),
    .Y(_043_)
  );
  NOT _153_ (
    .A(_043_),
    .Y(data_2_synt[6])
  );
  NAND _154_ (
    .A(IDLE_OUT),
    .B(data_2[7]),
    .Y(_044_)
  );
  NOT _155_ (
    .A(_044_),
    .Y(data_2_synt[7])
  );
  NAND _156_ (
    .A(IDLE_OUT),
    .B(data_3[0]),
    .Y(_045_)
  );
  NOT _157_ (
    .A(_045_),
    .Y(data_3_synt[0])
  );
  NAND _158_ (
    .A(IDLE_OUT),
    .B(data_3[1]),
    .Y(_046_)
  );
  NOT _159_ (
    .A(_046_),
    .Y(data_3_synt[1])
  );
  NAND _160_ (
    .A(IDLE_OUT),
    .B(data_3[2]),
    .Y(_047_)
  );
  NOT _161_ (
    .A(_047_),
    .Y(data_3_synt[2])
  );
  NAND _162_ (
    .A(IDLE_OUT),
    .B(data_3[3]),
    .Y(_048_)
  );
  NOT _163_ (
    .A(_048_),
    .Y(data_3_synt[3])
  );
  NAND _164_ (
    .A(IDLE_OUT),
    .B(data_3[4]),
    .Y(_049_)
  );
  NOT _165_ (
    .A(_049_),
    .Y(data_3_synt[4])
  );
  NAND _166_ (
    .A(data_3[5]),
    .B(IDLE_OUT),
    .Y(_050_)
  );
  NOT _167_ (
    .A(_050_),
    .Y(data_3_synt[5])
  );
  NAND _168_ (
    .A(IDLE_OUT),
    .B(data_3[6]),
    .Y(_051_)
  );
  NOT _169_ (
    .A(_051_),
    .Y(data_3_synt[6])
  );
  NAND _170_ (
    .A(IDLE_OUT),
    .B(data_3[7]),
    .Y(_052_)
  );
  NOT _171_ (
    .A(_052_),
    .Y(data_3_synt[7])
  );
  NAND _172_ (
    .A(IDLE_OUT),
    .B(valid_2),
    .Y(_053_)
  );
  NOT _173_ (
    .A(_053_),
    .Y(valid_2_synt)
  );
  NAND _174_ (
    .A(IDLE_OUT),
    .B(valid_0),
    .Y(_054_)
  );
  NOT _175_ (
    .A(_054_),
    .Y(valid_0_synt)
  );
  NAND _176_ (
    .A(IDLE_OUT),
    .B(valid_1),
    .Y(_055_)
  );
  NOT _177_ (
    .A(_055_),
    .Y(valid_1_synt)
  );
  NAND _178_ (
    .A(IDLE_OUT),
    .B(data_1[0]),
    .Y(_056_)
  );
  NOT _179_ (
    .A(_056_),
    .Y(data_1_synt[0])
  );
  NAND _180_ (
    .A(IDLE_OUT),
    .B(data_1[1]),
    .Y(_057_)
  );
  NOT _181_ (
    .A(_057_),
    .Y(data_1_synt[1])
  );
  NAND _182_ (
    .A(IDLE_OUT),
    .B(data_1[2]),
    .Y(_058_)
  );
  NOT _183_ (
    .A(_058_),
    .Y(data_1_synt[2])
  );
  NAND _184_ (
    .A(IDLE_OUT),
    .B(data_1[3]),
    .Y(_059_)
  );
  NOT _185_ (
    .A(_059_),
    .Y(data_1_synt[3])
  );
  NAND _186_ (
    .A(IDLE_OUT),
    .B(data_1[4]),
    .Y(_060_)
  );
  NOT _187_ (
    .A(_060_),
    .Y(data_1_synt[4])
  );
  NAND _188_ (
    .A(IDLE_OUT),
    .B(data_1[5]),
    .Y(_061_)
  );
  NOT _189_ (
    .A(_061_),
    .Y(data_1_synt[5])
  );
  NAND _190_ (
    .A(IDLE_OUT),
    .B(data_1[6]),
    .Y(_062_)
  );
  NOT _191_ (
    .A(_062_),
    .Y(data_1_synt[6])
  );
  NAND _192_ (
    .A(IDLE_OUT),
    .B(data_1[7]),
    .Y(_063_)
  );
  NOT _193_ (
    .A(_063_),
    .Y(data_1_synt[7])
  );
  NAND _194_ (
    .A(IDLE_OUT),
    .B(data_0[0]),
    .Y(_064_)
  );
  NOT _195_ (
    .A(_064_),
    .Y(data_0_synt[0])
  );
  NAND _196_ (
    .A(IDLE_OUT),
    .B(data_0[1]),
    .Y(_065_)
  );
  NOT _197_ (
    .A(_065_),
    .Y(data_0_synt[1])
  );
  NAND _198_ (
    .A(IDLE_OUT),
    .B(data_0[2]),
    .Y(_066_)
  );
  NOT _199_ (
    .A(_066_),
    .Y(data_0_synt[2])
  );
  NAND _200_ (
    .A(IDLE_OUT),
    .B(data_0[3]),
    .Y(_067_)
  );
  NOT _201_ (
    .A(_067_),
    .Y(data_0_synt[3])
  );
  NAND _202_ (
    .A(IDLE_OUT),
    .B(data_0[4]),
    .Y(_068_)
  );
  NOT _203_ (
    .A(_068_),
    .Y(data_0_synt[4])
  );
  NAND _204_ (
    .A(IDLE_OUT),
    .B(data_0[5]),
    .Y(_069_)
  );
  NOT _205_ (
    .A(_069_),
    .Y(data_0_synt[5])
  );
  NAND _206_ (
    .A(IDLE_OUT),
    .B(data_0[6]),
    .Y(_070_)
  );
  NOT _207_ (
    .A(_070_),
    .Y(data_0_synt[6])
  );
  NAND _208_ (
    .A(IDLE_OUT),
    .B(data_0[7]),
    .Y(_071_)
  );
  NOT _209_ (
    .A(_071_),
    .Y(data_0_synt[7])
  );
  NOR _210_ (
    .A(IDLE_OUT),
    .B(_021_),
    .Y(valid_3r_synt)
  );
  NOR _211_ (
    .A(IDLE_OUT),
    .B(_031_),
    .Y(data_3r_synt[0])
  );
  NOR _212_ (
    .A(IDLE_OUT),
    .B(_032_),
    .Y(data_3r_synt[1])
  );
  NOR _213_ (
    .A(IDLE_OUT),
    .B(_033_),
    .Y(data_3r_synt[2])
  );
  NOR _214_ (
    .A(IDLE_OUT),
    .B(_034_),
    .Y(data_3r_synt[3])
  );
  NOR _215_ (
    .A(IDLE_OUT),
    .B(_035_),
    .Y(data_3r_synt[4])
  );
endmodule
